# データ保存

In [1]:
import os
os.environ["SPEDAS_DATA_DIR"] = "/mnt/j/observation_data/"

# PWE-EFDのスペクトルを見てみる

In [4]:
import math
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta
from pathlib import Path

import pyspedas as psp
import pytplot as pt
import ergpyspedas.erg as ergpy

pt.del_data('*')

time_range = ['20200301/00:00:00', '20200401/00:00:00']

ERG_LOAD_RETRY_DELAYS_SEC = (0, 30, 120, 300)


def load_erg_with_retry(
    load_func,
    *,
    description,
    expected_tplot_vars=(),
    validate_result=None,
    retry_delays_sec=ERG_LOAD_RETRY_DELAYS_SEC,
    **load_kwargs,
):
    """ergpy loadと出力検証を、待機時間を延ばしながら再試行する。"""
    retry_delays_sec = tuple(float(delay) for delay in retry_delays_sec)
    if len(retry_delays_sec) == 0:
        raise ValueError("retry_delays_secには少なくとも初回試行を指定する。")
    if any((not math.isfinite(delay)) or delay < 0 for delay in retry_delays_sec):
        raise ValueError("retry delayは有限の非負値で指定する。")

    expected_tplot_vars = tuple(expected_tplot_vars)
    last_error = None

    for attempt, delay_sec in enumerate(retry_delays_sec, start=1):
        if delay_sec > 0:
            print(
                f"waiting {delay_sec:g} s before {description} attempt "
                f"{attempt}/{len(retry_delays_sec)}"
            )
            time.sleep(delay_sec)

        # 前回試行のtplot変数を成功判定に使わない。
        for var_name in expected_tplot_vars:
            pt.del_data(var_name)

        try:
            result = load_func(**load_kwargs)

            missing_vars = []
            for var_name in expected_tplot_vars:
                data = psp.get_data(var_name, xarray=True)
                if data is None or getattr(data, "size", 0) == 0:
                    missing_vars.append(var_name)
            if missing_vars:
                raise RuntimeError(
                    f"required tplot variables were not created: {missing_vars}"
                )

            if validate_result is not None and not validate_result(result):
                raise RuntimeError("ergpy loader returned no usable result")

            print(
                f"{description} succeeded on attempt "
                f"{attempt}/{len(retry_delays_sec)}"
            )
            return result
        except Exception as err:
            last_error = err
            print(
                f"{description} failed on attempt "
                f"{attempt}/{len(retry_delays_sec)}: {err}"
            )

    raise RuntimeError(
        f"{description} failed after {len(retry_delays_sec)} attempts"
    ) from last_error


ERG_PREFETCH_BLOCK_DAYS = 7
ERG_PREFETCH_MAX_WORKERS = 8


def _normalize_download_files(result):
    if result is None:
        return []
    if isinstance(result, (str, Path)):
        return [str(result)]
    return list(dict.fromkeys(str(path) for path in result))


def _download_result_has_local_files(result):
    files = _normalize_download_files(result)
    return len(files) > 0 and all(Path(path).is_file() for path in files)


def _build_prefetch_blocks(trange, block_days=ERG_PREFETCH_BLOCK_DAYS):
    start = datetime.strptime(trange[0], "%Y%m%d/%H:%M:%S")
    end = datetime.strptime(trange[1], "%Y%m%d/%H:%M:%S")
    if start >= end:
        raise ValueError("prefetch trangeはstart < endにする。")

    blocks = []
    cursor = start
    while cursor < end:
        block_end = min(cursor + timedelta(days=int(block_days)), end)
        query_end = block_end - timedelta(seconds=1)
        blocks.append([
            cursor.strftime("%Y%m%d/%H:%M:%S"),
            query_end.strftime("%Y%m%d/%H:%M:%S"),
        ])
        cursor = block_end
    return blocks


def prefetch_erg_downloads(
    specs,
    trange,
    max_workers=ERG_PREFETCH_MAX_WORKERS,
    block_days=ERG_PREFETCH_BLOCK_DAYS,
):
    """downloadonlyのblockを並列取得する。tplot展開は呼び出し側で逐次行う。"""
    blocks = _build_prefetch_blocks(trange, block_days=block_days)
    tasks = [
        (description, load_func, load_kwargs, block)
        for description, load_func, load_kwargs in specs
        for block in blocks
    ]
    worker_count = max(1, min(int(max_workers), len(tasks)))
    print(f"ERG prefetch blocks : {len(tasks)}")
    print(f"ERG prefetch workers: {worker_count}")

    def prefetch_one(description, load_func, load_kwargs, block):
        kwargs = dict(load_kwargs)
        kwargs.update({
            "trange": block,
            "downloadonly": True,
            "no_update": False,
            "ror": False,
        })
        result = load_erg_with_retry(
            load_func,
            description=(
                f"{description} prefetch "
                f"[{block[0]} -- {block[1]}]"
            ),
            validate_result=_download_result_has_local_files,
            **kwargs,
        )
        return _normalize_download_files(result)

    files_by_task = {}
    failures = []
    with ThreadPoolExecutor(max_workers=worker_count) as executor:
        futures = {
            executor.submit(
                prefetch_one, description, load_func, load_kwargs, block
            ): (description, block)
            for description, load_func, load_kwargs, block in tasks
        }
        for future in as_completed(futures):
            description, block = futures[future]
            key = (description, block[0], block[1])
            try:
                files_by_task[key] = future.result()
            except Exception as err:
                failures.append((description, block, repr(err)))

    if failures:
        for description, block, error in failures:
            print(f"prefetch failed: {description} {block} ({error})")
        raise RuntimeError(
            f"ERG prefetch failed for {len(failures)}/{len(tasks)} block(s)"
        )

    print(f"ERG prefetch complete: {len(files_by_task)}/{len(tasks)} block(s)")
    return files_by_task


ERG_PREFETCH_SPECS = (
    (
        "PWE-EFD L2 spectrum",
        ergpy.pwe_efd,
        {"level": "l2", "datatype": "spec", "get_support_data": True},
    ),
    (
        "PWE-EFD L2 64 Hz",
        ergpy.pwe_efd,
        {
            "level": "l2",
            "datatype": "64",
            "coord": "dsi",
            "get_support_data": True,
        },
    ),
    (
        "LEPe L2 omniflux",
        ergpy.lepe,
        {"datatype": "omniflux", "level": "l2"},
    ),
    (
        "LEPi L2 omniflux",
        ergpy.lepi,
        {"datatype": "omniflux", "level": "l2"},
    ),
    (
        "PWE-HFA L3",
        ergpy.pwe_hfa,
        {"level": "l3"},
    ),
)

ERG_prefetch_files = prefetch_erg_downloads(
    ERG_PREFETCH_SPECS,
    time_range,
    max_workers=ERG_PREFETCH_MAX_WORKERS,
    block_days=ERG_PREFETCH_BLOCK_DAYS,
)


load_erg_with_retry(
    ergpy.pwe_efd,
    description="PWE-EFD L2 spectrum load",
    expected_tplot_vars=(
        "erg_pwe_efd_l2_spec_spectra",
        "erg_pwe_efd_l2_spec_quality_flag",
    ),
    trange=time_range,
    level="l2",
    datatype="spec",
    get_support_data=True,
    no_update=True,
)

29-Sep-26 17:27:54: del_data: No valid tplot variables found, returning
29-Sep-26 17:27:54: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/
29-Sep-26 17:28:17: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/
29-Sep-26 17:28:36: Remote index took 42.8 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 17:28:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200301_v02_04.cdf
29-Sep-26 17:28:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200302_v02_04.cdf
29-Sep-26 17:29:03: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200303_v02_04.cdf
29-Sep-26 17:29:25: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200304_v02_04.cdf
29-Sep-26 17:29:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200304_v02_04.cdf
29-Sep-26 17:29:50: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200305_v02_04.cdf
29-Sep-26 17:29:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200305_v02_04.cdf
29-Sep-26 17:29:59: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200306_v02_04.cdf
29-Sep-26 17:30:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200307_v02_04.cdf
29-Sep-26 17:30:23: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200308_v02_04.cdf
29-Sep-26 17:30:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200308_v02_04.cdf
29-Sep-26 17:30:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200309_v02_04.cdf
29-Sep-26 17:30:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200310_v02_04.cdf
29-Sep-26 17:30:33: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200311_v02_04.cdf
29-Sep-26 17:30:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200312_v02_04.cdf
29-Sep-26 17:30:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200313_v02_04.cdf
29-Sep-26 17:30:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200314_v02_04.cdf
29-Sep-26 17:30:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200315_v02_04.cdf
29-Sep-26 17:30:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200316_v02_04.cdf
29-Sep-26 17:30:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200317_v02_04.cdf
29-Sep-26 17:30:46: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200318_v02_04.cdf
29-Sep-26 17:30:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200319_v02_04.cdf
29-Sep-26 17:30:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200320_v02_04.cdf
29-Sep-26 17:30:52: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200321_v02_04.cdf
29-Sep-26 17:31:11: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200322_v02_04.cdf
29-Sep-26 17:31:35: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200323_v02_04.cdf
29-Sep-26 17:31:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200323_v02_04.cdf
29-Sep-26 17:31:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200324_v02_04.cdf
29-Sep-26 17:32:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200325_v02_04.cdf
29-Sep-26 17:32:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200326_v02_04.cdf
29-Sep-26 17:32:30: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200327_v02_04.cdf
29-Sep-26 17:32:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200328_v02_04.cdf
29-Sep-26 17:32:52: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200329_v02_04.cdf
29-Sep-26 17:33:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200330_v02_04.cdf
29-Sep-26 17:33:04: File is current: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/spec/2020/03/erg_pwe_efd_l2_spec_20200331_v02_04.cdf

printing PI info and rules of the road was failed

['erg_pwe_efd_l2_spec_Epoch',
 'erg_pwe_efd_l2_spec_spectra',
 'erg_pwe_efd_l2_spec_quality_flag',
 'erg_pwe_efd_l2_spec_WPT1_3_BIAS_LVL',
 'erg_pwe_efd_l2_spec_WPT2_4_BIAS_LVL',
 'erg_pwe_efd_l2_spec_frequency',
 'erg_pwe_efd_l2_spec_frequency_100hz',
 'erg_pwe_efd_l2_spec_TI_corrected',
 'erg_pwe_efd_l2_spec_TI_original',
 'erg_pwe_efd_l2_spec_band_width']

In [5]:
efd_spectra         = psp.get_data('erg_pwe_efd_l2_spec_spectra', xarray=True).sortby('time')
efd_spectra_flag    = psp.get_data('erg_pwe_efd_l2_spec_quality_flag', xarray=True).sortby('time')

bad_times = efd_spectra_flag.time.where(efd_spectra_flag != 0, drop=True)

print(efd_spectra)
print('')
print(efd_spectra_flag)
print('')
print(bad_times)

<xarray.DataArray 'erg_pwe_efd_l2_spec_spectra' (time: 2637793, v_dim: 100)> Size: 1GB
array([[8.5514078e+00, 2.1829189e-01, 6.2378887e-05, ..., 9.2904666e-05,
        6.2956085e-04, 4.7210377e-04],
       [1.2079185e+01, 3.4596932e-01, 9.8863861e-04, ..., 2.9379036e-04,
        2.8121448e-04, 7.4823410e-04],
       [9.5948372e+00, 2.7481321e-01, 1.1092709e-04, ..., 6.5771473e-04,
        7.9257012e-04, 1.0569087e-03],
       ...,
       [1.7062299e+00, 5.4832447e-02, 1.5668868e-04, ..., 3.2963822e-04,
        1.4094111e-04, 1.0569087e-03],
       [3.0341539e+00, 8.6903572e-02, 5.5595243e-04, ..., 1.6521047e-04,
        8.8927831e-04, 8.3953241e-04],
       [3.0341539e+00, 8.6903572e-02, 9.8863866e-06, ..., 1.1696005e-04,
        7.0637884e-04, 1.1858712e-03]],
      shape=(2637793, 100), dtype=float32)
Coordinates:
  * time       (time) datetime64[ns] 21MB 2020-03-01T00:00:13.064606 ... 2020...
    spec_bins  (v_dim) float32 400B 1.0 2.0 3.0 4.0 ... 196.5 204.5 212.5 220.5
    v          (v_dim) float32 400B 1.0 2.0 3.0 4.0 ... 196.5 204.5 212.5 220.5
Dimensions without coordinates: v_dim
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'spectra', 'CATDESC': 'EFD onboard s...
    data_att:      {'coord_sys': '', 'units': '(mV/m)^2/Hz', 'depend_1_units'...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...

<xarray.DataArray 'erg_pwe_efd_l2_spec_quality_flag' (time: 2637793)> Size: 11MB
array([12, 12, 12, ...,  0,  0,  0], shape=(2637793,), dtype=uint32)
Coordinates:
  * time     (time) datetime64[ns] 21MB 2020-03-01T00:00:13.064606 ... 2020-0...
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'quality flag', 'CATDESC': 'quality ...
    data_att:      {'coord_sys': '', 'units': 'None', 'depend_1_units': None,...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...

<xarray.DataArray 'time' (time: 378905)> Size: 3MB
array(['2020-03-01T00:00:13.064606000', '2020-03-01T00:00:14.064606000',
       '2020-03-01T00:00:15.064606000', ...,
       '2020-03-31T22:12:49.570555000', '2020-03-31T22:12:50.570555000',
       '2020-03-31T22:12:51.570555000'],
      shape=(378905,), dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 3MB 2020-03-01T00:00:13.064606 ... 2020-03...

In [6]:
import numpy as np

qf_on_spec = efd_spectra_flag.reindex(
    time=efd_spectra.time,
    method="nearest",
    tolerance=np.timedelta64(500, "ms")
)

efd_spectra_qf = efd_spectra.where(qf_on_spec == 0, np.nan)

# LEP-i, LEP-eのデータ存在時間の確認

In [9]:
load_erg_with_retry(
    ergpy.lepe,
    description="LEPe L2 omniflux load",
    expected_tplot_vars=("erg_lepe_l2_omniflux_FEDO",),
    trange=time_range,
    datatype="omniflux",
    level="l2",
    no_update=True,
)

29-Sep-26 17:36:08: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/lepe/l2/omniflux/2020/03/
29-Sep-26 17:36:29: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepe/l2/omniflux/2020/03/
29-Sep-26 17:36:39: Remote index took 30.5 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 17:36:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200301_v05_01.cdf
29-Sep-26 17:36:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200302_v05_01.cdf
29-Sep-26 17:36:44: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200303_v05_01.cdf
29-Sep-26 17:36:47: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200304_v05_01.cdf
29-Sep-26 17:36:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200305_v05_01.cdf
29-Sep-26 17:36:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200306_v05_01.cdf
29-Sep-26 17:36:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200307_v05_01.cdf
29-Sep-26 17:36:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200308_v05_01.cdf
29-Sep-26 17:37:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200309_v05_01.cdf
29-Sep-26 17:37:08: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200310_v05_01.cdf
29-Sep-26 17:37:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200311_v05_01.cdf
29-Sep-26 17:37:41: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200312_v05_01.cdf
29-Sep-26 17:37:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200312_v05_01.cdf
29-Sep-26 17:37:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200313_v05_01.cdf
29-Sep-26 17:38:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200314_v05_01.cdf
29-Sep-26 17:38:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200315_v05_01.cdf
29-Sep-26 17:38:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200316_v05_01.cdf
29-Sep-26 17:38:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200317_v05_01.cdf
29-Sep-26 17:38:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200318_v05_01.cdf
29-Sep-26 17:38:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200319_v05_01.cdf
29-Sep-26 17:38:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200320_v05_01.cdf
29-Sep-26 17:38:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200321_v05_01.cdf
29-Sep-26 17:38:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200322_v05_01.cdf
29-Sep-26 17:38:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200323_v05_01.cdf
29-Sep-26 17:38:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200324_v05_01.cdf
29-Sep-26 17:38:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200325_v05_01.cdf
29-Sep-26 17:38:58: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200326_v05_01.cdf
29-Sep-26 17:39:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200327_v05_01.cdf
29-Sep-26 17:39:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200328_v05_01.cdf
29-Sep-26 17:39:44: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200329_v05_01.cdf
29-Sep-26 17:39:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200330_v05_01.cdf
29-Sep-26 17:39:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepe/l2/omniflux/2020/03/erg_lepe_l2_omniflux_20200331_v05_01.cdf
29-Sep-26 17:39:56: erg_lepe_l2_omniflux_fedo contains negative values; setting the z-axis to log scale will cause the negative values to be ignored on figures.
29-Sep-26 17:39:56: erg_lepe_l2_omniflux_FEDO contains negative values; setting the z-axis to log scale will cause the negative values to be ignored on figures.

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Low-Energy Particle experiments - electron analyzer (LEP-e) Level 2 omni electron flux data']

Information about ERG LEPe

PI:  ['Shiang-Yu Wang']
Affiliation:  ['Academia Sinica, Taiwan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of LEPe L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Lepe

Contact: erg_lepe_info at isee.nagoya-u.ac.jp
**************************************************************************

['erg_lepe_l2_omniflux_FEDO']

In [10]:
load_erg_with_retry(
    ergpy.lepi,
    description="LEPi L2 omniflux load",
    expected_tplot_vars=("erg_lepi_l2_omniflux_FPDO",),
    trange=time_range,
    datatype="omniflux",
    level="l2",
    no_update=True,
)

29-Sep-26 17:39:56: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/
29-Sep-26 17:40:18: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/
29-Sep-26 17:40:45: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/
29-Sep-26 17:41:16: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/
29-Sep-26 17:41:27: Remote index took 90.2 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 17:41:28: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200301_v03_00.cdf
29-Sep-26 17:41:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200301_v03_00.cdf
29-Sep-26 17:41:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200302_v03_00.cdf
29-Sep-26 17:41:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200303_v03_00.cdf
29-Sep-26 17:42:03: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200304_v03_00.cdf
29-Sep-26 17:42:05: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200305_v03_00.cdf
29-Sep-26 17:42:08: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200306_v03_00.cdf
29-Sep-26 17:42:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200307_v03_00.cdf
29-Sep-26 17:42:34: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200308_v03_00.cdf
29-Sep-26 17:42:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200309_v03_00.cdf
29-Sep-26 17:42:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200310_v03_00.cdf
29-Sep-26 17:42:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200311_v03_00.cdf
29-Sep-26 17:42:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200312_v03_00.cdf
29-Sep-26 17:43:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200313_v03_00.cdf
29-Sep-26 17:43:12: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200314_v03_00.cdf
29-Sep-26 17:43:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200315_v03_00.cdf
29-Sep-26 17:43:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200316_v03_00.cdf
29-Sep-26 17:43:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200317_v03_00.cdf
29-Sep-26 17:43:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200318_v03_00.cdf
29-Sep-26 17:43:47: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200319_v03_00.cdf
29-Sep-26 17:44:07: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200320_v03_00.cdf
29-Sep-26 17:44:28: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200321_v03_00.cdf
29-Sep-26 17:44:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200321_v03_00.cdf
29-Sep-26 17:45:04: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200322_v03_00.cdf
29-Sep-26 17:45:07: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200322_v03_00.cdf
29-Sep-26 17:45:31: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200323_v03_00.cdf
29-Sep-26 17:45:52: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200323_v03_00.cdf
29-Sep-26 17:46:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200324_v03_00.cdf
29-Sep-26 17:46:36: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200325_v03_00.cdf
29-Sep-26 17:46:46: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200325_v03_00.cdf
29-Sep-26 17:46:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200326_v03_00.cdf
29-Sep-26 17:47:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200327_v03_00.cdf
29-Sep-26 17:47:06: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200328_v03_00.cdf
29-Sep-26 17:47:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200329_v03_00.cdf
29-Sep-26 17:47:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200330_v03_00.cdf
29-Sep-26 17:47:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/lepi/l2/omniflux/2020/03/erg_lepi_l2_omniflux_20200331_v03_00.cdf

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Low Energy Particle Ion (LEPi) Experiment 3D ion flux data']

Information about ERG LEPi

PI:  ['Kazushi Asamura']
Affiliation:  ['ISAS, Jaxa']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of LEPi L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Lepi
RoR of ERG/LEPi: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Lepi#Rules_of_the_Road

Contact: erg_lepi_info at isee.nagoya-u.ac.jp
**************************************************************************

['erg_lepi_l2_omniflux_Epoch',
 'erg_lepi_l2_omniflux_FPDO',
 'erg_lepi_l2_omniflux_FHEDO',
 'erg_lepi_l2_omniflux_FODO',
 'erg_lepi_l2_omniflux_FPDO_raw',
 'erg_lepi_l2_omniflux_FHEDO_raw',
 'erg_lepi_l2_omniflux_FODO_raw']

In [11]:
LEPe_FEDO_omniflux = psp.get_data('erg_lepe_l2_omniflux_FEDO', xarray=True).sortby('time')
LEPi_FPDO_omniflux = psp.get_data('erg_lepi_l2_omniflux_FPDO', xarray=True).sortby('time')

In [12]:
import numpy as np
import pandas as pd
import xarray as xr


def merge_omniflux_gap_ranges(
    gap_ranges_df,
    merge_gap_tolerance=pd.Timedelta(seconds=0),
):
    """
    gap_start_time/gap_end_time が重なる、接する、または
    merge_gap_tolerance 以下の短い good island を挟む gap 行を merge する。

    reason は統合元が分かるように '+' で連結する。
    """

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "reason",
        "bad_start_time",
        "bad_end_time",
        "bad_duration_sec",
        "bad_duration_min",
        "n_bad_time_samples",
        "n_invalid_values",
        "invalid_fraction_max",
        "invalid_fraction_mean",
    ]

    if gap_ranges_df is None or len(gap_ranges_df) == 0:
        return pd.DataFrame(columns=columns)

    df = gap_ranges_df.copy()
    df["gap_start_time"] = pd.to_datetime(df["gap_start_time"])
    df["gap_end_time"] = pd.to_datetime(df["gap_end_time"])
    df = df.dropna(subset=["gap_start_time", "gap_end_time"])
    df = df[df["gap_end_time"] >= df["gap_start_time"]]
    df = df.sort_values(["gap_start_time", "gap_end_time"]).reset_index(drop=True)

    if len(df) == 0:
        return pd.DataFrame(columns=columns)

    merge_gap_tolerance = pd.Timedelta(merge_gap_tolerance)

    groups = []
    current = [0]
    current_end = df.loc[0, "gap_end_time"]

    for idx in range(1, len(df)):
        start = df.loc[idx, "gap_start_time"]
        end = df.loc[idx, "gap_end_time"]

        if start <= current_end + merge_gap_tolerance:
            current.append(idx)
            if end > current_end:
                current_end = end
        else:
            groups.append(current)
            current = [idx]
            current_end = end

    groups.append(current)

    merged_rows = []

    for group in groups:
        g = df.loc[group]
        gap_start = g["gap_start_time"].min()
        gap_end = g["gap_end_time"].max()
        gap_dt = gap_end - gap_start

        reasons = []
        for reason in g["reason"].dropna().astype(str):
            for part in reason.split("+"):
                if part not in reasons:
                    reasons.append(part)

        bad_starts = pd.to_datetime(g["bad_start_time"], errors="coerce").dropna()
        bad_ends = pd.to_datetime(g["bad_end_time"], errors="coerce").dropna()

        n_bad = pd.to_numeric(g["n_bad_time_samples"], errors="coerce").fillna(0)
        n_invalid = pd.to_numeric(g["n_invalid_values"], errors="coerce").fillna(0)
        invalid_max = pd.to_numeric(g["invalid_fraction_max"], errors="coerce")
        invalid_mean = pd.to_numeric(g["invalid_fraction_mean"], errors="coerce")

        valid_mean = invalid_mean.notna() & (n_bad > 0)
        if valid_mean.any():
            invalid_fraction_mean = float(
                np.average(invalid_mean[valid_mean], weights=n_bad[valid_mean])
            )
        else:
            invalid_fraction_mean = np.nan

        bad_duration = pd.to_numeric(g["bad_duration_sec"], errors="coerce").sum(min_count=1)

        merged_rows.append({
            "gap_start_time": gap_start,
            "gap_end_time": gap_end,
            "gap_duration_sec": gap_dt.total_seconds(),
            "gap_duration_min": gap_dt.total_seconds() / 60,
            "reason": "+".join(reasons),
            "bad_start_time": bad_starts.min() if len(bad_starts) > 0 else pd.NaT,
            "bad_end_time": bad_ends.max() if len(bad_ends) > 0 else pd.NaT,
            "bad_duration_sec": float(bad_duration) if pd.notna(bad_duration) else np.nan,
            "bad_duration_min": float(bad_duration) / 60 if pd.notna(bad_duration) else np.nan,
            "n_bad_time_samples": int(n_bad.sum()),
            "n_invalid_values": int(n_invalid.sum()),
            "invalid_fraction_max": float(invalid_max.max()) if invalid_max.notna().any() else np.nan,
            "invalid_fraction_mean": invalid_fraction_mean,
        })

    return pd.DataFrame(merged_rows, columns=columns).reset_index(drop=True)


def find_time_gaps_with_bad_omniflux(
    flux_da,
    threshold=pd.Timedelta(minutes=1),
    min_bad_duration=pd.Timedelta(seconds=30),
    invalid_fraction_threshold=0.3,
    time_dim="time",
    include_nonfinite=True,
    include_negative=True,
    merge_gap_ranges=True,
    merge_gap_tolerance=pd.Timedelta(seconds=0),
):
    """
    time gap に加えて、
    omniflux の使用不可データ割合が invalid_fraction_threshold 以上の状態が
    min_bad_duration 以上継続した場合に bad time gap として抽出する。

    Parameters
    ----------
    flux_da : xr.DataArray
        例: erg_lepe_l2_omniflux_FEDO
        dims は通常 (time, energy) を想定。
    threshold : pd.Timedelta
        隣接時刻差がこの値以上なら通常の time gap とみなす。
    min_bad_duration : pd.Timedelta
        bad 状態がこの時間以上継続した場合のみ gap として採用する。
    invalid_fraction_threshold : float
        各時刻で使用不可データがこの割合以上なら bad sample とする。
        例: 0.3 なら 30%以上。
    time_dim : str
        時間次元名。
    include_nonfinite : bool
        True の場合、NaN/inf を使用不可とみなす。
    include_negative : bool
        True の場合、負値を使用不可とみなす。
    merge_gap_ranges : bool
        True の場合、検出後に重なる/接する gap 行を merge する。
    merge_gap_tolerance : pd.Timedelta
        gap 同士の間にこの時間以下の短い good island がある場合も merge する。
        0秒なら重なりまたは接している区間だけを merge する。

    Returns
    -------
    gap_ranges_df : pd.DataFrame
    """

    da = flux_da.sortby(time_dim)
    times = pd.DatetimeIndex(pd.to_datetime(da[time_dim].values))

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "reason",
        "bad_start_time",
        "bad_end_time",
        "bad_duration_sec",
        "bad_duration_min",
        "n_bad_time_samples",
        "n_invalid_values",
        "invalid_fraction_max",
        "invalid_fraction_mean",
    ]

    if len(times) == 0:
        return pd.DataFrame(columns=columns)

    rows = []

    # ============================================================
    # 1. 通常の time gap
    # ============================================================
    if len(times) >= 2:
        dt = times[1:] - times[:-1]
        gap_mask = dt >= threshold

        for i in np.where(gap_mask)[0]:
            rows.append({
                "gap_start_time": times[i],
                "gap_end_time": times[i + 1],
                "gap_duration_sec": dt[i].total_seconds(),
                "gap_duration_min": dt[i].total_seconds() / 60,
                "reason": "time_gap",
                "bad_start_time": pd.NaT,
                "bad_end_time": pd.NaT,
                "bad_duration_sec": np.nan,
                "bad_duration_min": np.nan,
                "n_bad_time_samples": 0,
                "n_invalid_values": 0,
                "invalid_fraction_max": np.nan,
                "invalid_fraction_mean": np.nan,
            })

    # ============================================================
    # 2. 使用不可データ割合を評価
    # ============================================================
    reduce_dims = [d for d in da.dims if d != time_dim]

    invalid_da = xr.zeros_like(da, dtype=bool)

    if include_nonfinite:
        invalid_da = invalid_da | (~np.isfinite(da))

    if include_negative:
        invalid_da = invalid_da | (da < 0)

    if len(reduce_dims) > 0:
        n_invalid_each_time = invalid_da.sum(dim=reduce_dims)
        n_total_each_time = xr.ones_like(invalid_da, dtype=int).sum(dim=reduce_dims)

        invalid_fraction = n_invalid_each_time / n_total_each_time
        bad_time = invalid_fraction >= invalid_fraction_threshold

        n_invalid_each_time = n_invalid_each_time.values.astype(int)
        invalid_fraction_each_time = invalid_fraction.values.astype(float)
        bad_time = bad_time.values.astype(bool)

    else:
        n_invalid_each_time = invalid_da.values.astype(int)
        invalid_fraction_each_time = invalid_da.values.astype(float)
        bad_time = invalid_fraction_each_time >= invalid_fraction_threshold

    bad_indices = np.where(bad_time)[0]

    if len(bad_indices) > 0:
        # 連続する bad sample を block 化
        split_points = np.where(np.diff(bad_indices) > 1)[0]

        block_starts = np.r_[bad_indices[0], bad_indices[split_points + 1]]
        block_ends   = np.r_[bad_indices[split_points], bad_indices[-1]]

        for i0, i1 in zip(block_starts, block_ends):

            bad_start = times[i0]

            # bad interval の終端は最後の bad sample の次時刻とする
            if i1 < len(times) - 1:
                bad_interval_end = times[i1 + 1]
            else:
                if len(times) >= 2:
                    cadence = pd.Series(times[1:] - times[:-1]).median()
                else:
                    cadence = pd.Timedelta(0)

                bad_interval_end = times[i1] + cadence

            bad_duration = bad_interval_end - bad_start

            # 継続時間が足りなければ採用しない
            if bad_duration < min_bad_duration:
                continue

            # gap としては直前の good sample から直後の good sample まで
            if i0 > 0:
                gap_start = times[i0 - 1]
            else:
                gap_start = times[i0]

            if i1 < len(times) - 1:
                gap_end = times[i1 + 1]
            else:
                gap_end = bad_interval_end

            gap_dt = gap_end - gap_start

            invalid_frac_block = invalid_fraction_each_time[i0:i1 + 1]

            rows.append({
                "gap_start_time": gap_start,
                "gap_end_time": gap_end,
                "gap_duration_sec": gap_dt.total_seconds(),
                "gap_duration_min": gap_dt.total_seconds() / 60,
                "reason": "bad_omniflux_fraction",
                "bad_start_time": bad_start,
                "bad_end_time": times[i1],
                "bad_duration_sec": bad_duration.total_seconds(),
                "bad_duration_min": bad_duration.total_seconds() / 60,
                "n_bad_time_samples": int(i1 - i0 + 1),
                "n_invalid_values": int(n_invalid_each_time[i0:i1 + 1].sum()),
                "invalid_fraction_max": float(np.nanmax(invalid_frac_block)),
                "invalid_fraction_mean": float(np.nanmean(invalid_frac_block)),
            })

    gap_ranges_df = pd.DataFrame(rows, columns=columns)

    if len(gap_ranges_df) == 0:
        return gap_ranges_df

    gap_ranges_df = gap_ranges_df.sort_values(
        ["gap_start_time", "gap_end_time"]
    ).reset_index(drop=True)

    if merge_gap_ranges:
        gap_ranges_df = merge_omniflux_gap_ranges(
            gap_ranges_df,
            merge_gap_tolerance=merge_gap_tolerance,
        )

    return gap_ranges_df

In [13]:
LEPe_omniflux_gap_ranges_df = find_time_gaps_with_bad_omniflux(
    LEPe_FEDO_omniflux,
    threshold=pd.Timedelta(minutes=1),
    min_bad_duration=pd.Timedelta(minutes=1),
    invalid_fraction_threshold=0.20,
)

print(f"1分以上の time gap 数: {len(LEPe_omniflux_gap_ranges_df)}")
display(LEPe_omniflux_gap_ranges_df)

1分以上の time gap 数: 241

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,reason,bad_start_time,bad_end_time,bad_duration_sec,bad_duration_min,n_bad_time_samples,n_invalid_values,invalid_fraction_max,invalid_fraction_mean
0,2020-03-01 03:48:44.792683,2020-03-01 04:47:23.901570,3519.108887,58.651815,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
1,2020-03-01 08:02:35.160738,2020-03-01 08:03:55.146182,79.985444,1.333091,bad_omniflux_fraction,2020-03-01 08:02:51.145327,2020-03-01 08:03:39.145968,64.000855,1.066681,4,31,0.28125,0.242188
2,2020-03-01 08:07:39.149175,2020-03-01 08:09:15.134833,95.985658,1.599761,bad_omniflux_fraction,2020-03-01 08:07:55.149389,2020-03-01 08:08:59.134619,79.985444,1.333091,5,42,0.31250,0.262500
3,2020-03-01 08:36:59.094566,2020-03-01 08:39:23.096490,144.001924,2.400032,bad_omniflux_fraction,2020-03-01 08:37:15.094779,2020-03-01 08:39:07.096276,128.001711,2.133362,8,58,0.25000,0.226562
4,2020-03-01 09:20:43.035877,2020-03-01 09:23:55.022816,191.986939,3.199782,bad_omniflux_fraction,2020-03-01 09:20:59.036090,2020-03-01 09:23:39.022604,160.002138,2.666702,10,75,0.25000,0.234375
...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,2020-03-31 23:25:28.710263,2020-03-31 23:33:12.683563,463.973300,7.732888,bad_omniflux_fraction,2020-03-31 23:25:44.710420,2020-03-31 23:32:56.683406,431.972986,7.199550,27,234,0.37500,0.270833
237,2020-03-31 23:34:16.684191,2020-03-31 23:35:52.685133,96.000942,1.600016,bad_omniflux_fraction,2020-03-31 23:34:32.684348,2020-03-31 23:35:36.684976,80.000785,1.333346,5,39,0.28125,0.243750
238,2020-03-31 23:36:40.685603,2020-03-31 23:38:00.670762,79.985159,1.333086,bad_omniflux_fraction,2020-03-31 23:36:56.685760,2020-03-31 23:37:44.670605,63.985002,1.066417,4,32,0.28125,0.250000
239,2020-03-31 23:42:16.673274,2020-03-31 23:46:00.659858,223.986584,3.733110,bad_omniflux_fraction,2020-03-31 23:42:32.673431,2020-03-31 23:45:44.659696,207.986427,3.466440,13,121,0.37500,0.290865
240,2020-03-31 23:46:48.660346,2020-03-31 23:59:44.621380,775.961034,12.932684,bad_omniflux_fraction,2020-03-31 23:47:04.660509,2020-03-31 23:59:36.621274,743.976334,12.399606,47,449,0.40625,0.298537

In [14]:
LEPi_omniflux_gap_ranges_df = find_time_gaps_with_bad_omniflux(
    LEPi_FPDO_omniflux,
    threshold=pd.Timedelta(minutes=1),
    min_bad_duration=pd.Timedelta(minutes=1),
    invalid_fraction_threshold=0.20,
)

print(f"1分以上の time gap 数: {len(LEPi_omniflux_gap_ranges_df)}")
display(LEPi_omniflux_gap_ranges_df)

1分以上の time gap 数: 155

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,reason,bad_start_time,bad_end_time,bad_duration_sec,bad_duration_min,n_bad_time_samples,n_invalid_values,invalid_fraction_max,invalid_fraction_mean
0,2020-03-01 04:50:11.903000064,2020-03-01 04:51:15.904000000,64.000999,1.066683,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
1,2020-03-01 13:14:42.927000064,2020-03-01 14:09:53.580000000,3310.652999,55.177550,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
2,2020-03-01 17:23:52.710000128,2020-03-01 17:24:56.711000064,64.000999,1.066683,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
3,2020-03-01 22:42:48.220000000,2020-03-01 23:40:54.920000000,3486.700000,58.111667,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
4,2020-03-02 08:12:45.468000000,2020-03-02 09:05:56.105999872,3190.637999,53.177300,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,2020-03-31 03:20:26.628999936,2020-03-31 07:36:18.912999936,15352.284000,255.871400,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
151,2020-03-31 11:47:48.473999872,2020-03-31 12:40:49.761999872,3181.288000,53.021467,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
152,2020-03-31 12:47:13.751000064,2020-03-31 12:48:17.752000000,64.000999,1.066683,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
153,2020-03-31 21:15:31.564000000,2020-03-31 22:11:52.804999936,3381.240999,56.354017,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN
154,2020-03-31 22:18:16.809999872,2020-03-31 22:19:20.809999872,64.000000,1.066667,time_gap,NaT,NaT,NaN,NaN,0,0,NaN,NaN

# `erg_att_izras`と`erg_att_izdec`を取得

In [15]:
import re
import numpy as np
import pandas as pd
import pyspedas as psp
from pyspedas import time_float, store_data
from ergpyspedas.erg.satellite.erg.load import load as erg_load


def load_att_robust(
    trange,
    level="l2",
    no_update=False,
    uname=None,
    passwd=None,
):
    """
    ERG/Arase attitude txt を robust に読み込んで tplot 変数へ保存する。

    ergpyspedas 標準の att loader は空白 split に依存しているため、
    例: "26.2539-151515.3574" のように隣接数値間の空白が欠けた行で落ちる。
    ここでは timestamp 以降の数値を正規表現で抽出し、必要列だけを使う。
    元txtファイルは変更しない。
    """

    file_res = 24 * 3600.0
    pathformat = f"satellite/erg/att/txt/erg_att_{level}_%Y%m%d_v??.txt"

    out_files = erg_load(
        pathformat=pathformat,
        trange=trange,
        file_res=file_res,
        downloadonly=True,
        no_update=no_update,
        uname=uname,
        passwd=passwd,
    )

    if out_files is None or len(out_files) == 0:
        raise FileNotFoundError(f"No ERG attitude files found for trange={trange}")

    # timestamp 以外の数値を抽出する。隣接した負値も別トークンとして拾う。
    float_pattern = re.compile(
        r"[+-]?(?:\d+\.\d*|\.\d+|\d+)(?:[Ee][+-]?\d+)?"
    )

    rows = []
    skipped = []
    fixed_joined_numeric = 0

    for file in out_files:
        with open(file, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()

        # ergpyspedas 標準 loader と同じく先頭10行はヘッダ扱い。
        for line_no, line in enumerate(lines[10:], start=11):
            stripped = line.strip()
            if not stripped:
                continue

            parts = stripped.split(maxsplit=1)
            if len(parts) < 2:
                skipped.append((file, line_no, "no payload", stripped))
                continue

            tstr, payload = parts
            nums = [float(x) for x in float_pattern.findall(payload)]

            # 標準 loader が使う列に対応するには最低11個の数値が必要。
            # nums: 0 Omega, 1 I_alpha, 2 I_delta, ..., 6 Phase,
            #       7 GX_alpha, 8 GX_delta, 9 GZ_alpha, 10 GZ_delta
            if len(nums) < 11:
                skipped.append((file, line_no, f"too few numeric values: {len(nums)}", stripped))
                continue

            # 空白欠落の典型例を集計だけしておく。
            if re.search(r"\d\.\d+-\d", payload):
                fixed_joined_numeric += 1

            rows.append({
                "time": tstr,
                "Omega": nums[0],
                "I_Alpha": nums[1],
                "I_Delta": nums[2],
                "Phase": nums[6],
                "GX_Alpha": nums[7],
                "GX_Delta": nums[8],
                "GZ_Alpha": nums[9],
                "GZ_Delta": nums[10],
            })

    if len(rows) == 0:
        raise ValueError("No valid attitude rows parsed.")

    att_df = pd.DataFrame(rows)
    att_df = att_df.drop_duplicates(subset="time").sort_values("time").reset_index(drop=True)

    t = time_float(att_df["time"].tolist())

    store_data("erg_att_sprate", data={"x": t, "y": att_df["Omega"].to_numpy(float)})
    store_data("erg_att_spphase", data={"x": t, "y": att_df["Phase"].to_numpy(float)})
    store_data("erg_att_izras", data={"x": t, "y": att_df["I_Alpha"].to_numpy(float)})
    store_data("erg_att_izdec", data={"x": t, "y": att_df["I_Delta"].to_numpy(float)})
    store_data("erg_att_gxras", data={"x": t, "y": att_df["GX_Alpha"].to_numpy(float)})
    store_data("erg_att_gxdec", data={"x": t, "y": att_df["GX_Delta"].to_numpy(float)})
    store_data("erg_att_gzras", data={"x": t, "y": att_df["GZ_Alpha"].to_numpy(float)})
    store_data("erg_att_gzdec", data={"x": t, "y": att_df["GZ_Delta"].to_numpy(float)})

    print(f"loaded attitude files: {len(out_files)}")
    print(f"parsed attitude rows: {len(att_df)}")
    print(f"fixed joined numeric rows: {fixed_joined_numeric}")
    print(f"skipped rows: {len(skipped)}")
    if len(skipped) > 0:
        print("first skipped row:", skipped[0])

    return att_df


att_df = load_att_robust(time_range, no_update=False)

# dsi2j2000.py / erg_interpolate_att.py と同じ処理
psp.degap("erg_att_izras", dt=8.0, margin=0.5)
psp.degap("erg_att_izdec", dt=8.0, margin=0.5)

att_izras = psp.get_data("erg_att_izras", xarray=True)
att_izdec = psp.get_data("erg_att_izdec", xarray=True)

print(att_izras)
print(att_izdec)

29-Sep-26 17:47:48: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/att/txt/
29-Sep-26 17:47:55: Remote index took 6.8 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 17:48:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200301_v03.txt
29-Sep-26 17:48:07: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200302_v03.txt
29-Sep-26 17:48:12: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200303_v03.txt
29-Sep-26 17:48:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200304_v03.txt
29-Sep-26 17:48:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200305_v03.txt
29-Sep-26 17:48:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200306_v03.txt
29-Sep-26 17:48:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200307_v03.txt
29-Sep-26 17:48:34: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200308_v03.txt
29-Sep-26 17:48:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200309_v03.txt
29-Sep-26 17:48:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200310_v03.txt
29-Sep-26 17:49:08: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200311_v03.txt
29-Sep-26 17:49:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200312_v03.txt
29-Sep-26 17:49:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200313_v03.txt
29-Sep-26 17:49:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200314_v03.txt
29-Sep-26 17:49:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200315_v03.txt
29-Sep-26 17:49:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200316_v03.txt
29-Sep-26 17:49:46: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200317_v03.txt
29-Sep-26 17:49:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200318_v03.txt
29-Sep-26 17:49:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200319_v03.txt
29-Sep-26 17:50:09: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200320_v03.txt
29-Sep-26 17:50:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200321_v03.txt
29-Sep-26 17:50:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200322_v03.txt
29-Sep-26 17:50:33: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200323_v03.txt
29-Sep-26 17:50:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200324_v03.txt
29-Sep-26 17:50:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200325_v03.txt
29-Sep-26 17:51:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200326_v03.txt
29-Sep-26 17:51:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200327_v03.txt
29-Sep-26 17:51:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200328_v03.txt
29-Sep-26 17:51:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200329_v03.txt
29-Sep-26 17:51:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200330_v03.txt
29-Sep-26 17:51:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200331_v03.txt

loaded attitude files: 31
parsed attitude rows: 268708
fixed joined numeric rows: 0
skipped rows: 55954
first skipped row: ('/mnt/j/observation_data//ergsc/satellite/erg/att/txt/erg_att_l2_20200301_v03.txt', 11, 'too few numeric values: 0', '#   [date/time]            [rpm] [deg]   [deg]   [deg]    [deg]   [deg]   V/I     S/G     [deg]  [deg]    [deg]    [deg]    [deg]        [s]              [s]')
<xarray.DataArray 'erg_att_izras' (time: 334837)> Size: 3MB
array([ 165.4484,  165.4484,  165.4484, ..., -176.3681, -176.368 ,
       -176.3679], shape=(334837,))
Coordinates:
  * time     (time) datetime64[ns] 3MB 2020-03-01T00:00:05.018099968 ... 2020...
Attributes:
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...
<xarray.DataArray 'erg_att_izdec' (time: 334837)> Size: 3MB
array([16.7759, 16.7759, 16.7759, ..., -1.3701, -1.3701, -1.3701],
      shape=(334837,))
Coordinates:
  * time     (time) datetime64[ns] 3MB 2020-03-01T00:00:05.018099968 ... 2020...
Attributes:
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...

In [16]:
def merge_att_nan_intervals(
    att_nan_intervals_df,
    merge_gap_tolerance=pd.Timedelta(seconds=0),
):
    """
    gap_start_time/gap_end_time が重なる、接する、または
    merge_gap_tolerance 以下の短い good island を挟む attitude NaN 区間を merge する。
    """

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "bad_start_time",
        "bad_end_time",
        "bad_duration_sec",
        "bad_duration_min",
        "n_bad_time_samples",
        "n_nan_izras",
        "n_nan_izdec",
        "reason",
    ]

    if att_nan_intervals_df is None or len(att_nan_intervals_df) == 0:
        return pd.DataFrame(columns=columns)

    df = att_nan_intervals_df.copy()
    df["gap_start_time"] = pd.to_datetime(df["gap_start_time"])
    df["gap_end_time"] = pd.to_datetime(df["gap_end_time"])
    df = df.dropna(subset=["gap_start_time", "gap_end_time"])
    df = df[df["gap_end_time"] >= df["gap_start_time"]]
    df = df.sort_values(["gap_start_time", "gap_end_time"]).reset_index(drop=True)

    if len(df) == 0:
        return pd.DataFrame(columns=columns)

    merge_gap_tolerance = pd.Timedelta(merge_gap_tolerance)

    groups = []
    current = [0]
    current_end = df.loc[0, "gap_end_time"]

    for idx in range(1, len(df)):
        start = df.loc[idx, "gap_start_time"]
        end = df.loc[idx, "gap_end_time"]

        if start <= current_end + merge_gap_tolerance:
            current.append(idx)
            if end > current_end:
                current_end = end
        else:
            groups.append(current)
            current = [idx]
            current_end = end

    groups.append(current)

    merged_rows = []

    for group in groups:
        g = df.loc[group]
        gap_start = g["gap_start_time"].min()
        gap_end = g["gap_end_time"].max()
        gap_duration = gap_end - gap_start

        reasons = []
        for reason in g["reason"].dropna().astype(str):
            for part in reason.split("+"):
                if part not in reasons:
                    reasons.append(part)

        bad_starts = pd.to_datetime(g["bad_start_time"], errors="coerce").dropna()
        bad_ends = pd.to_datetime(g["bad_end_time"], errors="coerce").dropna()
        bad_duration = pd.to_numeric(g["bad_duration_sec"], errors="coerce").sum(min_count=1)

        n_bad = pd.to_numeric(g["n_bad_time_samples"], errors="coerce").fillna(0)
        n_nan_izras = pd.to_numeric(g["n_nan_izras"], errors="coerce").fillna(0)
        n_nan_izdec = pd.to_numeric(g["n_nan_izdec"], errors="coerce").fillna(0)

        merged_rows.append({
            "gap_start_time": gap_start,
            "gap_end_time": gap_end,
            "gap_duration_sec": gap_duration.total_seconds(),
            "gap_duration_min": gap_duration.total_seconds() / 60,
            "bad_start_time": bad_starts.min() if len(bad_starts) > 0 else pd.NaT,
            "bad_end_time": bad_ends.max() if len(bad_ends) > 0 else pd.NaT,
            "bad_duration_sec": float(bad_duration) if pd.notna(bad_duration) else np.nan,
            "bad_duration_min": float(bad_duration) / 60 if pd.notna(bad_duration) else np.nan,
            "n_bad_time_samples": int(n_bad.sum()),
            "n_nan_izras": int(n_nan_izras.sum()),
            "n_nan_izdec": int(n_nan_izdec.sum()),
            "reason": "+".join(reasons),
        })

    return pd.DataFrame(merged_rows, columns=columns).reset_index(drop=True)


def find_nan_intervals_att(
    att_izras,
    att_izdec,
    time_dim="time",
    merge_gap_ranges=True,
    merge_gap_tolerance=pd.Timedelta(seconds=0),
):
    """
    erg_att_izras / erg_att_izdec のどちらかが NaN になる連続区間を抽出する。
    gap_start_time / gap_end_time は、NaN block を挟む直前・直後の正常 grid。

    merge_gap_ranges=True の場合、重なる/接する gap 行を merge する。
    merge_gap_tolerance を指定すると、その時間以下の短い good island もまとめる。
    """

    izras = att_izras.sortby(time_dim)
    izdec = att_izdec.sortby(time_dim)

    times = pd.DatetimeIndex(pd.to_datetime(izras[time_dim].values))

    ras = np.asarray(izras.values)
    dec = np.asarray(izdec.values)

    bad = np.isnan(ras) | np.isnan(dec)
    bad_indices = np.where(bad)[0]

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "bad_start_time",
        "bad_end_time",
        "bad_duration_sec",
        "bad_duration_min",
        "n_bad_time_samples",
        "n_nan_izras",
        "n_nan_izdec",
        "reason",
    ]

    if len(bad_indices) == 0:
        return pd.DataFrame(columns=columns)

    rows = []

    split_points = np.where(np.diff(bad_indices) > 1)[0]
    block_starts = np.r_[bad_indices[0], bad_indices[split_points + 1]]
    block_ends = np.r_[bad_indices[split_points], bad_indices[-1]]

    cadence = pd.Series(times[1:] - times[:-1]).median() if len(times) >= 2 else pd.Timedelta(0)

    for i0, i1 in zip(block_starts, block_ends):
        bad_start = times[i0]

        if i1 < len(times) - 1:
            bad_interval_end = times[i1 + 1]
        else:
            bad_interval_end = times[i1] + cadence

        bad_duration = bad_interval_end - bad_start

        # NaN block を挟む正常 grid の間を gap とする
        gap_start = times[i0 - 1] if i0 > 0 else times[i0]
        gap_end = times[i1 + 1] if i1 < len(times) - 1 else bad_interval_end
        gap_duration = gap_end - gap_start

        rows.append({
            "gap_start_time": gap_start,
            "gap_end_time": gap_end,
            "gap_duration_sec": gap_duration.total_seconds(),
            "gap_duration_min": gap_duration.total_seconds() / 60,
            "bad_start_time": bad_start,
            "bad_end_time": times[i1],
            "bad_duration_sec": bad_duration.total_seconds(),
            "bad_duration_min": bad_duration.total_seconds() / 60,
            "n_bad_time_samples": int(i1 - i0 + 1),
            "n_nan_izras": int(np.isnan(ras[i0:i1 + 1]).sum()),
            "n_nan_izdec": int(np.isnan(dec[i0:i1 + 1]).sum()),
            "reason": "att_izras_or_izdec_nan",
        })

    att_nan_intervals_df = pd.DataFrame(rows, columns=columns)

    if merge_gap_ranges:
        att_nan_intervals_df = merge_att_nan_intervals(
            att_nan_intervals_df,
            merge_gap_tolerance=merge_gap_tolerance,
        )

    return att_nan_intervals_df

In [17]:
att_nan_intervals_df = find_nan_intervals_att(att_izras, att_izdec)

print(f"time gap 数: {len(att_nan_intervals_df)}")
display(att_nan_intervals_df)

time gap 数: 96

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,bad_start_time,bad_end_time,bad_duration_sec,bad_duration_min,n_bad_time_samples,n_nan_izras,n_nan_izdec,reason
0,2020-03-01 03:20:28.886200064,2020-03-01 03:55:07.994999808,2079.108799,34.651813,2020-03-01 03:20:36.886200064,2020-03-01 03:55:00.886200064,2071.108799,34.518480,259,259,259,att_izras_or_izdec_nan
1,2020-03-01 12:47:06.813600000,2020-03-01 13:22:49.752999936,2142.939399,35.715657,2020-03-01 12:47:14.813600000,2020-03-01 13:22:42.813600000,2134.939399,35.582323,267,267,267,att_izras_or_izdec_nan
2,2020-03-01 17:30:56.698499840,2020-03-02 00:28:22.715800064,25046.017300,417.433622,2020-03-01 17:31:04.698499840,2020-03-02 00:28:16.698499840,25038.017300,417.300288,3130,3130,3130,att_izras_or_izdec_nan
3,2020-03-02 00:29:50.707299840,2020-03-02 23:10:00.444199936,81609.736900,1360.162282,2020-03-02 00:29:58.707299840,2020-03-02 23:09:58.707299840,81601.736900,1360.028948,10201,10201,10201,att_izras_or_izdec_nan
4,2020-03-03 02:33:28.342600192,2020-03-03 03:13:18.835400192,2390.492800,39.841547,2020-03-03 02:33:36.342600192,2020-03-03 03:13:12.342600192,2382.492800,39.708213,298,298,298,att_izras_or_izdec_nan
...,...,...,...,...,...,...,...,...,...,...,...,...
91,2020-03-30 16:21:18.092999936,2020-03-30 17:12:11.748000000,3053.655000,50.894250,2020-03-30 16:21:26.092999936,2020-03-30 17:12:06.092999936,3045.655000,50.760917,381,381,381,att_izras_or_izdec_nan
92,2020-03-31 01:49:01.088200192,2020-03-31 02:39:30.744800000,3029.656599,50.494277,2020-03-31 01:49:09.088200192,2020-03-31 02:39:25.088200192,3021.656599,50.360943,378,378,378,att_izras_or_izdec_nan
93,2020-03-31 11:16:36.115600128,2020-03-31 12:06:49.817600000,3013.701999,50.228367,2020-03-31 11:16:44.115600128,2020-03-31 12:06:44.115600128,3005.701999,50.095033,376,376,376,att_izras_or_izdec_nan
94,2020-03-31 16:00:09.712499968,2020-03-31 16:00:57.713700096,48.001200,0.800020,2020-03-31 16:00:17.712499968,2020-03-31 16:00:57.712499968,40.001200,0.666687,6,6,6,att_izras_or_izdec_nan
95,2020-03-31 20:44:19.208499968,2020-03-31 23:40:00.678999808,10541.470499,175.691175,2020-03-31 20:44:27.208499968,2020-03-31 23:39:55.208499968,10533.470499,175.557842,1317,1317,1317,att_izras_or_izdec_nan

# PWE-HFA L3（1分値）のデータ存在時間・品質の確認

In [19]:
load_erg_with_retry(
    ergpy.pwe_hfa,
    description="PWE-HFA L3 load",
    expected_tplot_vars=(
        "erg_pwe_hfa_l3_1min_ne_mgf",
        "erg_pwe_hfa_l3_1min_quality_flag",
    ),
    trange=time_range,
    level="l3",
    no_update=True,
)

HFA_L3_ne_mgf = psp.get_data(
    "erg_pwe_hfa_l3_1min_ne_mgf",
    xarray=True,
)
HFA_L3_quality_flag = psp.get_data(
    "erg_pwe_hfa_l3_1min_quality_flag",
    xarray=True,
)

if HFA_L3_ne_mgf is None or HFA_L3_quality_flag is None:
    raise KeyError(
        "HFA L3 tplot variables not found: "
        "erg_pwe_hfa_l3_1min_ne_mgf and/or "
        "erg_pwe_hfa_l3_1min_quality_flag"
    )

HFA_L3_ne_mgf = HFA_L3_ne_mgf.sortby("time")
HFA_L3_quality_flag = HFA_L3_quality_flag.sortby("time")

print(HFA_L3_ne_mgf)
print(HFA_L3_quality_flag)

29-Sep-26 18:05:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/
29-Sep-26 18:05:31: Remote index took 10.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:05:34: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200301_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200301_v06_11.cdf
29-Sep-26 18:05:35: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200301_v06_11.cdf complete, 0.025 MB in 1.1 sec (0.022 MB/sec) (transfer_normal)
29-Sep-26 18:05:37: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200302_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200302_v06_11.cdf
29-Sep-26 18:05:37: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200302_v06_11.cdf complete, 0.025 MB in 1.1 sec (0.023 MB/sec) (transfer_normal)
29-Sep-26 18:05:42: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200303_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200303_v06_11.cdf
29-Sep-26 18:05:43: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200303_v06_11.cdf complete, 0.025 MB in 4.5 sec (0.006 MB/sec) (transfer_slow)
29-Sep-26 18:05:59: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200304_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200304_v06_11.cdf
29-Sep-26 18:05:59: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200304_v06_11.cdf complete, 0.025 MB in 15.4 sec (0.002 MB/sec) (transfer_slow)
29-Sep-26 18:06:04: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200305_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200305_v06_11.cdf
29-Sep-26 18:06:04: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200305_v06_11.cdf complete, 0.025 MB in 3.4 sec (0.007 MB/sec) (transfer_slow)
29-Sep-26 18:06:09: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200306_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200306_v06_11.cdf
29-Sep-26 18:06:09: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200306_v06_11.cdf complete, 0.020 MB in 3.6 sec (0.006 MB/sec) (transfer_slow)
29-Sep-26 18:06:13: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200307_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200307_v06_11.cdf
29-Sep-26 18:06:13: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200307_v06_11.cdf complete, 0.025 MB in 2.7 sec (0.009 MB/sec) (transfer_slow)
29-Sep-26 18:06:25: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200308_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200308_v06_11.cdf
29-Sep-26 18:06:26: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200308_v06_11.cdf complete, 0.025 MB in 10.8 sec (0.002 MB/sec) (transfer_slow)
29-Sep-26 18:06:45: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200309_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200309_v06_11.cdf
29-Sep-26 18:06:45: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200309_v06_11.cdf complete, 0.025 MB in 18.4 sec (0.001 MB/sec) (transfer_slow)
29-Sep-26 18:06:53: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200310_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200310_v06_11.cdf
29-Sep-26 18:06:53: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200310_v06_11.cdf complete, 0.025 MB in 6.2 sec (0.004 MB/sec) (transfer_slow)
29-Sep-26 18:07:03: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200311_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200311_v06_11.cdf
29-Sep-26 18:07:04: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200311_v06_11.cdf complete, 0.025 MB in 9.5 sec (0.003 MB/sec) (transfer_slow)
29-Sep-26 18:07:14: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200312_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200312_v06_11.cdf
29-Sep-26 18:07:14: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200312_v06_11.cdf complete, 0.025 MB in 8.9 sec (0.003 MB/sec) (transfer_slow)
29-Sep-26 18:07:24: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200313_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200313_v06_11.cdf
29-Sep-26 18:07:25: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200313_v06_11.cdf complete, 0.025 MB in 9.2 sec (0.003 MB/sec) (transfer_slow)
29-Sep-26 18:07:30: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200314_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200314_v06_11.cdf
29-Sep-26 18:07:30: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200314_v06_11.cdf complete, 0.025 MB in 4.3 sec (0.006 MB/sec) (transfer_slow)
29-Sep-26 18:07:47: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200315_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200315_v06_11.cdf
29-Sep-26 18:07:48: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200315_v06_11.cdf complete, 0.025 MB in 16.0 sec (0.002 MB/sec) (transfer_slow)
29-Sep-26 18:07:50: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200316_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200316_v06_11.cdf
29-Sep-26 18:07:50: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200316_v06_11.cdf complete, 0.024 MB in 1.0 sec (0.026 MB/sec) (transfer_normal)
29-Sep-26 18:07:56: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200317_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200317_v06_11.cdf
29-Sep-26 18:07:56: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200317_v06_11.cdf complete, 0.025 MB in 5.2 sec (0.005 MB/sec) (transfer_slow)
29-Sep-26 18:08:18: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200318_v06_11.cdf
29-Sep-26 18:08:24: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200318_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200318_v06_11.cdf
29-Sep-26 18:08:24: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200318_v06_11.cdf complete, 0.025 MB in 26.4 sec (0.001 MB/sec) (transfer_slow)
29-Sep-26 18:08:32: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200319_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200319_v06_11.cdf
29-Sep-26 18:08:32: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200319_v06_11.cdf complete, 0.025 MB in 6.5 sec (0.004 MB/sec) (transfer_slow)
29-Sep-26 18:08:35: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200320_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200320_v06_11.cdf
29-Sep-26 18:08:35: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200320_v06_11.cdf complete, 0.025 MB in 1.8 sec (0.014 MB/sec) (transfer_normal)
29-Sep-26 18:08:36: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200321_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200321_v06_11.cdf
29-Sep-26 18:08:36: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200321_v06_11.cdf complete, 0.023 MB in 0.0 sec (0.492 MB/sec) (transfer_normal)
29-Sep-26 18:08:37: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200322_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200322_v06_11.cdf
29-Sep-26 18:08:38: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200322_v06_11.cdf complete, 0.025 MB in 0.0 sec (0.513 MB/sec) (transfer_normal)
29-Sep-26 18:08:39: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200323_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200323_v06_11.cdf
29-Sep-26 18:08:39: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200323_v06_11.cdf complete, 0.024 MB in 0.1 sec (0.447 MB/sec) (transfer_normal)
29-Sep-26 18:08:41: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200324_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200324_v06_11.cdf
29-Sep-26 18:08:42: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200324_v06_11.cdf complete, 0.025 MB in 1.3 sec (0.019 MB/sec) (transfer_normal)
29-Sep-26 18:08:44: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200325_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200325_v06_11.cdf
29-Sep-26 18:08:44: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200325_v06_11.cdf complete, 0.024 MB in 1.1 sec (0.023 MB/sec) (transfer_normal)
29-Sep-26 18:08:45: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200326_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200326_v06_11.cdf
29-Sep-26 18:08:45: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200326_v06_11.cdf complete, 0.025 MB in 0.0 sec (0.506 MB/sec) (transfer_normal)
29-Sep-26 18:08:46: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200327_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200327_v06_11.cdf
29-Sep-26 18:08:47: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200327_v06_11.cdf complete, 0.025 MB in 0.0 sec (0.509 MB/sec) (transfer_normal)
29-Sep-26 18:08:49: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200328_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200328_v06_11.cdf
29-Sep-26 18:08:49: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200328_v06_11.cdf complete, 0.025 MB in 0.8 sec (0.030 MB/sec) (transfer_normal)
29-Sep-26 18:08:50: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200329_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200329_v06_11.cdf
29-Sep-26 18:08:51: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200329_v06_11.cdf complete, 0.025 MB in 0.6 sec (0.044 MB/sec) (transfer_normal)
29-Sep-26 18:08:53: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200330_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200330_v06_11.cdf
29-Sep-26 18:08:53: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200330_v06_11.cdf complete, 0.025 MB in 1.1 sec (0.024 MB/sec) (transfer_normal)
29-Sep-26 18:08:54: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200331_v06_11.cdf to /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200331_v06_11.cdf
29-Sep-26 18:08:55: Download of /mnt/j/observation_data//ergsc/satellite/erg/pwe/hfa/l3/2020/03/erg_pwe_hfa_l3_1min_20200331_v06_11.cdf complete, 0.025 MB in 0.2 sec (0.139 MB/sec) (transfer_normal)
29-Sep-26 18:08:55: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:08:55: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Plasma Wave Experiment (PWE) High Frequency Analyzer (HFA) Level 3 UHR frequency and electron density data']

Information about ERG PWE HFA

PI:  ['Yoshiya Kasahara and Ayako Matsuoka']
Affiliation:  ['Kanazawa University and Kyoto University']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of PWE/HFA: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Pwe/Hfa

Contact: erg_pwe_info at isee.nagoya-u.ac.jp
**************************************************************************
<xarray.DataArray 'erg_pwe_hfa_l3_1min_ne_mgf' (time: 43983)> Size: 176kB
array([ 0.28735897,  0.28567612,  0.29573172, ..., 17.979342  ,
       18.000526  , 18.019323  ], shape=(43983,), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 352kB 2020-03-01T00:00:29.998791218 ... 20...
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'density_mgf', 'CATDESC': 'density_m...
    data_att:      {'coord_sys': '', 'units': '/cc', 'depend_1_units': '/cc',...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...
<xarray.DataArray 'erg_pwe_hfa_l3_1min_quality_flag' (time: 43983)> Size: 176kB
array([4, 4, 4, ..., 0, 0, 0], shape=(43983,), dtype=uint32)
Coordinates:
  * time     (time) datetime64[ns] 352kB 2020-03-01T00:00:29.998791218 ... 20...
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'quality flag', 'CATDESC': 'quality ...
    data_att:      {'coord_sys': '', 'units': 'None', 'depend_1_units': None,...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...

In [20]:
def find_hfa_invalid_ranges(
    ne_mgf_da,
    quality_flag_da,
    threshold=pd.Timedelta(minutes=5),
    nominal_cadence=pd.Timedelta(minutes=1),
):
    """HFA L3のtime gap、quality flag不良、ne_mgf非有限値を抽出する。"""

    ne_mgf, quality_flag = xr.align(
        ne_mgf_da.sortby("time"),
        quality_flag_da.sortby("time"),
        join="outer",
    )
    times = pd.DatetimeIndex(pd.to_datetime(ne_mgf.time.values))

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "reason",
        "bad_start_time",
        "bad_end_time",
        "bad_duration_sec",
        "bad_duration_min",
        "n_bad_time_samples",
        "n_invalid_values",
        "invalid_fraction_max",
        "invalid_fraction_mean",
    ]

    if len(times) == 0:
        return pd.DataFrame(columns=columns)

    rows = []

    if len(times) >= 2:
        dt = times[1:] - times[:-1]
        for i in np.where(dt >= threshold)[0]:
            duration_sec = dt[i].total_seconds()
            rows.append({
                "gap_start_time": times[i],
                "gap_end_time": times[i + 1],
                "gap_duration_sec": duration_sec,
                "gap_duration_min": duration_sec / 60,
                "reason": "hfa_l3_time_gap",
                "bad_start_time": pd.NaT,
                "bad_end_time": pd.NaT,
                "bad_duration_sec": np.nan,
                "bad_duration_min": np.nan,
                "n_bad_time_samples": 0,
                "n_invalid_values": 0,
                "invalid_fraction_max": np.nan,
                "invalid_fraction_mean": np.nan,
            })

    def reduce_invalid_to_time(invalid_da):
        reduce_dims = [dim for dim in invalid_da.dims if dim != "time"]
        if reduce_dims:
            invalid_da = invalid_da.any(dim=reduce_dims)
        return np.asarray(invalid_da.values, dtype=bool)

    bad_ne = reduce_invalid_to_time(~np.isfinite(ne_mgf))
    bad_qf = reduce_invalid_to_time(
        (~np.isfinite(quality_flag)) | (quality_flag >= 1)
    )
    bad = bad_ne | bad_qf
    bad_indices = np.where(bad)[0]

    if len(bad_indices) > 0:
        split_mask = np.diff(bad_indices) > 1
        if len(bad_indices) >= 2:
            bad_dt = times[bad_indices[1:]] - times[bad_indices[:-1]]
            split_mask |= bad_dt > 1.5 * nominal_cadence

        split_points = np.where(split_mask)[0]
        block_starts = np.r_[bad_indices[0], bad_indices[split_points + 1]]
        block_ends = np.r_[bad_indices[split_points], bad_indices[-1]]

        for i0, i1 in zip(block_starts, block_ends):
            gap_start = times[i0 - 1] if i0 > 0 else times[i0]
            gap_end = times[i1 + 1] if i1 < len(times) - 1 else times[i1] + nominal_cadence
            bad_end_exclusive = times[i1] + nominal_cadence
            gap_duration = gap_end - gap_start
            bad_duration = bad_end_exclusive - times[i0]

            reasons = []
            if bad_qf[i0:i1 + 1].any():
                reasons.append("hfa_l3_quality_flag")
            if bad_ne[i0:i1 + 1].any():
                reasons.append("hfa_l3_ne_mgf_nonfinite")

            rows.append({
                "gap_start_time": gap_start,
                "gap_end_time": gap_end,
                "gap_duration_sec": gap_duration.total_seconds(),
                "gap_duration_min": gap_duration.total_seconds() / 60,
                "reason": "+".join(reasons),
                "bad_start_time": times[i0],
                "bad_end_time": times[i1],
                "bad_duration_sec": bad_duration.total_seconds(),
                "bad_duration_min": bad_duration.total_seconds() / 60,
                "n_bad_time_samples": int(i1 - i0 + 1),
                "n_invalid_values": int(
                    bad_qf[i0:i1 + 1].sum() + bad_ne[i0:i1 + 1].sum()
                ),
                "invalid_fraction_max": np.nan,
                "invalid_fraction_mean": np.nan,
            })

    ranges_df = pd.DataFrame(rows, columns=columns)
    if len(ranges_df) == 0:
        return ranges_df

    return merge_omniflux_gap_ranges(ranges_df)


HFA_L3_gap_ranges_df = find_hfa_invalid_ranges(
    HFA_L3_ne_mgf,
    HFA_L3_quality_flag,
    threshold=pd.Timedelta(minutes=5),
    nominal_cadence=pd.Timedelta(minutes=1),
)

print(f"HFA L3のtime gap・quality・ne_mgf不良区間数: {len(HFA_L3_gap_ranges_df)}")
display(HFA_L3_gap_ranges_df)

HFA L3のtime gap・quality・ne_mgf不良区間数: 223

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,reason,bad_start_time,bad_end_time,bad_duration_sec,bad_duration_min,n_bad_time_samples,n_invalid_values,invalid_fraction_max,invalid_fraction_mean
0,2020-03-01 00:00:29.998791218,2020-03-01 00:07:30.000013351,420.001222,7.000020,hfa_l3_quality_flag,2020-03-01 00:00:29.998791218,2020-03-01 00:06:29.998810053,420.000018,7.000000,7,7,NaN,NaN
1,2020-03-01 03:26:30.001514434,2020-03-01 03:48:29.998538970,1319.997024,21.999950,hfa_l3_quality_flag,2020-03-01 03:27:29.998855591,2020-03-01 03:47:30.001157761,1260.002302,21.000038,21,21,NaN,NaN
2,2020-03-01 03:54:29.999040604,2020-03-01 04:45:29.999542236,3060.000501,51.000008,hfa_l3_quality_flag,2020-03-01 03:55:29.999841689,2020-03-01 04:44:30.000471114,3000.000629,50.000010,50,50,NaN,NaN
3,2020-03-01 07:59:30.000457764,2020-03-01 08:08:29.999097824,539.998640,8.999977,hfa_l3_quality_flag,2020-03-01 08:00:29.999568939,2020-03-01 08:07:30.000026702,480.000457,8.000008,8,8,NaN,NaN
4,2020-03-01 11:59:30.000484466,2020-03-01 12:08:29.999084473,539.998600,8.999977,hfa_l3_quality_flag,2020-03-01 12:00:29.999555587,2020-03-01 12:07:30.000013351,480.000457,8.000008,8,8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,2020-03-31 01:47:30.001144409,2020-03-31 03:19:30.000171661,5519.999027,91.999984,hfa_l3_quality_flag,2020-03-31 01:48:29.998968123,2020-03-31 03:18:29.998525620,5459.999557,90.999993,91,91,NaN,NaN
219,2020-03-31 03:59:30.001316070,2020-03-31 04:08:30.000801086,539.999485,8.999991,hfa_l3_quality_flag,2020-03-31 04:00:29.999542236,2020-03-31 04:07:30.000000000,480.000457,8.000008,8,8,NaN,NaN
220,2020-03-31 07:59:30.000457764,2020-03-31 08:08:29.999097824,539.998640,8.999977,hfa_l3_quality_flag,2020-03-31 08:00:29.999568939,2020-03-31 08:07:30.000026702,480.000457,8.000008,8,8,NaN,NaN
221,2020-03-31 11:15:29.999555587,2020-03-31 12:08:29.999084473,3179.999528,52.999992,hfa_l3_quality_flag,2020-03-31 11:16:29.998626708,2020-03-31 12:07:30.000013351,3120.001386,52.000023,52,52,NaN,NaN
222,2020-03-31 20:43:30.001386641,2020-03-31 21:33:29.996822357,2999.995435,49.999924,hfa_l3_quality_flag,2020-03-31 20:44:30.000457764,2020-03-31 21:32:29.997711182,2939.997253,48.999954,49,49,NaN,NaN

# 第一段階検証 Especについて

In [21]:
import numpy as np
import pandas as pd

# ============================================================
# gap range を time mask に変換する関数
# ============================================================

EVENT_HALF_WIDTH = pd.Timedelta(seconds=200)
MIN_EVENT_DURATION = pd.Timedelta(seconds=400)
MAX_ANALYSIS_DURATION = pd.Timedelta(seconds=1200)
BACKGROUND_CONTEXT_PAD = pd.Timedelta(seconds=60)
RANGE_BOUNDARY_EPSILON = pd.Timedelta(microseconds=1)

def make_not_in_gap_mask(times, gap_ranges_df_list):
    """
    times が、複数の gap_ranges_df のどの時間範囲にも含まれない mask を返す。

    gap_ranges_df は以下のどちらかの列を持つ想定:
      - missing_start_time, missing_end_time
      - gap_start_time, gap_end_time
    """

    times_pd = pd.DatetimeIndex(pd.to_datetime(times))

    in_gap = np.zeros(len(times_pd), dtype=bool)

    for gap_df in gap_ranges_df_list:
        if gap_df is None or len(gap_df) == 0:
            continue

        if {"missing_start_time", "missing_end_time"}.issubset(gap_df.columns):
            start_col = "missing_start_time"
            end_col   = "missing_end_time"
        elif {"gap_start_time", "gap_end_time"}.issubset(gap_df.columns):
            start_col = "gap_start_time"
            end_col   = "gap_end_time"
        else:
            raise ValueError(
                "gap_ranges_df must have either "
                "['missing_start_time', 'missing_end_time'] or "
                "['gap_start_time', 'gap_end_time'] columns."
            )

        for _, row in gap_df.iterrows():
            start = pd.to_datetime(row[start_col])
            end   = pd.to_datetime(row[end_col])

            if pd.isna(start) or pd.isna(end):
                continue

            in_gap |= (times_pd >= start) & (times_pd <= end)

    not_in_gap = ~in_gap

    return not_in_gap

In [22]:
# spec_bins = 3..32 の範囲で、各 time ごとに 60% 以上のデータが 1e-4 を超える time を抽出
subset = efd_spectra_qf.sel(spec_bins=slice(3, 32))

valid = subset.notnull()
above = valid & (subset > 1e-4)

frac_above = above.sum(dim="v_dim") / valid.sum(dim="v_dim")
mask = frac_above >= 0.6

# ============================================================
# 3点以上連続している区間を丸ごと残す
# ============================================================

mask_np = mask.values.astype(bool)

kernel = np.ones(3, dtype=int)
count3 = np.convolve(mask_np.astype(int), kernel, mode="valid")
window3 = count3 == 3

mask_consecutive_3_np = np.zeros_like(mask_np, dtype=bool)

for i, ok in enumerate(window3):
    if ok:
        mask_consecutive_3_np[i:i+3] = True

# ============================================================
# LEPe / LEPi / HFA L3 / ATT gap 範囲に含まれない条件を追加
# ============================================================

not_in_data_gap_mask = make_not_in_gap_mask(
    frac_above.time.values,
    [
        LEPe_omniflux_gap_ranges_df,
        LEPi_omniflux_gap_ranges_df,
        HFA_L3_gap_ranges_df,
        att_nan_intervals_df,
    ],
)

# 最終 mask
final_mask_np = mask_consecutive_3_np & not_in_data_gap_mask

selected_times = frac_above.time.values[final_mask_np]
selected_fracs = frac_above.values[final_mask_np]

print(f"3点以上連続条件を満たす time の数: {mask_consecutive_3_np.sum()}")
print(f"LEPe/LEPi/HFA L3/ATT gap 除外後の time の数: {len(selected_times)}")

3点以上連続条件を満たす time の数: 126363
LEPe/LEPi/HFA L3/ATT gap 除外後の time の数: 100831

In [23]:
import numpy as np
import pandas as pd


def gap_df_to_intervals_fast(gap_df):
    """
    各観測データのgap DataFrameをinterval DataFrameに変換する。
    """

    if gap_df is None or len(gap_df) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    if {"missing_start_time", "missing_end_time"}.issubset(gap_df.columns):
        start_col = "missing_start_time"
        end_col = "missing_end_time"
    elif {"gap_start_time", "gap_end_time"}.issubset(gap_df.columns):
        start_col = "gap_start_time"
        end_col = "gap_end_time"
    else:
        raise ValueError(
            "gap_df must have either "
            "['missing_start_time', 'missing_end_time'] or "
            "['gap_start_time', 'gap_end_time'] columns."
        )

    out = pd.DataFrame({
        "start_time": pd.to_datetime(gap_df[start_col]),
        "end_time": pd.to_datetime(gap_df[end_col]),
    })

    out = out.dropna()
    out = out[out["end_time"] >= out["start_time"]]

    return out.reset_index(drop=True)


def merge_intervals_fast(intervals_df):
    """
    start_time, end_time を持つ interval DataFrame を高速に merge する。
    """

    if intervals_df is None or len(intervals_df) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    df = intervals_df.dropna().copy()
    df = df.sort_values("start_time").reset_index(drop=True)

    starts = pd.DatetimeIndex(df["start_time"]).to_numpy()
    ends = pd.DatetimeIndex(df["end_time"]).to_numpy()

    order = np.argsort(starts)
    starts = starts[order]
    ends = ends[order]

    # ここは datetime64[ns] のまま np.maximum.accumulate できる
    cum_ends = np.maximum.accumulate(ends)

    # 新しい interval が始まる条件
    # start > 直前までの cumulative end
    new_group = np.empty(len(starts), dtype=bool)
    new_group[0] = True
    new_group[1:] = starts[1:] > cum_ends[:-1]

    group_id = np.cumsum(new_group) - 1

    merged_starts = []
    merged_ends = []

    for gid in np.unique(group_id):
        use = group_id == gid
        merged_starts.append(starts[use][0])
        merged_ends.append(ends[use].max())

    return pd.DataFrame({
        "start_time": pd.to_datetime(merged_starts),
        "end_time": pd.to_datetime(merged_ends),
    })


def make_forbidden_intervals_fast(
    bad_times=None,
    LEPe_gap_ranges_df=None,
    LEPi_gap_ranges_df=None,
    HFA_gap_ranges_df=None,
    att_gap_ranges_df=None,
):
    """
    bad_times, LEPe gap, LEPi gap, HFA L3 gap, ATT gap をまとめて禁止 interval にする。

    bad_times は point-like interval [t, t] として扱う。
    """

    dfs = []

    if bad_times is not None:
        bad_times_pd = pd.DatetimeIndex(pd.to_datetime(bad_times.values))
        bad_times_pd = bad_times_pd.dropna().sort_values().unique()
        bad_times_pd = pd.DatetimeIndex(bad_times_pd)

        if len(bad_times_pd) > 0:
            dfs.append(pd.DataFrame({
                "start_time": bad_times_pd,
                "end_time": bad_times_pd,
            }))

    df_lepe = gap_df_to_intervals_fast(LEPe_gap_ranges_df)
    df_lepi = gap_df_to_intervals_fast(LEPi_gap_ranges_df)
    df_hfa  = gap_df_to_intervals_fast(HFA_gap_ranges_df)
    df_att  = gap_df_to_intervals_fast(att_gap_ranges_df)

    if len(df_lepe) > 0:
        dfs.append(df_lepe)

    if len(df_lepi) > 0:
        dfs.append(df_lepi)

    if len(df_hfa) > 0:
        dfs.append(df_hfa)

    if len(df_att) > 0:
        dfs.append(df_att)

    if len(dfs) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    intervals_df = pd.concat(dfs, ignore_index=True)
    intervals_df = merge_intervals_fast(intervals_df)

    return intervals_df

In [24]:
def make_trimmed_time_ranges_fast(
    selected_times,
    forbidden_intervals_df,
    half_width=EVENT_HALF_WIDTH,
    eps=pd.Timedelta(nanoseconds=1),
):
    """
    selected_times ± half_width の区間を作る。
    ただし forbidden intervals を含まないように、
    各 selected_time の前後で最も近い forbidden interval まで切り詰める。

    Returns
    -------
    time_ranges : list[tuple[pd.Timestamp, pd.Timestamp]]
    """

    selected_times_pd = pd.DatetimeIndex(
        pd.to_datetime(selected_times)
    ).sort_values()

    if len(selected_times_pd) == 0:
        return []

    start0 = selected_times_pd - half_width
    end0 = selected_times_pd + half_width

    if forbidden_intervals_df is None or len(forbidden_intervals_df) == 0:
        return list(zip(start0, end0))

    forbidden_intervals_df = forbidden_intervals_df.sort_values("start_time").reset_index(drop=True)

    f_starts = pd.DatetimeIndex(pd.to_datetime(forbidden_intervals_df["start_time"]))
    f_ends = pd.DatetimeIndex(pd.to_datetime(forbidden_intervals_df["end_time"]))

    # numpy datetime64[ns] として扱う
    t_np = selected_times_pd.to_numpy()
    start_np = start0.to_numpy()
    end_np = end0.to_numpy()

    f_starts_np = f_starts.to_numpy()
    f_ends_np = f_ends.to_numpy()

    # 各 t に対して、t 以下で始まる最後の forbidden interval
    i_prev = np.searchsorted(f_starts_np, t_np, side="right") - 1

    valid_prev = i_prev >= 0

    inside_forbidden = np.zeros(len(t_np), dtype=bool)

    # t が forbidden interval 内に入っているか
    inside_forbidden[valid_prev] = (
        t_np[valid_prev] <= f_ends_np[i_prev[valid_prev]]
    )

    # start 側の切り詰め
    start_trim = start_np.copy()

    use_prev_trim = np.zeros(len(t_np), dtype=bool)
    use_prev_trim[valid_prev] = (
        f_ends_np[i_prev[valid_prev]] > start_np[valid_prev]
    )

    start_trim[use_prev_trim] = (
        f_ends_np[i_prev[use_prev_trim]] + np.timedelta64(eps.value, "ns")
    )

    # next forbidden interval
    # inside でない場合、直後の interval は i_prev + 1
    i_next = i_prev + 1
    valid_next = i_next < len(f_starts_np)

    end_trim = end_np.copy()

    use_next_trim = np.zeros(len(t_np), dtype=bool)
    use_next_trim[valid_next] = (
        f_starts_np[i_next[valid_next]] < end_np[valid_next]
    )

    end_trim[use_next_trim] = (
        f_starts_np[i_next[use_next_trim]] - np.timedelta64(eps.value, "ns")
    )

    valid = (~inside_forbidden) & (end_trim > start_trim)

    start_out = pd.to_datetime(start_trim[valid])
    end_out = pd.to_datetime(end_trim[valid])

    time_ranges = list(zip(start_out, end_out))

    return time_ranges

In [25]:
def merge_time_ranges(
    time_ranges,
    max_duration=None,
):
    """
    overlapping time ranges を merge する。
    max_duration を指定した場合、merge 後の duration がそれを超える merge はしない。
    """

    if len(time_ranges) == 0:
        return []

    time_ranges = sorted(time_ranges)

    merged = []

    for start, end in time_ranges:
        if not merged:
            merged.append((start, end))
            continue

        prev_start, prev_end = merged[-1]

        is_overlapping = start <= prev_end

        candidate_start = prev_start
        candidate_end = max(prev_end, end)

        if max_duration is None:
            ok_duration = True
        else:
            ok_duration = (candidate_end - candidate_start) <= max_duration

        if is_overlapping and ok_duration:
            merged[-1] = (candidate_start, candidate_end)
        else:
            merged.append((start, end))

    return merged

In [26]:
import time

t0_clock = time.perf_counter()

# ============================================================
# forbidden intervals を作る
# ============================================================

forbidden_intervals_df = make_forbidden_intervals_fast(
    bad_times=bad_times,
    LEPe_gap_ranges_df=LEPe_omniflux_gap_ranges_df,
    LEPi_gap_ranges_df=LEPi_omniflux_gap_ranges_df,
    HFA_gap_ranges_df=HFA_L3_gap_ranges_df,
    att_gap_ranges_df=att_nan_intervals_df
)

print(f"forbidden intervals: {len(forbidden_intervals_df)}")

# ============================================================
# selected_times ±15 min を forbidden interval で切る
# ============================================================

time_ranges = make_trimmed_time_ranges_fast(
    selected_times=selected_times,
    forbidden_intervals_df=forbidden_intervals_df,
    half_width=EVENT_HALF_WIDTH,
    eps=pd.Timedelta(nanoseconds=1),
)

print(f"time_ranges before merge: {len(time_ranges)}")

# ============================================================
# merge
# ============================================================

merged_ranges = merge_time_ranges(
    time_ranges,
    max_duration=None,
    # max_duration=pd.Timedelta(minutes=60),  # 必要ならこちら
)

# ============================================================
# DataFrame 化
# ============================================================

merged_ranges_df = pd.DataFrame(
    merged_ranges,
    columns=["start_time", "end_time"]
)

if len(merged_ranges_df) > 0:
    merged_ranges_df["duration_sec"] = (
        merged_ranges_df["end_time"] - merged_ranges_df["start_time"]
    ).dt.total_seconds()
    merged_ranges_df["duration_minutes"] = merged_ranges_df["duration_sec"] / 60

    merged_ranges_df = merged_ranges_df[
        merged_ranges_df["duration_sec"] >= MIN_EVENT_DURATION.total_seconds()
    ].reset_index(drop=True)
else:
    merged_ranges_df["duration_sec"] = []
    merged_ranges_df["duration_minutes"] = []

elapsed = time.perf_counter() - t0_clock

print(f"元の選択時間数: {len(selected_times)}")
print(f"400秒以上のマージ後時間範囲数: {len(merged_ranges_df)}")
print(f"elapsed: {elapsed:.2f} sec")
print("\n有効なマージ時間範囲:")
display(merged_ranges_df)

forbidden intervals: 12466
time_ranges before merge: 100831
元の選択時間数: 100831
400秒以上のマージ後時間範囲数: 394
elapsed: 2.73 sec

有効なマージ時間範囲:

,start_time,end_time,duration_sec,duration_minutes
0,2020-03-01 00:07:37.057405001,2020-03-01 00:50:27.056379,2569.998974,42.833316
1,2020-03-01 00:56:26.056025000,2020-03-01 01:41:14.041179,2687.985154,44.799753
2,2020-03-01 01:44:43.039767000,2020-03-01 01:52:00.041287,437.001520,7.283359
3,2020-03-01 02:24:32.047267000,2020-03-01 02:33:18.038827,525.991560,8.766526
4,2020-03-01 06:28:56.008816000,2020-03-01 06:45:48.999552,1012.990736,16.883179
...,...,...,...,...
389,2020-03-31 14:54:12.659703000,2020-03-31 15:01:03.658775,410.999072,6.849985
390,2020-03-31 15:11:14.651863000,2020-03-31 15:18:05.651954,411.000091,6.850002
391,2020-03-31 15:42:56.643964000,2020-03-31 15:54:41.645240,705.001276,11.750021
392,2020-03-31 16:32:41.637232000,2020-03-31 16:53:26.629087,1244.991855,20.749864
393,2020-03-31 17:26:52.617188000,2020-03-31 17:33:34.617188,402.000000,6.700000

# MGF dataのFFT

In [27]:
import time
import numpy as np
import pandas as pd
import xarray as xr
from tqdm.auto import tqdm


MGF_LOAD_PAD = pd.Timedelta(seconds=2)
MGF_MAX_BLOCK_HOURS = 24
MGF_RETRY_DELAYS_SEC = (0, 30, 120, 300)
MGF_DOWNLOAD_WORKERS = 8


def _format_erg_trange(start, end):
    start = pd.to_datetime(start)
    end = pd.to_datetime(end)
    return [
        start.strftime("%Y%m%d/%H:%M:%S"),
        end.strftime("%Y%m%d/%H:%M:%S"),
    ]


def _drop_duplicate_times(da, time_dim="time"):
    times = pd.DatetimeIndex(pd.to_datetime(da[time_dim].values))
    keep = ~times.duplicated(keep="first")
    return da.isel({time_dim: keep})


def _normalize_time_ranges(ranges_df):
    if ranges_df is None or len(ranges_df) == 0:
        raise ValueError("ranges_df が空なので MGF data を読み込めない。")

    ranges = ranges_df.dropna(subset=["start_time", "end_time"]).copy()
    ranges["start_time"] = pd.to_datetime(ranges["start_time"])
    ranges["end_time"] = pd.to_datetime(ranges["end_time"])
    ranges = ranges[ranges["end_time"] > ranges["start_time"]]
    ranges = ranges.sort_values(["start_time", "end_time"]).reset_index(drop=True)

    if len(ranges) == 0:
        raise ValueError("有効な MGF 読み込み時間範囲がない。")

    return ranges


def build_mgf_hour_blocks(
    ranges_df,
    pad=MGF_LOAD_PAD,
    max_block_hours=MGF_MAX_BLOCK_HOURS,
):
    """
    イベント範囲が触れる1時間ファイルを一意化し、連続hourをblock化する。
    blockはメモリ使用量を制限するため max_block_hours 時間以下に分割する。
    """
    ranges = _normalize_time_ranges(ranges_df)
    pad = pd.Timedelta(pad)
    max_block_hours = int(max_block_hours)

    if max_block_hours < 1:
        raise ValueError("max_block_hours は1以上にする。")

    required_hours = set()
    for row in ranges.itertuples(index=False):
        first_hour = (row.start_time - pad).floor("h")
        last_hour = (row.end_time + pad).floor("h")
        required_hours.update(pd.date_range(first_hour, last_hour, freq="h"))

    required_hours = pd.DatetimeIndex(sorted(required_hours))
    if len(required_hours) == 0:
        return ranges, required_hours, []

    one_hour = pd.Timedelta(hours=1)
    blocks = []
    block_start = required_hours[0]
    block_last = required_hours[0]
    block_n_hours = 1

    for hour in required_hours[1:]:
        is_consecutive = hour == block_last + one_hour
        within_limit = block_n_hours < max_block_hours

        if is_consecutive and within_limit:
            block_last = hour
            block_n_hours += 1
        else:
            blocks.append((block_start, block_last + one_hour))
            block_start = hour
            block_last = hour
            block_n_hours = 1

    blocks.append((block_start, block_last + one_hour))
    return ranges, required_hours, blocks


def make_mask_in_padded_ranges(time_values, ranges_df, pad=MGF_LOAD_PAD):
    """
    ソート済みtime軸に対し、イベント範囲+padのunion maskをO(N log M)で作る。
    """
    times = pd.DatetimeIndex(pd.to_datetime(time_values))
    if len(times) == 0:
        return np.zeros(0, dtype=bool)

    ranges = _normalize_time_ranges(ranges_df)
    pad = pd.Timedelta(pad)

    starts_ns = pd.DatetimeIndex(ranges["start_time"] - pad).to_numpy(
        dtype="datetime64[ns]"
    ).astype(np.int64)
    ends_ns = pd.DatetimeIndex(ranges["end_time"] + pad).to_numpy(
        dtype="datetime64[ns]"
    ).astype(np.int64)
    times_ns = times.to_numpy(dtype="datetime64[ns]").astype(np.int64)

    left = np.searchsorted(times_ns, starts_ns, side="left")
    right = np.searchsorted(times_ns, ends_ns, side="right")

    delta = np.zeros(len(times_ns) + 1, dtype=np.int64)
    np.add.at(delta, left, 1)
    np.add.at(delta, right, -1)
    return np.cumsum(delta[:-1]) > 0

def _missing_required_mgf_hours(da, required_hours, block_start, block_end):
    """Return required hour starts that have no samples in a loaded block."""
    expected = required_hours[
        (required_hours >= pd.Timestamp(block_start))
        & (required_hours < pd.Timestamp(block_end))
    ]
    if da is None or da.sizes.get("time", 0) == 0:
        return list(expected)

    present = pd.DatetimeIndex(pd.to_datetime(da["time"].values)).floor("h").unique()
    return list(expected.difference(present))


def _format_mgf_hours(hours):
    return [pd.Timestamp(hour).strftime("%Y-%m-%d %H:00") for hour in hours]


def load_mgf64_for_ranges(
    ranges_df,
    pad=MGF_LOAD_PAD,
    no_update=True,
    max_block_hours=MGF_MAX_BLOCK_HOURS,
    retry_delays_sec=MGF_RETRY_DELAYS_SEC,
):
    """
    必要なMGF 64 Hzのhourファイルを一意化し、連続hour blockごとに読み込む。
    読込後はイベント範囲+padだけを残す。

    CDF取得だけを並列化し、グローバルtplot変数を使うblock読込は逐次実行する。
    """
    ranges, required_hours, hour_blocks = build_mgf_hour_blocks(
        ranges_df,
        pad=pad,
        max_block_hours=max_block_hours,
    )

    if len(hour_blocks) == 0:
        raise ValueError("必要な MGF hour block がない。")

    print(f"MGF event ranges       : {len(ranges)}")
    print(f"MGF unique hour files  : {len(required_hours)}")
    print(f"MGF load blocks        : {len(hour_blocks)}")
    print(f"MGF max block hours    : {int(max_block_hours)}")

    retry_delays_sec = tuple(float(delay) for delay in retry_delays_sec)
    if len(retry_delays_sec) == 0:
        raise ValueError("retry_delays_secには少なくとも初回試行を指定する。")
    if any((not np.isfinite(delay)) or delay < 0 for delay in retry_delays_sec):
        raise ValueError("MGF retry delayは有限の非負値で指定する。")

    print(f"MGF retry attempts     : {len(retry_delays_sec)}")
    print(f"MGF retry delays [s]   : {retry_delays_sec}")

    if not no_update:
        def prefetch_mgf_block(block_index, block_start, block_end):
            query_end = block_end - pd.Timedelta(seconds=1)
            trange_i = _format_erg_trange(block_start, query_end)

            def covers_block(result):
                files = _normalize_download_files(result)
                if not files:
                    return False
                filenames = [Path(path).name for path in files]
                expected_hours = pd.date_range(
                    block_start,
                    block_end - pd.Timedelta(hours=1),
                    freq="h",
                )
                return all(
                    any(hour.strftime("%Y%m%d%H") in name for name in filenames)
                    for hour in expected_hours
                )

            files = load_erg_with_retry(
                ergpy.mgf,
                description=(
                    f"MGF block {block_index + 1}/{len(hour_blocks)} prefetch"
                ),
                validate_result=covers_block,
                retry_delays_sec=retry_delays_sec,
                trange=trange_i,
                level="l2",
                datatype="64hz",
                get_support_data=True,
                downloadonly=True,
                no_update=False,
                time_clip=True,
            )
            return _normalize_download_files(files)

        worker_count = max(1, min(int(MGF_DOWNLOAD_WORKERS), len(hour_blocks)))
        print(f"MGF prefetch workers    : {worker_count}")
        prefetch_failures = []
        with ThreadPoolExecutor(max_workers=worker_count) as executor:
            futures = {
                executor.submit(
                    prefetch_mgf_block, i, block_start, block_end
                ): (i, block_start, block_end)
                for i, (block_start, block_end) in enumerate(hour_blocks)
            }
            for future in as_completed(futures):
                i, block_start, block_end = futures[future]
                try:
                    future.result()
                except Exception as err:
                    prefetch_failures.append(
                        (i, block_start, block_end, repr(err))
                    )

        if prefetch_failures:
            for i, block_start, block_end, error in prefetch_failures:
                print(
                    f"MGF prefetch failed: block {i + 1} "
                    f"[{block_start} -- {block_end}) ({error})"
                )
            raise RuntimeError(
                f"MGF prefetch failed for "
                f"{len(prefetch_failures)}/{len(hour_blocks)} block(s)"
            )
        print(f"MGF prefetch complete   : {len(hour_blocks)} block(s)")

    loaded_blocks = {}
    pending_blocks = [
        (i, block_start, block_end)
        for i, (block_start, block_end) in enumerate(hour_blocks)
    ]
    block_status = {
        i: {
            "block_id": int(i + 1),
            "block_start": pd.Timestamp(block_start),
            "block_end": pd.Timestamp(block_end),
            "attempts": 0,
            "status": "pending",
            "last_error": "",
        }
        for i, (block_start, block_end) in enumerate(hour_blocks)
    }

    for attempt, delay_sec in enumerate(retry_delays_sec, start=1):
        if len(pending_blocks) == 0:
            break

        if delay_sec > 0:
            print(
                f"waiting {delay_sec:g} s before MGF attempt "
                f"{attempt}/{len(retry_delays_sec)} for {len(pending_blocks)} block(s)"
            )
            time.sleep(delay_sec)

        failed_blocks = []
        description = f"Loading MGF blocks attempt {attempt}/{len(retry_delays_sec)}"
        for i, block_start, block_end in tqdm(
            pending_blocks, total=len(pending_blocks), desc=description
        ):
            query_end = block_end - pd.Timedelta(seconds=1)
            trange_i = _format_erg_trange(block_start, query_end)
            block_status[i]["attempts"] = int(attempt)

            # ergpy/pytplotは同じ変数名を使うため、試行ごとに一度消去する。
            pt.del_data("erg_mgf_l2_mag_64hz_dsi")
            pt.del_data("erg_mgf_l2_quality_64hz")

            try:
                ergpy.mgf(
                    trange=trange_i,
                    level="l2",
                    datatype="64hz",
                    get_support_data=True,
                    no_update=True,
                    time_clip=True,
                )

                B_i = psp.get_data("erg_mgf_l2_mag_64hz_dsi", xarray=True)
                qf_i = psp.get_data("erg_mgf_l2_quality_64hz", xarray=True)
                if B_i is None or qf_i is None:
                    raise RuntimeError("MGF variables were not created")

                # block_endは次hourの境界なので右端を含めない。
                block_end_inclusive = block_end - pd.Timedelta(nanoseconds=1)
                B_i = B_i.sortby("time").sel(
                    time=slice(block_start, block_end_inclusive)
                )
                qf_i = qf_i.sortby("time").sel(
                    time=slice(block_start, block_end_inclusive)
                )
                if (
                    B_i.sizes.get("time", 0) == 0
                    or qf_i.sizes.get("time", 0) == 0
                ):
                    raise RuntimeError("MGF variables are empty")

                missing_B_hours = _missing_required_mgf_hours(
                    B_i, required_hours, block_start, block_end
                )
                missing_qf_hours = _missing_required_mgf_hours(
                    qf_i, required_hours, block_start, block_end
                )
                missing_hours = sorted(set(missing_B_hours) | set(missing_qf_hours))
                if missing_hours:
                    raise RuntimeError(
                        f"missing required MGF hour(s): {_format_mgf_hours(missing_hours)}"
                    )

                loaded_blocks[i] = (B_i, qf_i)
                block_status[i]["status"] = "success"
                block_status[i]["last_error"] = ""
                print(
                    f"loaded MGF block {i + 1}/{len(hour_blocks)} on attempt {attempt}: "
                    f"{trange_i[0]} - {trange_i[1]}"
                )
            except Exception as err:
                failed_blocks.append((i, block_start, block_end))
                block_status[i]["status"] = (
                    "retrying" if attempt < len(retry_delays_sec) else "failed"
                )
                block_status[i]["last_error"] = repr(err)
                print(
                    f"MGF block {i + 1}/{len(hour_blocks)} failed on attempt "
                    f"{attempt}/{len(retry_delays_sec)}: {trange_i} ({err})"
                )
            finally:
                pt.del_data("erg_mgf_l2_mag_64hz_dsi")
                pt.del_data("erg_mgf_l2_quality_64hz")

        pending_blocks = failed_blocks

    MGF_block_status_df = pd.DataFrame(
        [block_status[i] for i in range(len(hour_blocks))]
    )
    if pending_blocks:
        failed_summary = []
        for i, block_start, block_end in pending_blocks:
            failed_summary.append(
                f"block {i + 1} [{block_start} -- {block_end})"
            )
        print(
            MGF_block_status_df.loc[
                MGF_block_status_df["status"] != "success"
            ].to_string(index=False)
        )
        raise RuntimeError(
            "MGF download failed after retries: " + "; ".join(failed_summary)
        )

    B_list = [loaded_blocks[i][0] for i in range(len(hour_blocks))]
    qf_list = [loaded_blocks[i][1] for i in range(len(hour_blocks))]

    B64_data_dsi = _drop_duplicate_times(
        xr.concat(B_list, dim="time").sortby("time")
    )
    B64_data_dsi_quality_flag = _drop_duplicate_times(
        xr.concat(qf_list, dim="time").sortby("time")
    )

    # hourファイル全体ではなく、FFTに必要なイベント範囲+padだけを保持する。
    B_mask = xr.DataArray(
        make_mask_in_padded_ranges(B64_data_dsi.time.values, ranges, pad=pad),
        coords={"time": B64_data_dsi.time},
        dims=("time",),
    )
    qf_mask = xr.DataArray(
        make_mask_in_padded_ranges(B64_data_dsi_quality_flag.time.values, ranges, pad=pad),
        coords={"time": B64_data_dsi_quality_flag.time},
        dims=("time",),
    )

    B64_data_dsi = B64_data_dsi.where(B_mask, drop=True)
    B64_data_dsi_quality_flag = B64_data_dsi_quality_flag.where(qf_mask, drop=True)

    if (
        B64_data_dsi.sizes.get("time", 0) == 0
        or B64_data_dsi_quality_flag.sizes.get("time", 0) == 0
    ):
        raise ValueError("hour block読込後、イベント範囲+pad内に MGF data がない。")

    return B64_data_dsi, B64_data_dsi_quality_flag, MGF_block_status_df


B64_data_dsi, B64_data_dsi_quality_flag, MGF_block_status_df = load_mgf64_for_ranges(
    merged_ranges_df,
    pad=MGF_LOAD_PAD,
    no_update=False,
    max_block_hours=MGF_MAX_BLOCK_HOURS,
    retry_delays_sec=MGF_RETRY_DELAYS_SEC,
)

print(B64_data_dsi)
print(B64_data_dsi_quality_flag)
print("MGF block status:")
print(MGF_block_status_df["status"].value_counts(dropna=False).to_string())
print(f"MGF blocks recovered by retry: {(MGF_block_status_df['attempts'] > 1).sum()}")

29-Sep-26 18:09:07: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

MGF event ranges       : 394
MGF unique hour files  : 278
MGF load blocks        : 86
MGF max block hours    : 24
MGF retry attempts     : 4
MGF retry delays [s]   : (0.0, 30.0, 120.0, 300.0)

Loading MGF blocks attempt 1/4:   0%|          | 0/86 [00:00<?, ?it/s]29-Sep-26 18:09:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:09:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:09:07: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:09:27: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:09:53: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:10:23: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:10:46: Connection error getting remote index https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/, marking this URL as bad
29-Sep-26 18:10:48: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:10:48: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:10:48: The name erg_mgf_l2_mag_64hz_dsi is currently not in pyspedas
29-Sep-26 18:10:48: The name erg_mgf_l2_quality_64hz is currently not in pyspedas
29-Sep-26 18:10:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:10:48: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   1%|          | 1/86 [01:40<2:22:24, 100.52s/it]29-Sep-26 18:10:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:10:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:10:48: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

MGF block 1/86 failed on attempt 1/4: ['20200301/00:00:00', '20200301/02:59:59'] (MGF variables were not created)

29-Sep-26 18:11:08: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:11:16: Remote index took 28.2 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:11:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030106_v04.06.cdf
29-Sep-26 18:11:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030107_v04.06.cdf
29-Sep-26 18:11:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030108_v04.06.cdf
29-Sep-26 18:11:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030109_v04.06.cdf
29-Sep-26 18:11:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030110_v04.06.cdf
29-Sep-26 18:11:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030111_v04.06.cdf
29-Sep-26 18:11:26: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030112_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030112_v04.06.cdf
29-Sep-26 18:11:27: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030112_v04.06.cdf complete, 5.081 MB in 0.4 sec (12.974 MB/sec) (transfer_normal)
29-Sep-26 18:11:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:11:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:11:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf0de420> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf30a690> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb8ec0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ceff66c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf30a690> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb8ec0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d061b20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:32: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   2%|▏         | 2/86 [02:24<1:34:26, 67.46s/it] 29-Sep-26 18:11:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:32: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 2/86 on attempt 1: 20200301/06:00:00 - 20200301/12:59:59

29-Sep-26 18:11:34: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030114_v04.06.cdf
29-Sep-26 18:11:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030115_v04.06.cdf
29-Sep-26 18:11:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030116_v04.06.cdf
29-Sep-26 18:11:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:11:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:11:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf03fef0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfa3e30> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ca512ff0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:11:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:40: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   3%|▎         | 3/86 [02:32<55:35, 40.19s/it]  29-Sep-26 18:11:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:11:40: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 3/86 on attempt 1: 20200301/14:00:00 - 20200301/16:59:59

29-Sep-26 18:12:00: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:12:28: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:12:56: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:13:01: Remote index took 81.5 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:13:12: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030301_v04.06.cdf
29-Sep-26 18:13:13: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:13:13: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:13:13: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ceff7800> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:13:13: del_data: No valid tplot variables found, returning
29-Sep-26 18:13:13: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   5%|▍         | 4/86 [04:06<1:23:55, 61.40s/it]29-Sep-26 18:13:13: del_data: No valid tplot variables found, returning
29-Sep-26 18:13:13: del_data: No valid tplot variables found, returning
29-Sep-26 18:13:13: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 4/86 on attempt 1: 20200303/01:00:00 - 20200303/01:59:59

29-Sep-26 18:13:37: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:14:05: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:14:36: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:14:54: Remote index took 100.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:14:56: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030305_v04.06.cdf
29-Sep-26 18:15:05: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030305_v04.06.cdf
29-Sep-26 18:15:08: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030306_v04.06.cdf
29-Sep-26 18:15:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030307_v04.06.cdf
29-Sep-26 18:15:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030308_v04.06.cdf
29-Sep-26 18:15:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030309_v04.06.cdf
29-Sep-26 18:15:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030310_v04.06.cdf
29-Sep-26 18:15:34: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030311_v04.06.cdf
29-Sep-26 18:15:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:15:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:15:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfcd760> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb4da0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee57290> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee55eb0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:35: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b5ac0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:35: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cf06090> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:35: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfcd760> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:15:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:15:38: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   6%|▌         | 5/86 [06:31<2:03:32, 91.51s/it]29-Sep-26 18:15:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:15:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:15:38: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 5/86 on attempt 1: 20200303/05:00:00 - 20200303/11:59:59

29-Sep-26 18:15:59: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:16:13: Remote index took 34.9 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:16:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030314_v04.06.cdf
29-Sep-26 18:16:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030315_v04.06.cdf
29-Sep-26 18:16:20: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:16:20: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:16:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d061520> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe3830> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:21: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   7%|▋         | 6/86 [07:14<1:40:01, 75.02s/it]29-Sep-26 18:16:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 6/86 on attempt 1: 20200303/14:00:00 - 20200303/15:59:59

29-Sep-26 18:16:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030317_v04.06.cdf
29-Sep-26 18:16:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030318_v04.06.cdf
29-Sep-26 18:16:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030319_v04.06.cdf
29-Sep-26 18:16:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030320_v04.06.cdf
29-Sep-26 18:16:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:16:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:16:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0623c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b6fc0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0776b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe23c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:16:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:46: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   8%|▊         | 7/86 [07:38<1:17:03, 58.52s/it]29-Sep-26 18:16:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:16:46: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 7/86 on attempt 1: 20200303/17:00:00 - 20200303/20:59:59

29-Sep-26 18:17:00: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030404_v04.06.cdf
29-Sep-26 18:17:05: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030405_v04.06.cdf
29-Sep-26 18:17:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:17:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:17:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0623c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:17:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b5a30> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:17:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:17:07: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:   9%|▉         | 8/86 [07:59<1:00:32, 46.57s/it]29-Sep-26 18:17:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:17:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:17:07: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 8/86 on attempt 1: 20200304/04:00:00 - 20200304/05:59:59

29-Sep-26 18:17:29: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:17:57: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:18:27: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:18:48: Connection error getting remote index https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/, marking this URL as bad
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: Skipping remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/ (previous attempt failed)
29-Sep-26 18:18:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:18:50: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  10%|█         | 9/86 [09:43<1:22:32, 64.31s/it]29-Sep-26 18:18:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:18:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:18:50: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

MGF block 9/86 failed on attempt 1/4: ['20200304/09:00:00', '20200304/15:59:59'] (MGF variables are empty)

29-Sep-26 18:19:11: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:19:14: Remote index took 23.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:19:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030421_v04.06.cdf
29-Sep-26 18:19:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:19:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:19:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b79e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:19:17: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:17: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  12%|█▏        | 10/86 [10:10<1:06:58, 52.87s/it]29-Sep-26 18:19:17: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:17: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:17: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 10/86 on attempt 1: 20200304/21:00:00 - 20200304/21:59:59

29-Sep-26 18:19:24: Remote index took 6.1 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:19:32: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030500_v04.06.cdf
29-Sep-26 18:19:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:19:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:19:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda81f70> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:19:33: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:33: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  13%|█▎        | 11/86 [10:26<51:58, 41.58s/it]  29-Sep-26 18:19:33: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:33: del_data: No valid tplot variables found, returning
29-Sep-26 18:19:33: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 11/86 on attempt 1: 20200305/00:00:00 - 20200305/00:59:59

29-Sep-26 18:19:39: Remote index took 5.6 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:19:41: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030505_v04.06.cdf
29-Sep-26 18:19:54: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030505_v04.06.cdf
29-Sep-26 18:20:00: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030506_v04.06.cdf
29-Sep-26 18:20:04: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030507_v04.06.cdf
29-Sep-26 18:20:06: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030508_v04.06.cdf
29-Sep-26 18:20:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030509_v04.06.cdf
29-Sep-26 18:20:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030510_v04.06.cdf
29-Sep-26 18:20:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:20:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:20:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6180> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6150> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d08eb70> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac7650> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b6ba0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b7a10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:21: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  14%|█▍        | 12/86 [11:13<53:25, 43.32s/it]29-Sep-26 18:20:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 12/86 on attempt 1: 20200305/05:00:00 - 20200305/10:59:59

29-Sep-26 18:20:38: Remote index took 16.9 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:20:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030600_v04.06.cdf
29-Sep-26 18:20:40: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:20:40: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:20:40: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac76e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:41: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  15%|█▌        | 13/86 [11:33<44:08, 36.28s/it]29-Sep-26 18:20:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:41: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 13/86 on attempt 1: 20200306/00:00:00 - 20200306/00:59:59

29-Sep-26 18:20:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030609_v04.06.cdf
29-Sep-26 18:20:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030610_v04.06.cdf
29-Sep-26 18:20:46: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:20:46: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:20:46: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf0de2d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:46: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f0b60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:47: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  16%|█▋        | 14/86 [11:39<32:31, 27.10s/it]29-Sep-26 18:20:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:47: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 14/86 on attempt 1: 20200306/09:00:00 - 20200306/10:59:59

29-Sep-26 18:20:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030612_v04.06.cdf
29-Sep-26 18:20:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030613_v04.06.cdf
29-Sep-26 18:20:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030614_v04.06.cdf
29-Sep-26 18:20:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030615_v04.06.cdf
29-Sep-26 18:20:55: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:20:55: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:20:55: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfce6c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:55: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f3c80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:55: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d076f00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee54c80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:20:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:58: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  17%|█▋        | 15/86 [11:50<26:17, 22.21s/it]29-Sep-26 18:20:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:20:58: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 15/86 on attempt 1: 20200306/12:00:00 - 20200306/15:59:59

29-Sep-26 18:21:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030705_v04.06.cdf
29-Sep-26 18:21:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030706_v04.06.cdf
29-Sep-26 18:21:32: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030707_v04.06.cdf
29-Sep-26 18:21:39: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030708_v04.06.cdf
29-Sep-26 18:21:44: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030709_v04.06.cdf
29-Sep-26 18:21:45: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:21:45: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:21:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaab0e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:21:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f0b90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:21:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaa8cb0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:21:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb2450> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:21:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f2ff0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:21:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:21:48: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  19%|█▊        | 16/86 [12:40<35:47, 30.67s/it]29-Sep-26 18:21:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:21:48: del_data: No valid tplot variables found, returning
29-Sep-26 18:21:48: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 16/86 on attempt 1: 20200307/05:00:00 - 20200307/09:59:59

29-Sep-26 18:22:11: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:22:39: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:22:43: Remote index took 55.2 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:22:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030713_v04.06.cdf
29-Sep-26 18:22:45: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:22:45: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:22:45: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d12e270> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:22:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:46: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  20%|█▉        | 17/86 [13:38<44:41, 38.86s/it]29-Sep-26 18:22:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:46: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 17/86 on attempt 1: 20200307/13:00:00 - 20200307/13:59:59

29-Sep-26 18:22:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030804_v04.06.cdf
29-Sep-26 18:22:52: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:22:52: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:22:52: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d074140> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:22:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:52: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  21%|██        | 18/86 [13:45<32:58, 29.09s/it]29-Sep-26 18:22:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:22:52: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 18/86 on attempt 1: 20200308/04:00:00 - 20200308/04:59:59

29-Sep-26 18:23:02: Remote index took 9.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:23:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030808_v04.06.cdf
29-Sep-26 18:23:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030809_v04.06.cdf
29-Sep-26 18:23:30: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030810_v04.06.cdf
29-Sep-26 18:23:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030811_v04.06.cdf
29-Sep-26 18:23:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030812_v04.06.cdf
29-Sep-26 18:23:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030813_v04.06.cdf
29-Sep-26 18:24:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030814_v04.06.cdf
29-Sep-26 18:24:16: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:24:16: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:24:16: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb80a5f5820> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac7bc0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b6000> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf03c8f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84e180> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb2f00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf309550> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:24:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:24:21: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  22%|██▏       | 19/86 [15:14<52:31, 47.04s/it]29-Sep-26 18:24:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:24:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:24:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 19/86 on attempt 1: 20200308/08:00:00 - 20200308/14:59:59

29-Sep-26 18:24:41: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:24:43: Remote index took 21.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:24:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030819_v04.06.cdf
29-Sep-26 18:24:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030820_v04.06.cdf
29-Sep-26 18:24:58: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030821_v04.06.cdf
29-Sep-26 18:25:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030822_v04.06.cdf
29-Sep-26 18:25:05: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030823_v04.06.cdf
29-Sep-26 18:25:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:25:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:25:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb80a61dcd0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda37140> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda17b90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac5e80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b6000> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:09: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:09: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  23%|██▎       | 20/86 [16:01<52:01, 47.30s/it]29-Sep-26 18:25:09: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:09: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:09: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 20/86 on attempt 1: 20200308/19:00:00 - 20200308/23:59:59

29-Sep-26 18:25:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030904_v04.06.cdf
29-Sep-26 18:25:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030905_v04.06.cdf
29-Sep-26 18:25:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030906_v04.06.cdf
29-Sep-26 18:25:30: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030907_v04.06.cdf
29-Sep-26 18:25:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030908_v04.06.cdf
29-Sep-26 18:25:37: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:25:37: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:25:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe33b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c71473b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac47a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84cbf0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda17530> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:25:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:40: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  24%|██▍       | 21/86 [16:32<45:53, 42.37s/it]29-Sep-26 18:25:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:25:40: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 21/86 on attempt 1: 20200309/04:00:00 - 20200309/08:59:59

29-Sep-26 18:26:00: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:26:16: Remote index took 36.6 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:26:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030918_v04.06.cdf
29-Sep-26 18:26:18: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:26:18: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:26:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ceff7bf0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:19: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:19: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  26%|██▌       | 22/86 [17:12<44:10, 41.42s/it]29-Sep-26 18:26:19: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:19: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:19: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 22/86 on attempt 1: 20200309/18:00:00 - 20200309/18:59:59

29-Sep-26 18:26:23: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031000_v04.06.cdf
29-Sep-26 18:26:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:26:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:26:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f0b30> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:24: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  27%|██▋       | 23/86 [17:16<31:57, 30.44s/it]29-Sep-26 18:26:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:24: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 23/86 on attempt 1: 20200310/00:00:00 - 20200310/00:59:59

29-Sep-26 18:26:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031002_v04.06.cdf
29-Sep-26 18:26:28: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:26:28: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:26:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee54e00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:28: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  28%|██▊       | 24/86 [17:21<23:25, 22.67s/it]29-Sep-26 18:26:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:26:28: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 24/86 on attempt 1: 20200310/02:00:00 - 20200310/02:59:59

29-Sep-26 18:26:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031006_v04.06.cdf
29-Sep-26 18:26:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031007_v04.06.cdf
29-Sep-26 18:26:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031008_v04.06.cdf
29-Sep-26 18:26:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031009_v04.06.cdf
29-Sep-26 18:26:51: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031010_v04.06.cdf
29-Sep-26 18:26:52: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031011_v04.06.cdf
29-Sep-26 18:26:54: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031012_v04.06.cdf
29-Sep-26 18:26:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031013_v04.06.cdf
29-Sep-26 18:26:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:26:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:26:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda366c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7144050> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b4050> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda14440> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d060890> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfcf140> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaab680> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:26:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaaad80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:27:01: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:01: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  29%|██▉       | 25/86 [17:54<26:08, 25.70s/it]29-Sep-26 18:27:01: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:01: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:01: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 25/86 on attempt 1: 20200310/06:00:00 - 20200310/13:59:59

29-Sep-26 18:27:03: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031017_v04.06.cdf
29-Sep-26 18:27:03: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:27:04: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:27:04: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac7410> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:27:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:04: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  30%|███       | 26/86 [17:57<18:51, 18.86s/it]29-Sep-26 18:27:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:04: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 26/86 on attempt 1: 20200310/17:00:00 - 20200310/17:59:59

29-Sep-26 18:27:06: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031112_v04.06.cdf
29-Sep-26 18:27:07: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:27:07: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:27:07: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda94470> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:27:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:07: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  31%|███▏      | 27/86 [18:00<13:55, 14.16s/it]29-Sep-26 18:27:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:07: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 27/86 on attempt 1: 20200311/12:00:00 - 20200311/12:59:59

29-Sep-26 18:27:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031115_v04.06.cdf
29-Sep-26 18:27:11: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:27:11: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:27:11: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda15820> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:27:11: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:11: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  33%|███▎      | 28/86 [18:04<10:41, 11.06s/it]29-Sep-26 18:27:11: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:11: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:11: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 28/86 on attempt 1: 20200311/15:00:00 - 20200311/15:59:59

29-Sep-26 18:27:31: Remote index took 20.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:27:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031117_v04.06.cdf
29-Sep-26 18:27:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:27:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:27:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef52450> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:27:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:36: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  34%|███▎      | 29/86 [18:29<14:33, 15.32s/it]29-Sep-26 18:27:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:27:36: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 29/86 on attempt 1: 20200311/17:00:00 - 20200311/17:59:59

29-Sep-26 18:27:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031206_v04.06.cdf
29-Sep-26 18:27:46: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031207_v04.06.cdf
29-Sep-26 18:27:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031208_v04.06.cdf
29-Sep-26 18:27:54: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031209_v04.06.cdf
29-Sep-26 18:27:59: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031210_v04.06.cdf
29-Sep-26 18:28:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031211_v04.06.cdf
29-Sep-26 18:28:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031212_v04.06.cdf
29-Sep-26 18:28:22: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:28:22: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:28:22: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf010b60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:22: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac73e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:22: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda16720> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc728e90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72a1e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda94950> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda83da0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:28:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:28:27: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  35%|███▍      | 30/86 [19:19<24:05, 25.81s/it]29-Sep-26 18:28:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:28:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:28:27: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 30/86 on attempt 1: 20200312/06:00:00 - 20200312/12:59:59

29-Sep-26 18:28:50: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:29:17: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:29:48: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:30:08: Remote index took 101.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:30:10: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031219_v04.06.cdf
29-Sep-26 18:30:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031219_v04.06.cdf
29-Sep-26 18:30:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031220_v04.06.cdf
29-Sep-26 18:30:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031221_v04.06.cdf
29-Sep-26 18:30:21: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:30:21: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:30:21: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac72c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:30:21: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe08c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:30:22: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb3da0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:30:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:30:23: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  36%|███▌      | 31/86 [21:16<48:35, 53.01s/it]29-Sep-26 18:30:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:30:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:30:23: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 31/86 on attempt 1: 20200312/19:00:00 - 20200312/21:59:59

29-Sep-26 18:30:43: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:30:57: Remote index took 34.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:31:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031302_v04.06.cdf
29-Sep-26 18:31:06: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031303_v04.06.cdf
29-Sep-26 18:31:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031304_v04.06.cdf
29-Sep-26 18:31:10: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:31:10: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:31:10: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ceff5e20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:11: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d062540> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:11: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f2210> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:12: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:12: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  37%|███▋      | 32/86 [22:05<46:40, 51.87s/it]29-Sep-26 18:31:12: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:12: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:12: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 32/86 on attempt 1: 20200313/02:00:00 - 20200313/04:59:59

29-Sep-26 18:31:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031306_v04.06.cdf
29-Sep-26 18:31:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031307_v04.06.cdf
29-Sep-26 18:31:21: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:31:21: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:31:21: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f0b60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:21: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf30a690> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:22: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:22: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  38%|███▊      | 33/86 [22:15<34:43, 39.31s/it]29-Sep-26 18:31:22: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:22: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:22: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 33/86 on attempt 1: 20200313/06:00:00 - 20200313/07:59:59

29-Sep-26 18:31:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031310_v04.06.cdf
29-Sep-26 18:31:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031311_v04.06.cdf
29-Sep-26 18:31:30: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:31:30: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:31:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f36b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc734a70> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:31: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  40%|███▉      | 34/86 [22:23<26:03, 30.07s/it]29-Sep-26 18:31:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:31: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 34/86 on attempt 1: 20200313/10:00:00 - 20200313/11:59:59

29-Sep-26 18:31:39: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031315_v04.06.cdf
29-Sep-26 18:31:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031316_v04.06.cdf
29-Sep-26 18:31:41: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:31:41: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:31:41: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72be00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:41: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84daf0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:31:42: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:42: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  41%|████      | 35/86 [22:35<20:50, 24.53s/it]29-Sep-26 18:31:42: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:42: del_data: No valid tplot variables found, returning
29-Sep-26 18:31:42: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 35/86 on attempt 1: 20200313/15:00:00 - 20200313/16:59:59

29-Sep-26 18:32:02: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:32:13: Remote index took 30.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:32:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031409_v04.06.cdf
29-Sep-26 18:32:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031410_v04.06.cdf
29-Sep-26 18:32:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031411_v04.06.cdf
29-Sep-26 18:32:39: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:32:39: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:32:39: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d075ac0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:32:39: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d489a60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:32:39: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda96c60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:32:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:32:41: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  42%|████▏     | 36/86 [23:34<28:58, 34.77s/it]29-Sep-26 18:32:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:32:41: del_data: No valid tplot variables found, returning
29-Sep-26 18:32:41: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 36/86 on attempt 1: 20200314/09:00:00 - 20200314/11:59:59

29-Sep-26 18:32:58: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031506_v04.06.cdf
29-Sep-26 18:32:59: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:32:59: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:32:59: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda80e90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:32:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:32:59: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  43%|████▎     | 37/86 [23:52<24:23, 29.86s/it]29-Sep-26 18:32:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:33:00: del_data: No valid tplot variables found, returning
29-Sep-26 18:33:00: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 37/86 on attempt 1: 20200315/06:00:00 - 20200315/06:59:59

29-Sep-26 18:33:20: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:33:44: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:34:01: Remote index took 61.6 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:34:09: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031513_v04.06.cdf
29-Sep-26 18:34:35: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031514_v04.06.cdf
29-Sep-26 18:34:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031514_v04.06.cdf
29-Sep-26 18:34:53: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031515_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031515_v04.06.cdf
29-Sep-26 18:34:55: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031515_v04.06.cdf complete, 4.786 MB in 13.4 sec (0.358 MB/sec) (transfer_slow)
29-Sep-26 18:35:12: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031516_v04.06.cdf
29-Sep-26 18:35:12: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:35:12: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:35:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72b6b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:35:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc734e90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:35:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7352e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:35:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7341d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:35:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:35:14: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  44%|████▍     | 38/86 [26:07<49:07, 61.40s/it]29-Sep-26 18:35:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:35:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:35:14: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 38/86 on attempt 1: 20200315/13:00:00 - 20200315/16:59:59

29-Sep-26 18:35:36: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:36:04: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:36:34: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:36:52: Remote index took 97.2 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:36:59: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031522_v04.06.cdf
29-Sep-26 18:37:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031523_v04.06.cdf
29-Sep-26 18:37:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031600_v04.06.cdf
29-Sep-26 18:37:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031601_v04.06.cdf
29-Sep-26 18:37:25: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:37:25: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:37:25: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d074290> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:25: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72ba40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:25: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef53770> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:25: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7288c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:28: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  45%|████▌     | 39/86 [28:20<1:04:55, 82.89s/it]29-Sep-26 18:37:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:28: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 39/86 on attempt 1: 20200315/22:00:00 - 20200316/01:59:59

29-Sep-26 18:37:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031606_v04.06.cdf
29-Sep-26 18:37:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031607_v04.06.cdf
29-Sep-26 18:37:39: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031608_v04.06.cdf
29-Sep-26 18:37:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031609_v04.06.cdf
29-Sep-26 18:37:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031610_v04.06.cdf
29-Sep-26 18:37:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031611_v04.06.cdf
29-Sep-26 18:37:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:37:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:37:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84c2f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf20ba70> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84d610> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda94710> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda94470> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736c90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:47: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  47%|████▋     | 40/86 [28:40<49:02, 63.96s/it]  29-Sep-26 18:37:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:47: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:47: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 40/86 on attempt 1: 20200316/06:00:00 - 20200316/11:59:59

29-Sep-26 18:37:55: Remote index took 7.4 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:37:56: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031614_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031614_v04.06.cdf
29-Sep-26 18:37:57: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031614_v04.06.cdf complete, 4.905 MB in 0.7 sec (7.386 MB/sec) (transfer_normal)
29-Sep-26 18:37:57: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:37:57: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:37:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfa1280> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:37:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:58: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  48%|████▊     | 41/86 [28:50<35:53, 47.85s/it]29-Sep-26 18:37:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:58: del_data: No valid tplot variables found, returning
29-Sep-26 18:37:58: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 41/86 on attempt 1: 20200316/14:00:00 - 20200316/14:59:59

29-Sep-26 18:38:02: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031620_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031620_v04.06.cdf
29-Sep-26 18:38:02: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031620_v04.06.cdf complete, 4.931 MB in 0.9 sec (5.796 MB/sec) (transfer_normal)
29-Sep-26 18:38:02: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:38:02: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:38:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda82a50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:03: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  49%|████▉     | 42/86 [28:55<25:43, 35.07s/it]29-Sep-26 18:38:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:03: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 42/86 on attempt 1: 20200316/20:00:00 - 20200316/20:59:59

29-Sep-26 18:38:05: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031703_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031703_v04.06.cdf
29-Sep-26 18:38:06: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031703_v04.06.cdf complete, 4.957 MB in 1.1 sec (4.683 MB/sec) (transfer_normal)
29-Sep-26 18:38:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:38:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:38:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda37890> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:07: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  50%|█████     | 43/86 [28:59<18:25, 25.72s/it]29-Sep-26 18:38:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:07: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:07: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 43/86 on attempt 1: 20200317/03:00:00 - 20200317/03:59:59

29-Sep-26 18:38:09: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031709_v04.06.cdf
29-Sep-26 18:38:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031710_v04.06.cdf
29-Sep-26 18:38:12: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031711_v04.06.cdf
29-Sep-26 18:38:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031712_v04.06.cdf
29-Sep-26 18:38:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031713_v04.06.cdf
29-Sep-26 18:38:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031714_v04.06.cdf
29-Sep-26 18:38:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031715_v04.06.cdf
29-Sep-26 18:38:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:38:18: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba2c90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7349e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda941d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee55670> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda37d40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84c8f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda158b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:38:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:23: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  51%|█████     | 44/86 [29:15<15:55, 22.74s/it]29-Sep-26 18:38:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:38:23: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 44/86 on attempt 1: 20200317/09:00:00 - 20200317/15:59:59

29-Sep-26 18:38:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031721_v04.06.cdf
29-Sep-26 18:38:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031722_v04.06.cdf
29-Sep-26 18:38:52: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031723_v04.06.cdf
29-Sep-26 18:38:59: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031723_v04.06.cdf
29-Sep-26 18:39:00: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:39:00: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:39:00: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7967fb0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:00: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda37bc0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:00: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b7ce0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:02: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:02: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  52%|█████▏    | 45/86 [29:54<18:53, 27.65s/it]29-Sep-26 18:39:02: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:02: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:02: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 45/86 on attempt 1: 20200317/21:00:00 - 20200317/23:59:59

29-Sep-26 18:39:22: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:39:43: Remote index took 41.6 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:39:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031804_v04.06.cdf
29-Sep-26 18:39:49: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:39:49: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:39:49: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84ed50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:49: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  53%|█████▎    | 46/86 [30:42<22:24, 33.62s/it]29-Sep-26 18:39:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:49: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 46/86 on attempt 1: 20200318/04:00:00 - 20200318/04:59:59

29-Sep-26 18:39:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031806_v04.06.cdf
29-Sep-26 18:39:58: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031807_v04.06.cdf
29-Sep-26 18:39:58: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:39:58: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:39:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba0890> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7965be0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:39:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:59: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  55%|█████▍    | 47/86 [30:52<17:15, 26.54s/it]29-Sep-26 18:39:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:39:59: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 47/86 on attempt 1: 20200318/06:00:00 - 20200318/07:59:59

29-Sep-26 18:40:03: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031809_v04.06.cdf
29-Sep-26 18:40:06: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031809_v04.06.cdf
29-Sep-26 18:40:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031810_v04.06.cdf
29-Sep-26 18:40:13: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:40:13: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:40:13: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaabbc0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:13: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba1af0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:14: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  56%|█████▌    | 48/86 [31:07<14:37, 23.08s/it]29-Sep-26 18:40:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:14: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:14: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 48/86 on attempt 1: 20200318/09:00:00 - 20200318/10:59:59

29-Sep-26 18:40:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031817_v04.06.cdf
29-Sep-26 18:40:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031818_v04.06.cdf
29-Sep-26 18:40:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031819_v04.06.cdf
29-Sep-26 18:40:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031820_v04.06.cdf
29-Sep-26 18:40:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:40:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:40:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda35c40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d2cc3e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d077ad0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba3590> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:40:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:39: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  57%|█████▋    | 49/86 [31:31<14:28, 23.48s/it]29-Sep-26 18:40:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:40:39: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 49/86 on attempt 1: 20200318/17:00:00 - 20200318/20:59:59

29-Sep-26 18:41:02: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:41:16: Remote index took 37.8 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:41:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031900_v04.06.cdf
29-Sep-26 18:41:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031901_v04.06.cdf
29-Sep-26 18:41:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031902_v04.06.cdf
29-Sep-26 18:41:50: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:41:50: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:41:50: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba1700> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:41:50: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736360> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:41:50: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc84e810> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:41:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:41:52: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  58%|█████▊    | 50/86 [32:45<23:04, 38.45s/it]29-Sep-26 18:41:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:41:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:41:52: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 50/86 on attempt 1: 20200319/00:00:00 - 20200319/02:59:59

29-Sep-26 18:42:12: Remote index took 20.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:42:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031905_v04.06.cdf
29-Sep-26 18:42:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:42:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:42:26: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda36420> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:42:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:42:27: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  59%|█████▉    | 51/86 [33:19<21:48, 37.38s/it]29-Sep-26 18:42:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:42:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:42:27: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 51/86 on attempt 1: 20200319/05:00:00 - 20200319/05:59:59

29-Sep-26 18:42:34: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031908_v04.06.cdf
29-Sep-26 18:42:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031908_v04.06.cdf
29-Sep-26 18:42:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031909_v04.06.cdf
29-Sep-26 18:42:46: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031910_v04.06.cdf
29-Sep-26 18:42:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031911_v04.06.cdf
29-Sep-26 18:42:52: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031912_v04.06.cdf
29-Sep-26 18:42:54: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031913_v04.06.cdf
29-Sep-26 18:42:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031914_v04.06.cdf
29-Sep-26 18:43:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031915_v04.06.cdf
29-Sep-26 18:43:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:43:17: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:43:17: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d08cad0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee57740> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc729fd0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7965910> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c79653a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda178c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc735ee0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda372c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:43:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:43:23: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  60%|██████    | 52/86 [34:15<24:19, 42.94s/it]29-Sep-26 18:43:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:43:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:43:23: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 52/86 on attempt 1: 20200319/08:00:00 - 20200319/15:59:59

29-Sep-26 18:43:47: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:43:55: Remote index took 31.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:44:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031917_v04.06.cdf
29-Sep-26 18:44:04: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031918_v04.06.cdf
29-Sep-26 18:44:07: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031919_v04.06.cdf
29-Sep-26 18:44:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031920_v04.06.cdf
29-Sep-26 18:44:13: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031921_v04.06.cdf
29-Sep-26 18:44:15: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031922_v04.06.cdf
29-Sep-26 18:44:18: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031923_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031923_v04.06.cdf
29-Sep-26 18:44:19: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020031923_v04.06.cdf complete, 4.869 MB in 2.3 sec (2.151 MB/sec) (transfer_normal)
29-Sep-26 18:44:19: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:44:19: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:44:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72bd40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda37da0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72bd40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba0c50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f1910> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7146870> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78fb91d30> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:24: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  62%|██████▏   | 53/86 [35:16<26:35, 48.35s/it]29-Sep-26 18:44:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:24: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:24: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 53/86 on attempt 1: 20200319/17:00:00 - 20200319/23:59:59

29-Sep-26 18:44:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032014_v04.06.cdf
29-Sep-26 18:44:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032015_v04.06.cdf
29-Sep-26 18:44:28: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032016_v04.06.cdf
29-Sep-26 18:44:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032017_v04.06.cdf
29-Sep-26 18:44:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032018_v04.06.cdf
29-Sep-26 18:44:32: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032019_v04.06.cdf
29-Sep-26 18:44:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:44:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:44:32: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda17740> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c799d0d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d077d10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda80950> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaaa720> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6a20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:36: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  63%|██████▎   | 54/86 [35:29<20:02, 37.58s/it]29-Sep-26 18:44:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:36: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 54/86 on attempt 1: 20200320/14:00:00 - 20200320/19:59:59

29-Sep-26 18:44:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032108_v04.06.cdf
29-Sep-26 18:44:39: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032109_v04.06.cdf
29-Sep-26 18:44:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032110_v04.06.cdf
29-Sep-26 18:44:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032111_v04.06.cdf
29-Sep-26 18:44:44: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032112_v04.06.cdf
29-Sep-26 18:44:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032113_v04.06.cdf
29-Sep-26 18:44:47: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032114_v04.06.cdf
29-Sep-26 18:44:47: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:44:47: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:44:47: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfa1280> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:47: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc728aa0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:48: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda372c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:48: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7145d60> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:48: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda97d10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:48: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda97a10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:48: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba16a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:44:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:52: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  64%|██████▍   | 55/86 [35:44<16:00, 30.99s/it]29-Sep-26 18:44:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:44:52: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 55/86 on attempt 1: 20200321/08:00:00 - 20200321/14:59:59

29-Sep-26 18:45:08: Remote index took 15.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:45:09: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032118_v04.06.cdf
29-Sep-26 18:45:09: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:45:09: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:45:09: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7147f20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:45:10: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:10: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  65%|██████▌   | 56/86 [36:02<13:32, 27.08s/it]29-Sep-26 18:45:10: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:10: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:10: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 56/86 on attempt 1: 20200321/18:00:00 - 20200321/18:59:59

29-Sep-26 18:45:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032122_v04.06.cdf
29-Sep-26 18:45:14: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:45:14: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:45:14: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba04d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:45:15: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:15: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  66%|██████▋   | 57/86 [36:07<09:53, 20.48s/it]29-Sep-26 18:45:15: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:15: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:15: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 57/86 on attempt 1: 20200321/22:00:00 - 20200321/22:59:59

29-Sep-26 18:45:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032202_v04.06.cdf
29-Sep-26 18:45:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032203_v04.06.cdf
29-Sep-26 18:45:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:45:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:45:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c799e8d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:45:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72b350> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:45:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:28: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  67%|██████▋   | 58/86 [36:21<08:35, 18.42s/it]29-Sep-26 18:45:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:28: del_data: No valid tplot variables found, returning
29-Sep-26 18:45:28: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 58/86 on attempt 1: 20200322/02:00:00 - 20200322/03:59:59

29-Sep-26 18:45:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032205_v04.06.cdf
29-Sep-26 18:45:39: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032206_v04.06.cdf
29-Sep-26 18:45:45: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032207_v04.06.cdf
29-Sep-26 18:46:05: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032208_v04.06.cdf
29-Sep-26 18:46:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:46:06: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:46:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72a810> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:46:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc735820> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:46:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaaad80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:46:06: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba3770> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:46:08: del_data: No valid tplot variables found, returning
29-Sep-26 18:46:08: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  69%|██████▊   | 59/86 [37:01<11:09, 24.79s/it]29-Sep-26 18:46:08: del_data: No valid tplot variables found, returning
29-Sep-26 18:46:08: del_data: No valid tplot variables found, returning
29-Sep-26 18:46:08: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 59/86 on attempt 1: 20200322/05:00:00 - 20200322/08:59:59

29-Sep-26 18:46:32: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:46:59: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:47:27: Retrying (LoggingRetry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:47:47: Connection error getting remote index https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/, marking this URL as bad
29-Sep-26 18:47:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:47:49: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  70%|██████▉   | 60/86 [38:42<20:40, 47.73s/it]29-Sep-26 18:47:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:47:49: del_data: No valid tplot variables found, returning
29-Sep-26 18:47:49: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

MGF block 60/86 failed on attempt 1/4: ['20200322/15:00:00', '20200322/15:59:59'] (MGF variables are empty)

29-Sep-26 18:48:10: Remote index took 21.1 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:48:14: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032217_v04.06.cdf
29-Sep-26 18:48:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032217_v04.06.cdf
29-Sep-26 18:48:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032218_v04.06.cdf
29-Sep-26 18:48:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:48:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:48:26: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6a20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:48:26: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc72a990> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:48:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:27: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  71%|███████   | 61/86 [39:20<18:39, 44.78s/it]29-Sep-26 18:48:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:27: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:27: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 61/86 on attempt 1: 20200322/17:00:00 - 20200322/18:59:59

29-Sep-26 18:48:47: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:48:54: Remote index took 26.5 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:48:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032222_v04.06.cdf
29-Sep-26 18:48:58: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:48:58: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:48:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7965df0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:48:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:59: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  72%|███████▏  | 62/86 [39:51<16:17, 40.73s/it]29-Sep-26 18:48:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:48:59: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 62/86 on attempt 1: 20200322/22:00:00 - 20200322/22:59:59

29-Sep-26 18:49:04: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032300_v04.06.cdf
29-Sep-26 18:49:09: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032301_v04.06.cdf
29-Sep-26 18:49:16: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032302_v04.06.cdf
29-Sep-26 18:49:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032303_v04.06.cdf
29-Sep-26 18:49:18: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:49:18: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:49:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaab620> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc735a00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:18: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c71467e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef53ad0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:21: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  73%|███████▎  | 63/86 [40:13<13:28, 35.14s/it]29-Sep-26 18:49:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 63/86 on attempt 1: 20200323/00:00:00 - 20200323/03:59:59

29-Sep-26 18:49:23: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032306_v04.06.cdf
29-Sep-26 18:49:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032307_v04.06.cdf
29-Sep-26 18:49:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032308_v04.06.cdf
29-Sep-26 18:49:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032309_v04.06.cdf
29-Sep-26 18:49:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032310_v04.06.cdf
29-Sep-26 18:49:30: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032311_v04.06.cdf
29-Sep-26 18:49:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032312_v04.06.cdf
29-Sep-26 18:49:33: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032313_v04.06.cdf
29-Sep-26 18:49:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:49:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:49:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d075be0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736ea0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba15b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaab410> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc735b80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef53290> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfcd7f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee57800> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:49:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:39: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  74%|███████▍  | 64/86 [40:32<11:02, 30.13s/it]29-Sep-26 18:49:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:39: del_data: No valid tplot variables found, returning
29-Sep-26 18:49:39: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 64/86 on attempt 1: 20200323/06:00:00 - 20200323/13:59:59

29-Sep-26 18:49:59: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:50:09: Remote index took 30.2 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:50:11: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032316_v04.06.cdf
29-Sep-26 18:50:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032317_v04.06.cdf
29-Sep-26 18:50:17: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032318_v04.06.cdf
29-Sep-26 18:50:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032319_v04.06.cdf
29-Sep-26 18:50:23: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032320_v04.06.cdf
29-Sep-26 18:50:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032321_v04.06.cdf
29-Sep-26 18:50:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032322_v04.06.cdf
29-Sep-26 18:50:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:50:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:50:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe1e50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d076e70> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d076db0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe1e50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0777d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736e10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736960> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:32: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  76%|███████▌  | 65/86 [41:25<12:57, 37.01s/it]29-Sep-26 18:50:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:32: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 65/86 on attempt 1: 20200323/16:00:00 - 20200323/22:59:59

29-Sep-26 18:50:35: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032501_v04.06.cdf
29-Sep-26 18:50:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032502_v04.06.cdf
29-Sep-26 18:50:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032503_v04.06.cdf
29-Sep-26 18:50:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:50:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:50:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d106bd0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf03f170> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d2cc830> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:40: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  77%|███████▋  | 66/86 [41:32<09:23, 28.18s/it]29-Sep-26 18:50:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:40: del_data: No valid tplot variables found, returning
29-Sep-26 18:50:40: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 66/86 on attempt 1: 20200325/01:00:00 - 20200325/03:59:59

29-Sep-26 18:50:42: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032506_v04.06.cdf
29-Sep-26 18:50:44: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032507_v04.06.cdf
29-Sep-26 18:50:47: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032508_v04.06.cdf
29-Sep-26 18:50:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032509_v04.06.cdf
29-Sep-26 18:50:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032510_v04.06.cdf
29-Sep-26 18:50:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032511_v04.06.cdf
29-Sep-26 18:50:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032512_v04.06.cdf
29-Sep-26 18:50:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:50:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:50:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb1760> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb1b50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7353a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7365a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7344a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb2ab0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:50:57: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc7353a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:51:00: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:00: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  78%|███████▊  | 67/86 [41:53<08:12, 25.94s/it]29-Sep-26 18:51:00: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:00: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:00: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 67/86 on attempt 1: 20200325/06:00:00 - 20200325/12:59:59

29-Sep-26 18:51:21: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:51:29: Remote index took 28.9 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:51:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032521_v04.06.cdf
29-Sep-26 18:51:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:51:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:51:32: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc737380> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:51:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:32: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  79%|███████▉  | 68/86 [42:25<08:18, 27.71s/it]29-Sep-26 18:51:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:32: del_data: No valid tplot variables found, returning
29-Sep-26 18:51:32: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 68/86 on attempt 1: 20200325/21:00:00 - 20200325/21:59:59

29-Sep-26 18:51:35: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032612_v04.06.cdf
29-Sep-26 18:51:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032612_v04.06.cdf
29-Sep-26 18:51:48: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032613_v04.06.cdf
29-Sep-26 18:52:02: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032614_v04.06.cdf
29-Sep-26 18:52:07: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032615_v04.06.cdf
29-Sep-26 18:52:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032616_v04.06.cdf
29-Sep-26 18:52:14: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:52:14: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:52:14: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe2000> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:14: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda80380> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:15: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe2000> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:15: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7965100> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:15: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d50cdd0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:18: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:18: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  80%|████████  | 69/86 [43:10<09:20, 32.96s/it]29-Sep-26 18:52:18: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:18: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:18: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 69/86 on attempt 1: 20200326/12:00:00 - 20200326/16:59:59

29-Sep-26 18:52:23: Remote index took 5.0 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:52:31: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032709_v04.06.cdf
29-Sep-26 18:52:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032710_v04.06.cdf
29-Sep-26 18:52:55: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032711_v04.06.cdf
29-Sep-26 18:52:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:52:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:52:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ca510830> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d106bd0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:56: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc67f9e0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:52:57: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:57: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  81%|████████▏ | 70/86 [43:50<09:20, 35.04s/it]29-Sep-26 18:52:57: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:57: del_data: No valid tplot variables found, returning
29-Sep-26 18:52:57: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 70/86 on attempt 1: 20200327/09:00:00 - 20200327/11:59:59

29-Sep-26 18:53:20: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:53:44: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:53:55: Remote index took 57.5 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:54:01: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032715_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032715_v04.06.cdf
29-Sep-26 18:54:03: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032715_v04.06.cdf complete, 4.869 MB in 5.9 sec (0.821 MB/sec) (transfer_slow)
29-Sep-26 18:54:03: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:54:03: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:54:03: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef53590> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:03: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  83%|████████▎ | 71/86 [44:56<11:04, 44.32s/it]29-Sep-26 18:54:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:03: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:03: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 71/86 on attempt 1: 20200327/15:00:00 - 20200327/15:59:59

29-Sep-26 18:54:09: Remote index took 5.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:54:11: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032717_v04.06.cdf
29-Sep-26 18:54:14: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032717_v04.06.cdf
29-Sep-26 18:54:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032718_v04.06.cdf
29-Sep-26 18:54:20: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032719_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032719_v04.06.cdf
29-Sep-26 18:54:21: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032719_v04.06.cdf complete, 4.944 MB in 0.6 sec (7.681 MB/sec) (transfer_normal)
29-Sep-26 18:54:23: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032720_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032720_v04.06.cdf
29-Sep-26 18:54:23: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032720_v04.06.cdf complete, 4.942 MB in 1.2 sec (4.078 MB/sec) (transfer_normal)
29-Sep-26 18:54:24: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:54:24: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:54:24: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf013950> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:24: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6db0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:24: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb2960> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:24: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac5a90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:26: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:26: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  84%|████████▎ | 72/86 [45:19<08:50, 37.89s/it]29-Sep-26 18:54:26: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:26: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:26: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 72/86 on attempt 1: 20200327/17:00:00 - 20200327/20:59:59

29-Sep-26 18:54:32: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032805_v04.06.cdf
29-Sep-26 18:54:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032806_v04.06.cdf
29-Sep-26 18:54:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:54:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:54:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef52fc0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf03f290> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:54:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:38: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  85%|████████▍ | 73/86 [45:30<06:28, 29.92s/it]29-Sep-26 18:54:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:54:38: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 73/86 on attempt 1: 20200328/05:00:00 - 20200328/06:59:59

29-Sep-26 18:54:58: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:55:22: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:55:24: Remote index took 46.6 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:55:25: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032810_v04.06.cdf
29-Sep-26 18:55:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032810_v04.06.cdf
29-Sep-26 18:55:37: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032811_v04.06.cdf
29-Sep-26 18:55:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032812_v04.06.cdf
29-Sep-26 18:55:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032813_v04.06.cdf
29-Sep-26 18:55:44: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:55:44: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:55:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c799de80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda15520> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda808f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:44: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf2093d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:46: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  86%|████████▌ | 74/86 [46:39<08:18, 41.58s/it]29-Sep-26 18:55:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:46: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:46: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 74/86 on attempt 1: 20200328/10:00:00 - 20200328/13:59:59

29-Sep-26 18:55:49: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032815_v04.06.cdf
29-Sep-26 18:55:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032815_v04.06.cdf
29-Sep-26 18:55:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032816_v04.06.cdf
29-Sep-26 18:55:51: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:55:51: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:55:51: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda97560> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:51: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda14ce0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:52: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  87%|████████▋ | 75/86 [46:44<05:38, 30.78s/it]29-Sep-26 18:55:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:52: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:52: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 75/86 on attempt 1: 20200328/15:00:00 - 20200328/16:59:59

29-Sep-26 18:55:54: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032822_v04.06.cdf
29-Sep-26 18:55:56: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032823_v04.06.cdf
29-Sep-26 18:55:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032900_v04.06.cdf
29-Sep-26 18:55:57: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:55:58: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:55:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba0cb0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0754c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:58: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda368d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:55:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:59: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  88%|████████▊ | 76/86 [46:52<03:57, 23.78s/it]29-Sep-26 18:55:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:59: del_data: No valid tplot variables found, returning
29-Sep-26 18:55:59: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 76/86 on attempt 1: 20200328/22:00:00 - 20200329/00:59:59

29-Sep-26 18:56:03: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032904_v04.06.cdf
29-Sep-26 18:56:03: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:56:03: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:56:03: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cf016d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:04: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  90%|████████▉ | 77/86 [46:56<02:41, 17.96s/it]29-Sep-26 18:56:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:04: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:04: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 77/86 on attempt 1: 20200329/04:00:00 - 20200329/04:59:59

29-Sep-26 18:56:17: Remote index took 12.8 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:56:18: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032906_v04.06.cdf
29-Sep-26 18:56:20: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032907_v04.06.cdf
29-Sep-26 18:56:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032908_v04.06.cdf
29-Sep-26 18:56:23: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032909_v04.06.cdf
29-Sep-26 18:56:24: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032910_v04.06.cdf
29-Sep-26 18:56:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032911_v04.06.cdf
29-Sep-26 18:56:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:56:27: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:56:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cd9f0c50> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7973aa0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:27: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda80170> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda80a10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7972c00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:28: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cefe2ea0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:31: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  91%|█████████ | 78/86 [47:24<02:45, 20.75s/it]29-Sep-26 18:56:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:31: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:31: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 78/86 on attempt 1: 20200329/06:00:00 - 20200329/11:59:59

29-Sep-26 18:56:34: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033000_v04.06.cdf
29-Sep-26 18:56:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:56:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:56:34: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda96420> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:35: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:35: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  92%|█████████▏| 79/86 [47:27<01:49, 15.65s/it]29-Sep-26 18:56:35: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:35: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:35: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 79/86 on attempt 1: 20200330/00:00:00 - 20200330/00:59:59

29-Sep-26 18:56:38: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033002_v04.06.cdf
29-Sep-26 18:56:40: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033003_v04.06.cdf
29-Sep-26 18:56:41: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033004_v04.06.cdf
29-Sep-26 18:56:43: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033005_v04.06.cdf
29-Sep-26 18:56:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:56:43: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:56:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b5a90> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc67cfe0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d0b6c00> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:43: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda360c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:56:45: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:45: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  93%|█████████▎| 80/86 [47:38<01:24, 14.16s/it]29-Sep-26 18:56:45: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:45: del_data: No valid tplot variables found, returning
29-Sep-26 18:56:45: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 80/86 on attempt 1: 20200330/02:00:00 - 20200330/05:59:59

29-Sep-26 18:56:47: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033009_v04.06.cdf
29-Sep-26 18:56:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033010_v04.06.cdf
29-Sep-26 18:56:50: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033011_v04.06.cdf
29-Sep-26 18:56:53: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033012_v04.06.cdf
29-Sep-26 18:56:57: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033013_v04.06.cdf
29-Sep-26 18:56:59: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033014_v04.06.cdf
29-Sep-26 18:57:01: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033015_v04.06.cdf
29-Sep-26 18:57:01: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:57:02: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac5af0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c4ba2db0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda82ff0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee564b0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cef50440> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:02: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc736570> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:03: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cc737230> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:57:06: del_data: No valid tplot variables found, returning
29-Sep-26 18:57:06: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  94%|█████████▍| 81/86 [47:59<01:20, 16.12s/it]29-Sep-26 18:57:06: del_data: No valid tplot variables found, returning
29-Sep-26 18:57:06: del_data: No valid tplot variables found, returning
29-Sep-26 18:57:06: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 81/86 on attempt 1: 20200330/09:00:00 - 20200330/15:59:59

29-Sep-26 18:57:26: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:57:54: Retrying (LoggingRetry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:58:05: Remote index took 58.3 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:58:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033020_v04.06.cdf
29-Sep-26 18:58:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033021_v04.06.cdf
29-Sep-26 18:58:36: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033022_v04.06.cdf
29-Sep-26 18:58:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:58:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:58:36: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c799f710> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:58:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaaaea0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:58:37: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cda94590> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:58:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:38: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  95%|█████████▌| 82/86 [49:31<02:35, 38.95s/it]29-Sep-26 18:58:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:38: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:38: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 82/86 on attempt 1: 20200330/20:00:00 - 20200330/22:59:59

29-Sep-26 18:58:45: Remote index took 6.5 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:58:49: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033100_v04.06.cdf
29-Sep-26 18:58:50: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:58:50: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:58:50: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaa9c10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:58:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:50: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  97%|█████████▋| 83/86 [49:43<01:32, 30.89s/it]29-Sep-26 18:58:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:50: del_data: No valid tplot variables found, returning
29-Sep-26 18:58:50: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 83/86 on attempt 1: 20200331/00:00:00 - 20200331/00:59:59

29-Sep-26 18:59:12: Retrying (LoggingRetry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='ergsc.isee.nagoya-u.ac.jp', port=443): Read timed out. (read timeout=20)")': /data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 18:59:16: Remote index took 25.7 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 18:59:17: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033107_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033107_v04.06.cdf
29-Sep-26 18:59:18: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033107_v04.06.cdf complete, 4.983 MB in 0.3 sec (16.176 MB/sec) (transfer_normal)
29-Sep-26 18:59:19: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033108_v04.06.cdf
29-Sep-26 18:59:19: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:59:19: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:59:19: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf03ed80> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:20: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d075b20> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:21: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  98%|█████████▊| 84/86 [50:13<01:01, 30.70s/it]29-Sep-26 18:59:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:21: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:21: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 84/86 on attempt 1: 20200331/07:00:00 - 20200331/08:59:59

29-Sep-26 18:59:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033110_v04.06.cdf
29-Sep-26 18:59:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:59:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:59:23: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cf0de270> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:23: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4:  99%|█████████▉| 85/86 [50:16<00:22, 22.27s/it]29-Sep-26 18:59:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:23: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:23: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 85/86 on attempt 1: 20200331/10:00:00 - 20200331/10:59:59

29-Sep-26 18:59:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033113_v04.06.cdf
29-Sep-26 18:59:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033114_v04.06.cdf
29-Sep-26 18:59:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033115_v04.06.cdf
29-Sep-26 18:59:30: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033116_v04.06.cdf
29-Sep-26 18:59:32: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020033117_v04.06.cdf
29-Sep-26 18:59:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 18:59:32: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 18:59:32: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cf1c2f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:32: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb29f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c5b462a0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c79716d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:33: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdaab800> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 18:59:36: del_data: No valid tplot variables found, returning
29-Sep-26 18:59:36: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 1/4: 100%|██████████| 86/86 [50:28<00:00, 35.22s/it]

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 86/86 on attempt 1: 20200331/13:00:00 - 20200331/17:59:59
waiting 30 s before MGF attempt 2/4 for 3 block(s)

Loading MGF blocks attempt 2/4:   0%|          | 0/3 [00:00<?, ?it/s]29-Sep-26 19:00:06: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:06: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:06: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/
29-Sep-26 19:00:08: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030100_v04.06.cdf
29-Sep-26 19:00:10: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030101_v04.06.cdf
29-Sep-26 19:00:11: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030102_v04.06.cdf
29-Sep-26 19:00:12: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:00:12: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 19:00:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb3410> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cee57ad0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:12: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78cfb29f0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:14: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:14: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 2/4:  33%|███▎      | 1/3 [00:07<00:15,  7.94s/it]29-Sep-26 19:00:14: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:14: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:14: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 1/86 on attempt 2: 20200301/00:00:00 - 20200301/02:59:59

29-Sep-26 19:00:19: Remote index took 5.8 seconds to return, may indicate problems on remote server (index_slow)
29-Sep-26 19:00:21: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030409_v04.06.cdf
29-Sep-26 19:00:22: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030410_v04.06.cdf
29-Sep-26 19:00:23: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030411_v04.06.cdf
29-Sep-26 19:00:25: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030412_v04.06.cdf
29-Sep-26 19:00:26: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030413_v04.06.cdf
29-Sep-26 19:00:27: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030414_v04.06.cdf
29-Sep-26 19:00:29: File is current: /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020030415_v04.06.cdf
29-Sep-26 19:00:29: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:00:29: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 19:00:29: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c7144830> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:29: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c79675c0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:29: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6ceff4350> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac5250> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6cdac6e40> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c799df10> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:30: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb6c5aed3d0> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:34: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:34: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 2/4:  67%|██████▋   | 2/3 [00:28<00:15, 15.12s/it]29-Sep-26 19:00:34: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:34: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:34: Downloading remote index: https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 9/86 on attempt 2: 20200304/09:00:00 - 20200304/15:59:59

29-Sep-26 19:00:37: Downloading https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032215_v04.06.cdf to /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032215_v04.06.cdf
29-Sep-26 19:00:37: Download of /mnt/j/observation_data//ergsc/satellite/erg/mgf/l2/64hz/2020/03/erg_mgf_l2_64hz_dsi_2020032215_v04.06.cdf complete, 4.763 MB in 0.7 sec (7.235 MB/sec) (transfer_normal)
29-Sep-26 19:00:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:00:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

29-Sep-26 19:00:38: Variable erg_mgf_l2_date_time_64hz in file <cdflib.cdfread.CDF object at 0x7bb78d291550> has non-homogeneous unit values ['    yr', '    mo', '     d', '     h', '   min', '     s', '    ms', 'micros', '    ns']
29-Sep-26 19:00:38: del_data: No valid tplot variables found, returning
29-Sep-26 19:00:38: del_data: No valid tplot variables found, returning
Loading MGF blocks attempt 2/4: 100%|██████████| 3/3 [00:32<00:00, 10.86s/it]

**************************************************************************
['Exploration of Energization and Radiation in Geospace (ERG) Magnetic Field Experiment (MGF) Level 2 64 Hz resolution magnetic field data']

Information about ERG MGF

PI:  ['Ayako Matsuoka']
Affiliation:  ['Data Analysis Center for Geomagnetism and Space Magnetism, Graduate School of Science, Kyoto University, Kitashirakawa-Oiwake Cho, Sakyo-ku Kyoto 606-8502, Japan']

RoR of ERG project common: https://ergsc.isee.nagoya-u.ac.jp/data_info/rules_of_the_road.shtml.en
RoR of MGF L2: https://ergsc.isee.nagoya-u.ac.jp/mw/index.php/ErgSat/Mgf
Contact: erg_mgf_info at isee.nagoya-u.ac.jp
**************************************************************************
loaded MGF block 60/86 on attempt 2: 20200322/15:00:00 - 20200322/15:59:59

<xarray.DataArray 'erg_mgf_l2_mag_64hz_dsi' (time: 30771667, v_dim: 3)> Size: 369MB
array([[-58.004704, 122.960205, 100.919   ],
       [-57.911007, 122.930435, 100.942   ],
       [-57.961708, 122.88609 , 101.102   ],
       ...,
       [165.27937 ,  49.025715,  72.456   ],
       [165.31932 ,  48.90287 ,  72.459   ],
       [165.23415 ,  48.957096,  72.481   ]],
      shape=(30771667, 3), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 246MB 2020-03-01T00:07:35.061597696 ... 20...
Dimensions without coordinates: v_dim
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'B in DSI', 'CATDESC': 'B in DSI coo...
    data_att:      {'coord_sys': '', 'units': 'nT', 'depend_1_units': 'nT', '...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...
<xarray.DataArray 'erg_mgf_l2_quality_64hz' (time: 30771667, v_dim: 16)> Size: 2GB
array([[0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       ...,
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.]], shape=(30771667, 16), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 246MB 2020-03-01T00:07:35.061597696 ... 20...
Dimensions without coordinates: v_dim
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'Quality Flag', 'CATDESC': 'Quality ...
    data_att:      {'coord_sys': '', 'units': 'None', 'depend_1_units': None,...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...
MGF block status:
status
success    86
MGF blocks recovered by retry: 3

In [28]:
qf_B, B64 = xr.align(B64_data_dsi_quality_flag[:, 3], B64_data_dsi, join="inner")

B64_data_dsi_qf = xr.where(qf_B <= 21, B64, np.nan)

print(B64_data_dsi_qf)

<xarray.DataArray 'erg_mgf_l2_quality_64hz' (time: 30771667, v_dim: 3)> Size: 369MB
array([[-58.004704, 122.960205, 100.919   ],
       [-57.911007, 122.930435, 100.942   ],
       [-57.961708, 122.88609 , 101.102   ],
       ...,
       [165.27937 ,  49.025715,  72.456   ],
       [165.31932 ,  48.90287 ,  72.459   ],
       [165.23415 ,  48.957096,  72.481   ]],
      shape=(30771667, 3), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 246MB 2020-03-01T00:07:35.061597696 ... 20...
Dimensions without coordinates: v_dim
Attributes:
    CDF:           {'VATT': {'FIELDNAM': 'B in DSI', 'CATDESC': 'B in DSI coo...
    data_att:      {'coord_sys': '', 'units': 'nT', 'depend_1_units': 'nT', '...
    plot_options:  {'xaxis_opt': {'axis_label': '', 'crosshair': 'X', 'x_axis...

In [29]:
B64_data_dsi_qf_total = np.sqrt(xr.dot(B64_data_dsi_qf, B64_data_dsi_qf, dim='v_dim'))

In [30]:
m_e     = 9.1093837E-31    #[kg]
m_H     = 1.6726219e-27  # kg
m_He    = m_H * 4.
m_O     = m_H * 16.
elementary_charge = 1.60217663E-19  #[A s]

f_cH    = elementary_charge * B64_data_dsi_qf_total*1E-9 / m_H  / 2. / np.pi
f_cHe   = elementary_charge * B64_data_dsi_qf_total*1E-9 / m_He / 2. / np.pi
f_cO    = elementary_charge * B64_data_dsi_qf_total*1E-9 / m_O / 2. / np.pi

In [ ]:
#from pathlib import Path
#import numpy as np
#import pandas as pd
#from matplotlib.colors import Normalize
#import matplotlib.pyplot as plt
#import matplotlib.dates as mdates
#
#path_base_save_plot = f'/mnt/j/statistical_analysis_arase/preanalysis'
#path_base_save_plot = Path(path_base_save_plot + f'/PWE-EFD_spec')
#os.makedirs(path_base_save_plot, exist_ok=True)
#
#def edges_numeric(arr):
#    arr = np.asarray(arr, dtype=float)
#    if arr.size < 2:
#        return np.concatenate((arr, arr + 1.0))
#    d = np.diff(arr) / 2.0
#    return np.concatenate(([arr[0] - d[0]], arr[:-1] + d, [arr[-1] + d[-1]]))
#
#vmax = np.log10(1E1)
#vmin = np.log10(1e-4)
#
#for idx, row in merged_ranges_df.iterrows():
#    start = row["start_time"]
#    end = row["end_time"]
#
#    if pd.isna(start) or pd.isna(end):
#        continue
#
#    subset_range = efd_spectra_qf.sel(time=slice(start, end))
#
#    if subset_range.sizes.get("time", 0) < 2:
#        continue
#
#    times = pd.to_datetime(subset_range.time.values)
#
#    if "spec_bins" in subset_range.coords:
#        freqs = subset_range["spec_bins"].values
#    elif "v" in subset_range.coords:
#        freqs = subset_range["v"].values
#    else:
#        freqs = np.arange(subset_range.sizes["v_dim"])
#
#    data_range = subset_range.values
#    data_range = np.where(
#        np.isfinite(data_range) & (data_range > 0),
#        data_range,
#        np.nan
#    )
#
#    logdata_range = np.log10(data_range)
#
#    if np.isnan(logdata_range).all():
#        continue
#
#    t_num = mdates.date2num(times.to_pydatetime())
#    t_edges = edges_numeric(t_num)
#    f_edges = edges_numeric(freqs)
#
#    fig_i, ax_i = plt.subplots(figsize=(12, 4.5))
#
#    pcm_i = ax_i.pcolormesh(
#        t_edges,
#        f_edges,
#        logdata_range.T,
#        shading="auto",
#        cmap="turbo",
#        norm=Normalize(vmin=vmin, vmax=vmax),
#    )
#
#    f_cH_plot = f_cH.sel(time=slice(start, end))
#    f_cHe_plot = f_cHe.sel(time=slice(start, end))
#    f_cO_plot = f_cO.sel(time=slice(start, end))
#
#    ax_i.plot(f_cH_plot.time, f_cH_plot.data, lw=1, c='white', linestyle='solid')
#    ax_i.plot(f_cHe_plot.time, f_cHe_plot.data, lw=1, c='magenta', linestyle='solid')
#    ax_i.plot(f_cO_plot.time, f_cO_plot.data, lw=1, c='yellow', linestyle='solid')
#
#    ax_i.set_xlabel("Time")
#    ax_i.xaxis_date()
#    ax_i.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
#    ax_i.set_ylabel("Frequency [Hz]")
#    ax_i.set_title(
#        f"PWE-EFD spec ({start:%Y-%m-%d %H:%M:%S} - {end:%Y-%m-%d %H:%M:%S})"
#    )
#    ax_i.set_yscale("log")
#    ax_i.set_ylim(3, 32)
#    ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())
#
#    fig_i.colorbar(pcm_i, ax=ax_i, label=r"log10 PSD [$\mathrm{(mV/m)}^2/\mathrm{Hz}$]")
#    plt.tight_layout()
#
#    # =========================
#    # save figure
#    # =========================
#
#    # start の月・日で階層フォルダを作る
#    save_dir = path_base_save_plot / f"{start:%Y}" / f"{start:%m}"
#    save_dir.mkdir(parents=True, exist_ok=True)
#
#    filename = (
#        f"efd_spectra_qf_"
#        f"{start:%Y%m%d_%H%M%S}_to_{end:%Y%m%d_%H%M%S}.png"
#    )
#
#    save_path = save_dir / filename
#
#    fig_i.savefig(save_path, dpi=200, bbox_inches="tight")
#    plt.close(fig_i)
#
#    print(f"saved: {save_path}")

29-Sep-26 19:01:30: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_000737_to_20200301_005027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_005626_to_20200301_014114.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_014443_to_20200301_015200.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_022432_to_20200301_023318.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_062856_to_20200301_064548.png

29-Sep-26 19:01:35: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_070508_to_20200301_072514.png

29-Sep-26 19:01:36: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_073559_to_20200301_075930.png

29-Sep-26 19:01:37: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_081634_to_20200301_083659.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_083923_to_20200301_084804.png

29-Sep-26 19:01:38: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_084928_to_20200301_085626.png

29-Sep-26 19:01:39: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_085744_to_20200301_092043.png

29-Sep-26 19:01:40: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_092355_to_20200301_101506.png

29-Sep-26 19:01:41: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_101730_to_20200301_114725.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_120829_to_20200301_121844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_145828_to_20200301_150515.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_150741_to_20200301_152007.png

29-Sep-26 19:01:43: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_161957_to_20200301_162938.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200301_164829_to_20200301_165837.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_012657_to_20200303_013339.png

29-Sep-26 19:01:45: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_053333_to_20200303_054508.png

29-Sep-26 19:01:46: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_064439_to_20200303_074949.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_080829_to_20200303_085303.png

29-Sep-26 19:01:47: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_085303_to_20200303_101033.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_110413_to_20200303_112004.png

29-Sep-26 19:01:49: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_144029_to_20200303_151034.png

29-Sep-26 19:01:50: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_171520_to_20200303_174946.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_175642_to_20200303_185359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_190534_to_20200303_191227.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_191658_to_20200303_192443.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_192551_to_20200303_193741.png

29-Sep-26 19:01:53: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200303_203034_to_20200303_204108.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_040830_to_20200304_043602.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_044504_to_20200304_045624.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_045941_to_20200304_051752.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_052113_to_20200304_053208.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_090604_to_20200304_091247.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_100817_to_20200304_101748.png

29-Sep-26 19:01:57: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_102420_to_20200304_104602.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_104856_to_20200304_115930.png

29-Sep-26 19:01:58: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_120829_to_20200304_152234.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_152252_to_20200304_154627.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200304_214639_to_20200304_215414.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_002125_to_20200305_003019.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_053058_to_20200305_055624.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_055920_to_20200305_060654.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_061147_to_20200305_061829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_062158_to_20200305_062841.png

29-Sep-26 19:02:03: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_063642_to_20200305_064746.png

29-Sep-26 19:02:04: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_065443_to_20200305_070509.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_070645_to_20200305_071559.png

29-Sep-26 19:02:05: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_071753_to_20200305_072833.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_080829_to_20200305_090740.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_090946_to_20200305_093003.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_093827_to_20200305_095536.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200305_095811_to_20200305_100535.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_001717_to_20200306_002359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_002910_to_20200306_003552.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_093353_to_20200306_094755.png

29-Sep-26 19:02:10: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_094946_to_20200306_100403.png

29-Sep-26 19:02:11: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_100450_to_20200306_101625.png

29-Sep-26 19:02:11: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_101737_to_20200306_104529.png

29-Sep-26 19:02:12: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_104714_to_20200306_105457.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_120829_to_20200306_134654.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_135252_to_20200306_141119.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_141222_to_20200306_145141.png

29-Sep-26 19:02:15: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200306_145704_to_20200306_151602.png

29-Sep-26 19:02:16: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_053301_to_20200307_060617.png

29-Sep-26 19:02:17: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_060729_to_20200307_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_080829_to_20200307_093632.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_094846_to_20200307_095649.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_131058_to_20200307_132256.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_132630_to_20200307_133406.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200307_133458_to_20200307_134140.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_041848_to_20200308_043302.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_081504_to_20200308_082306.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_090728_to_20200308_091410.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_092924_to_20200308_093954.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_094356_to_20200308_101035.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_101118_to_20200308_103516.png

29-Sep-26 19:02:25: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_103917_to_20200308_114142.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_114236_to_20200308_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_121331_to_20200308_122013.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_123251_to_20200308_135503.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_140433_to_20200308_141342.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_190437_to_20200308_191710.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_202219_to_20200308_203553.png

29-Sep-26 19:02:30: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_204419_to_20200308_212930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_213740_to_20200308_215016.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200308_224921_to_20200308_231522.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_042422_to_20200309_045621.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_050048_to_20200309_052249.png

29-Sep-26 19:02:33: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_052411_to_20200309_054404.png

29-Sep-26 19:02:34: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_061300_to_20200309_065052.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_065300_to_20200309_070753.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_071828_to_20200309_072511.png

29-Sep-26 19:02:36: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_072707_to_20200309_074358.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_074811_to_20200309_075930.png

29-Sep-26 19:02:37: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_083745_to_20200309_085431.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_181103_to_20200309_182838.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200309_182958_to_20200309_185226.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_001053_to_20200310_002328.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_002509_to_20200310_003355.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_004801_to_20200310_005447.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_020703_to_20200310_021345.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_022055_to_20200310_023045.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_024118_to_20200310_024814.png

29-Sep-26 19:02:43: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_064049_to_20200310_064811.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_065415_to_20200310_072115.png

29-Sep-26 19:02:44: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_080901_to_20200310_082822.png

29-Sep-26 19:02:45: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_085258_to_20200310_092526.png

29-Sep-26 19:02:46: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_092646_to_20200310_094335.png

29-Sep-26 19:02:47: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_105654_to_20200310_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_120829_to_20200310_125910.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_125927_to_20200310_131036.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_132746_to_20200310_133754.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_133754_to_20200310_135821.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200310_171309_to_20200310_172123.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200311_123216_to_20200311_124141.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200311_124731_to_20200311_125438.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200311_152640_to_20200311_153627.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200311_172346_to_20200311_173825.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200311_174013_to_20200311_175023.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_064035_to_20200312_071539.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_072752_to_20200312_073434.png

29-Sep-26 19:02:55: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_073751_to_20200312_074441.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_080829_to_20200312_083616.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_084200_to_20200312_084958.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_085649_to_20200312_090344.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_090522_to_20200312_091205.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_091752_to_20200312_093827.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_094630_to_20200312_103106.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_104257_to_20200312_105954.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_110557_to_20200312_111239.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_122001_to_20200312_123848.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_192117_to_20200312_192759.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_193158_to_20200312_194225.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_200221_to_20200312_200903.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_200948_to_20200312_201710.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_203635_to_20200312_204347.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_213329_to_20200312_214021.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200312_214407_to_20200312_215516.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_025712_to_20200313_032114.png

29-Sep-26 19:03:07: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_032408_to_20200313_033246.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_034255_to_20200313_035930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_041029_to_20200313_041844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_042204_to_20200313_043127.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_044846_to_20200313_045528.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_061428_to_20200313_062159.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_065419_to_20200313_071942.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_102344_to_20200313_104210.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_105646_to_20200313_112944.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_114320_to_20200313_115006.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_152117_to_20200313_152800.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_161919_to_20200313_163113.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200313_163202_to_20200313_165905.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200314_095346_to_20200314_100032.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200314_100343_to_20200314_110844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200314_111230_to_20200314_111912.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200314_113055_to_20200314_114454.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_061657_to_20200315_062340.png

29-Sep-26 19:03:18: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_063613_to_20200315_064255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_132514_to_20200315_134139.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_134245_to_20200315_140944.png

29-Sep-26 19:03:20: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_141952_to_20200315_143528.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_154645_to_20200315_155930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_162237_to_20200315_162920.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_223136_to_20200315_223902.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_224241_to_20200315_225214.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_225216_to_20200315_231820.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_232323_to_20200315_233241.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200315_233331_to_20200315_235349.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_003420_to_20200316_010156.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_060852_to_20200316_062735.png

29-Sep-26 19:03:26: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_072345_to_20200316_074407.png

29-Sep-26 19:03:27: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_074519_to_20200316_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_080829_to_20200316_093120.png

29-Sep-26 19:03:28: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_093654_to_20200316_095006.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_101049_to_20200316_101841.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_104231_to_20200316_110255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_143537_to_20200316_144306.png

29-Sep-26 19:03:31: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_144436_to_20200316_145806.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200316_202845_to_20200316_203806.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_035106_to_20200317_035753.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_090823_to_20200317_091733.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_093243_to_20200317_095343.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_095843_to_20200317_101653.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_102451_to_20200317_105442.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_105810_to_20200317_110920.png

29-Sep-26 19:03:36: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_111311_to_20200317_113026.png

29-Sep-26 19:03:36: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_113102_to_20200317_115930.png

29-Sep-26 19:03:37: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_120829_to_20200317_130233.png

29-Sep-26 19:03:38: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_133820_to_20200317_135116.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_140756_to_20200317_142229.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_142244_to_20200317_150140.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_150141_to_20200317_152450.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_154036_to_20200317_155353.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_213956_to_20200317_214638.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_215118_to_20200317_215824.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_215828_to_20200317_223643.png

29-Sep-26 19:03:43: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_231154_to_20200317_234131.png

29-Sep-26 19:03:44: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200317_234332_to_20200317_235930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_040830_to_20200318_041629.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_042810_to_20200318_043516.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_063546_to_20200318_064812.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_070459_to_20200318_071408.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_071734_to_20200318_072626.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_072751_to_20200318_073917.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_091026_to_20200318_091709.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_101722_to_20200318_102503.png

29-Sep-26 19:03:50: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_102703_to_20200318_103751.png

29-Sep-26 19:03:51: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_170320_to_20200318_175508.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_180237_to_20200318_184921.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_190855_to_20200318_191656.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200318_195243_to_20200318_200631.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_004508_to_20200319_014640.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_014718_to_20200319_015400.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_022632_to_20200319_023513.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_050453_to_20200319_052626.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_081810_to_20200319_082940.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_083040_to_20200319_090254.png

29-Sep-26 19:03:58: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

29-Sep-26 19:03:59: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_091524_to_20200319_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_120829_to_20200319_134812.png

29-Sep-26 19:04:01: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_135013_to_20200319_135658.png

29-Sep-26 19:04:02: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_141007_to_20200319_142303.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_142608_to_20200319_151542.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_175100_to_20200319_180321.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_190947_to_20200319_192112.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_193259_to_20200319_193941.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_201534_to_20200319_202411.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_204429_to_20200319_210051.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_210350_to_20200319_211032.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_212102_to_20200319_212835.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_213902_to_20200319_215821.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_220929_to_20200319_222028.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200319_235052_to_20200319_235735.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_144437_to_20200320_145249.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_145758_to_20200320_150619.png

29-Sep-26 19:04:11: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_151226_to_20200320_152229.png

29-Sep-26 19:04:12: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_152627_to_20200320_160008.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_160737_to_20200320_173713.png

29-Sep-26 19:04:13: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_173814_to_20200320_175657.png

29-Sep-26 19:04:14: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_175802_to_20200320_184309.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_184309_to_20200320_190644.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_190714_to_20200320_191356.png

29-Sep-26 19:04:16: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200320_192623_to_20200320_194103.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_080829_to_20200321_084332.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_090431_to_20200321_093117.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_093503_to_20200321_101215.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_101255_to_20200321_105440.png

29-Sep-26 19:04:19: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_105855_to_20200321_110537.png

29-Sep-26 19:04:20: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_111347_to_20200321_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_120829_to_20200321_123640.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_123643_to_20200321_133047.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_133047_to_20200321_140120.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_140928_to_20200321_142554.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_142648_to_20200321_143336.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_181844_to_20200321_185945.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_222439_to_20200321_223255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200321_223835_to_20200321_224517.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_024516_to_20200322_030614.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_033456_to_20200322_034347.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_053937_to_20200322_054620.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_060230_to_20200322_064920.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_071726_to_20200322_072408.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_083148_to_20200322_083944.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_155137_to_20200322_155933.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_174044_to_20200322_174924.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_175720_to_20200322_180457.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_181223_to_20200322_182359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_220956_to_20200322_222023.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200322_223512_to_20200322_224155.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_004821_to_20200323_014348.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_014928_to_20200323_020722.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_023054_to_20200323_023736.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_032610_to_20200323_033609.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_033956_to_20200323_034811.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_063945_to_20200323_065823.png

29-Sep-26 19:04:37: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_071602_to_20200323_074707.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_075014_to_20200323_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_081157_to_20200323_081943.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_083004_to_20200323_083817.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_090012_to_20200323_091341.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_092917_to_20200323_093600.png

29-Sep-26 19:04:41: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_093933_to_20200323_094616.png

29-Sep-26 19:04:42: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_094840_to_20200323_103955.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_104531_to_20200323_113622.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_113713_to_20200323_115100.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_121743_to_20200323_130455.png

29-Sep-26 19:04:44: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_132513_to_20200323_134246.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_165051_to_20200323_170016.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_173507_to_20200323_175017.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_175146_to_20200323_180245.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_180402_to_20200323_181338.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_190911_to_20200323_191557.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_192935_to_20200323_193643.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_193734_to_20200323_194901.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_194919_to_20200323_201046.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_215312_to_20200323_215954.png

29-Sep-26 19:04:50: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200323_220901_to_20200323_221549.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_010847_to_20200325_020027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_022207_to_20200325_022849.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_023833_to_20200325_024515.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_025812_to_20200325_030455.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_061511_to_20200325_062153.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_062255_to_20200325_062937.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_070147_to_20200325_070829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_085404_to_20200325_090326.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_091710_to_20200325_092359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_092703_to_20200325_093902.png

29-Sep-26 19:04:57: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_094138_to_20200325_095403.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_101357_to_20200325_102346.png

29-Sep-26 19:04:58: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_103303_to_20200325_115824.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_120829_to_20200325_121832.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_122114_to_20200325_122756.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_211409_to_20200325_212051.png

29-Sep-26 19:05:01: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200325_212140_to_20200325_213755.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_120829_to_20200326_122601.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_122627_to_20200326_130955.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_144120_to_20200326_144813.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_145732_to_20200326_153317.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_154739_to_20200326_155708.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200326_163658_to_20200326_165330.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_091550_to_20200327_092232.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_092422_to_20200327_093108.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_094752_to_20200327_101456.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_102231_to_20200327_102925.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_102955_to_20200327_104338.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_111844_to_20200327_113727.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_154555_to_20200327_155239.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_172813_to_20200327_173455.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_175129_to_20200327_182844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_182925_to_20200327_183607.png

29-Sep-26 19:05:12: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_183753_to_20200327_184452.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_194932_to_20200327_200008.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200327_200756_to_20200327_202459.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_054055_to_20200328_055615.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_060352_to_20200328_061034.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_103623_to_20200328_111936.png

29-Sep-26 19:05:15: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_111942_to_20200328_112829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_120829_to_20200328_122423.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_122447_to_20200328_125614.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_125657_to_20200328_130443.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_131703_to_20200328_132919.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_151840_to_20200328_152522.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_162345_to_20200328_163157.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_223626_to_20200328_225923.png

29-Sep-26 19:05:20: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200328_230446_to_20200328_234450.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_000830_to_20200329_003214.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_043704_to_20200329_045053.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_064915_to_20200329_070208.png

29-Sep-26 19:05:22: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_070643_to_20200329_073201.png

29-Sep-26 19:05:23: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_073317_to_20200329_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_080829_to_20200329_085141.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_085635_to_20200329_090855.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_103250_to_20200329_104549.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200329_105555_to_20200329_111037.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_001308_to_20200330_002222.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_002428_to_20200330_003122.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_022609_to_20200330_023410.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_024340_to_20200330_025030.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_025623_to_20200330_030305.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_032244_to_20200330_033411.png

29-Sep-26 19:05:29: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_034154_to_20200330_034836.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_040830_to_20200330_042829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_043403_to_20200330_045232.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_045352_to_20200330_050348.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_054909_to_20200330_055632.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_091537_to_20200330_092256.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_092608_to_20200330_114428.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_114723_to_20200330_115556.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_120947_to_20200330_121633.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_122951_to_20200330_123635.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_123917_to_20200330_124820.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_131552_to_20200330_143726.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_144330_to_20200330_145028.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_151628_to_20200330_153231.png

29-Sep-26 19:05:40: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_153515_to_20200330_154740.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_200737_to_20200330_203039.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_203052_to_20200330_204128.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_204449_to_20200330_205907.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_210333_to_20200330_220110.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_221138_to_20200330_222816.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200330_224730_to_20200330_225559.png

29-Sep-26 19:05:45: /tmp/ipykernel_91668/2110806289.py:87: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_004030_to_20200331_005004.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_074521_to_20200331_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_080904_to_20200331_082305.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_083108_to_20200331_083828.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_102047_to_20200331_103344.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_135721_to_20200331_144027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_145412_to_20200331_150103.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_151114_to_20200331_151805.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_154256_to_20200331_155441.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_163241_to_20200331_165326.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec/2020/03/efd_spectra_qf_20200331_172652_to_20200331_173334.png

In [32]:
import numpy as np
import pandas as pd
import xarray as xr


def _estimate_sampling_rate_from_time(time_values):
    """
    datetime64 time coordinate から sampling rate を推定する。
    """
    time = pd.DatetimeIndex(pd.to_datetime(time_values))
    t_sec = (time - time[0]).total_seconds().to_numpy()

    dt_arr = np.diff(t_sec)
    dt_arr = dt_arr[np.isfinite(dt_arr) & (dt_arr > 0)]

    if len(dt_arr) == 0:
        raise ValueError("time 軸から dt を推定できない。")

    dt = np.median(dt_arr)
    fs = 1.0 / dt

    return fs, dt


def _one_sided_psd(x, fs, use_hann=True, remove_mean=True):
    """
    1D waveform から one-sided PSD を計算する。

    入力 x の単位が nT なら、出力 PSD は nT^2/Hz。
    """

    x = np.asarray(x, dtype=float)

    if np.any(~np.isfinite(x)):
        raise ValueError("x に NaN/Inf が含まれている。")

    if remove_mean:
        x = x - np.mean(x)

    N = len(x)

    if use_hann:
        window = np.hanning(N)
    else:
        window = np.ones(N)

    xw = x * window

    fft_vals = np.fft.rfft(xw)
    freq = np.fft.rfftfreq(N, d=1.0 / fs)

    psd = np.abs(fft_vals) ** 2 / (fs * np.sum(window ** 2))

    # one-sided correction
    if N % 2 == 0:
        # even N: DC と Nyquist 以外を2倍
        psd[1:-1] *= 2.0
    else:
        # odd N: DC 以外を2倍
        psd[1:] *= 2.0

    return freq, psd


def _bin_psd_to_1hz_bins(freq, psd, spec_bins=np.arange(3, 33), bin_width=1.0):
    """
    raw FFT PSD を 1 Hz ごとの spec_bins にまとめる。

    spec_bins は bin center として扱う。
    spec_bins=3 は 2.5--3.5 Hz の平均 PSD。
    spec_bins=32 は 31.5--32.5 Hz だが、Nyquist により実質 31.5--32 Hz。
    """

    freq = np.asarray(freq)
    psd = np.asarray(psd)

    out = np.full(len(spec_bins), np.nan)

    for i, fc in enumerate(spec_bins):
        f0 = fc - bin_width / 2.0
        f1 = fc + bin_width / 2.0

        if i == len(spec_bins) - 1:
            use = (freq >= f0) & (freq <= f1)
        else:
            use = (freq >= f0) & (freq < f1)

        if np.any(use):
            out[i] = np.nanmean(psd[use])

    return out

In [33]:
from concurrent.futures import ThreadPoolExecutor
from tqdm.auto import tqdm


def make_mgf64_spectra_like_efd(
    da_B,
    target_times=None,
    spec_bins=np.arange(3, 33),
    window_sec=1.0,
    step_sec=1.0,
    min_valid_fraction=1.0,
    gap_factor=1.5,
    use_hann=True,
    remove_mean=True,
    name="B64_spectra_qf",
    show_progress=True,
    n_workers=1,
):
    """
    MGF 64 Hz total magnetic field から EFD spec と同様の
    time x spec_bins スペクトルプロダクトを作る。

    Parameters
    ----------
    da_B : xr.DataArray
        time 軸を持つ 1D DataArray。
        単位は nT を想定。
        quality flag 不良点は NaN になっているものとする。
    target_times : array-like or None
        出力する spectrum の中心時刻。
        EFD と完全に同じ time grid にしたい場合は
        target_times=efd_spectra_qf.time.values
        とする。
        None の場合は step_sec ごとの時刻を自動生成する。
    spec_bins : array-like
        固定 frequency bins。デフォルトは 3--32 Hz。
    window_sec : float
        FFT 窓長。64 Hz sampling で 1秒なら df=1 Hz。
    step_sec : float
        target_times=None の場合の出力 cadence。
    min_valid_fraction : float
        各窓内で必要な有限値の割合。
        1.0 なら NaN が1点でもあれば、その窓は NaN spectrum。
    gap_factor : float
        窓内の time gap が通常 dt の gap_factor 倍を超えたら無効化。
    use_hann : bool
        Hann window を使うか。
    remove_mean : bool
        各窓で mean を除去するか。
    name : str
        出力 DataArray 名。
    show_progress : bool
        True の場合、FFT計算の進捗バーを表示する。
    n_workers : int
        1なら直列処理。2以上なら ThreadPoolExecutor で target_times を並列処理する。

    Returns
    -------
    spectra : xr.DataArray
        dims: time, spec_bins
        units: nT^2/Hz
    """

    da_B = da_B.sortby("time")

    time = pd.DatetimeIndex(pd.to_datetime(da_B.time.values))
    values = da_B.values.astype(float)
    spec_bins = np.asarray(spec_bins)

    fs, dt = _estimate_sampling_rate_from_time(time)

    nperseg = int(round(window_sec * fs))

    if nperseg < 2:
        raise ValueError("window_sec が短すぎる。")

    # 1秒窓、64 Hzなら nperseg = 64
    actual_window_sec = nperseg / fs
    df = fs / nperseg
    nyq = fs / 2.0

    print(f"Estimated fs        : {fs:.6f} Hz")
    print(f"Estimated dt        : {dt:.6f} sec")
    print(f"nperseg             : {nperseg}")
    print(f"actual window length: {actual_window_sec:.6f} sec")
    print(f"df                  : {df:.6f} Hz")
    print(f"Nyquist             : {nyq:.6f} Hz")
    print(f"target_times        : {0 if target_times is None else len(target_times)}")
    print(f"n_workers           : {n_workers}")

    if np.max(spec_bins) > nyq + 1e-6:
        print(
            f"Warning: spec_bins max = {np.max(spec_bins)} Hz exceeds Nyquist = {nyq:.3f} Hz"
        )

    half = nperseg // 2

    # target_times を作る
    if target_times is None:
        t0 = time[0] + pd.Timedelta(seconds=actual_window_sec / 2.0)
        t1 = time[-1] - pd.Timedelta(seconds=actual_window_sec / 2.0)

        target_times = pd.date_range(
            start=t0,
            end=t1,
            freq=pd.to_timedelta(step_sec, unit="s"),
        )
    else:
        target_times = pd.DatetimeIndex(pd.to_datetime(target_times))

    spectra = np.full((len(target_times), len(spec_bins)), np.nan)
    valid_fraction_arr = np.full(len(target_times), np.nan)
    n_valid_arr = np.full(len(target_times), 0)
    is_valid_window = np.full(len(target_times), False)

    time_ns = time.asi8

    def process_one(it):
        tc = target_times[it]
        tc_ns = pd.Timestamp(tc).value

        # 中心時刻に最も近い index
        ic = np.searchsorted(time_ns, tc_ns)

        # even nperseg の場合、中心の取り方は少し任意性がある。
        # ここでは ic を中心近傍として nperseg 点を取る。
        i0 = ic - half
        i1 = i0 + nperseg

        empty_spectrum = np.full(len(spec_bins), np.nan)

        if i0 < 0 or i1 > len(values):
            return it, empty_spectrum, np.nan, 0, False

        x = values[i0:i1]
        t_win = time[i0:i1]

        if len(x) != nperseg:
            return it, empty_spectrum, np.nan, 0, False

        # time gap check
        t_win_sec = (t_win - t_win[0]).total_seconds().to_numpy()
        dt_win = np.diff(t_win_sec)

        if len(dt_win) == 0:
            return it, empty_spectrum, np.nan, 0, False

        if np.nanmax(dt_win) > gap_factor * dt:
            return it, empty_spectrum, np.nan, 0, False

        finite = np.isfinite(x)
        valid_fraction = finite.sum() / len(x)
        n_valid = int(finite.sum())

        if valid_fraction < min_valid_fraction:
            return it, empty_spectrum, valid_fraction, n_valid, False

        # 今回は quality flag 不良点を補間しない方針。
        # min_valid_fraction=1.0 なら、ここに来る時点で NaN はない。
        if np.any(~finite):
            return it, empty_spectrum, valid_fraction, n_valid, False

        freq, psd = _one_sided_psd(
            x,
            fs=fs,
            use_hann=use_hann,
            remove_mean=remove_mean,
        )

        spectrum = _bin_psd_to_1hz_bins(
            freq=freq,
            psd=psd,
            spec_bins=spec_bins,
            bin_width=1.0,
        )

        return it, spectrum, valid_fraction, n_valid, True

    indices = range(len(target_times))

    if n_workers is None or n_workers <= 1:
        iterator = indices
        if show_progress:
            iterator = tqdm(iterator, total=len(target_times), desc="MGF FFT")

        for result in iterator:
            it, spectrum, valid_fraction, n_valid, ok = process_one(result)
            spectra[it, :] = spectrum
            valid_fraction_arr[it] = valid_fraction
            n_valid_arr[it] = n_valid
            is_valid_window[it] = ok
    else:
        with ThreadPoolExecutor(max_workers=int(n_workers)) as executor:
            iterator = executor.map(process_one, indices)
            if show_progress:
                iterator = tqdm(iterator, total=len(target_times), desc="MGF FFT")

            for it, spectrum, valid_fraction, n_valid, ok in iterator:
                spectra[it, :] = spectrum
                valid_fraction_arr[it] = valid_fraction
                n_valid_arr[it] = n_valid
                is_valid_window[it] = ok

    spectra_da = xr.DataArray(
        spectra,
        coords={
            "time": target_times,
            "spec_bins": spec_bins,
            "valid_fraction": ("time", valid_fraction_arr),
            "n_valid": ("time", n_valid_arr),
            "is_valid_window": ("time", is_valid_window),
        },
        dims=("time", "spec_bins"),
        name=name,
        attrs={
            "units": "nT^2/Hz",
            "input_units": "nT",
            "method": "sliding-window one-sided FFT PSD",
            "window": "hann" if use_hann else "boxcar",
            "remove_mean": bool(remove_mean),
            "sampling_rate_Hz": float(fs),
            "dt_sec": float(dt),
            "nperseg": int(nperseg),
            "window_sec": float(actual_window_sec),
            "df_Hz": float(df),
            "nyquist_Hz": float(nyq),
            "spec_bins": "frequency bin centers [Hz]",
            "bin_width_Hz": 1.0,
            "min_valid_fraction": float(min_valid_fraction),
            "n_workers": int(n_workers) if n_workers is not None else 1,
            "quality_flag_handling": "NaN samples are not interpolated; windows with insufficient valid samples are set to NaN.",
        },
    )

    return spectra_da

In [34]:
from pathlib import Path
import hashlib
import pandas as pd
import numpy as np
import xarray as xr


def make_times_in_ranges(time_values, ranges_df):
    """
    time_values のうち、ranges_df の start_time/end_time に含まれるものだけ返す。
    """

    times = pd.DatetimeIndex(pd.to_datetime(time_values))

    if ranges_df is None or len(ranges_df) == 0:
        return times.values

    use = make_mask_in_padded_ranges(
        times,
        ranges_df,
        pad=pd.Timedelta(0),
    )
    return times[use].values


def make_ranges_signature(ranges_df):
    """全イベント区間から再現可能な短いcache署名を作る。"""
    if ranges_df is None or len(ranges_df) == 0:
        return "empty"

    ranges = ranges_df.dropna(subset=["start_time", "end_time"]).copy()
    ranges["start_time"] = pd.to_datetime(ranges["start_time"])
    ranges["end_time"] = pd.to_datetime(ranges["end_time"])
    ranges = ranges.sort_values(["start_time", "end_time"])

    payload = "\n".join(
        f"{start.value}:{end.value}"
        for start, end in zip(ranges["start_time"], ranges["end_time"])
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]


def make_b64_spectra_save_path(
    ranges_df,
    time_range,
    ranges_signature,
    base_dir=Path("/mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/B64_spectra"),
):
    """
    区間構成と解析時間幅を含む B64_spectra_qf の保存パスを作る。
    """

    base_dir = Path(base_dir)
    base_dir.mkdir(parents=True, exist_ok=True)

    if ranges_df is not None and len(ranges_df) > 0:
        t0 = pd.to_datetime(ranges_df["start_time"].min())
        t1 = pd.to_datetime(ranges_df["end_time"].max())
    else:
        t0 = pd.to_datetime(time_range[0])
        t1 = pd.to_datetime(time_range[-1])

    half_width_sec = int(EVENT_HALF_WIDTH.total_seconds())
    min_duration_sec = int(MIN_EVENT_DURATION.total_seconds())

    filename = (
        f"B64_spectra_qf_valid_ranges_"
        f"{t0:%Y%m%d_%H%M%S}_to_{t1:%Y%m%d_%H%M%S}_"
        f"r{ranges_signature}_hw{half_width_sec}s_min{min_duration_sec}s.nc"
    )

    return base_dir / filename


mgf_target_times = make_times_in_ranges(
    efd_spectra_qf.time.values,
    merged_ranges_df,
)

B64_ranges_signature = make_ranges_signature(merged_ranges_df)
B64_spectra_save_path = make_b64_spectra_save_path(
    merged_ranges_df,
    time_range,
    ranges_signature=B64_ranges_signature,
)

print(f"EFD time grid 全体: {efd_spectra_qf.sizes.get('time', 0)}")
print(f"MGF FFT target_times: {len(mgf_target_times)}")
print(f"B64 ranges signature: {B64_ranges_signature}")
print(f"B64 spectra save path: {B64_spectra_save_path}")

EFD time grid 全体: 2637793
MGF FFT target_times: 478971
B64 ranges signature: d9661a427768
B64 spectra save path: /mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/B64_spectra/B64_spectra_qf_valid_ranges_20200301_000737_to_20200331_173334_rd9661a427768_hw200s_min400s.nc

In [35]:
# ============================================================
# Load cached B64_spectra_qf if available; otherwise compute and save.
# ============================================================

import os

force_recompute_B64_spectra = False
MGF_FFT_N_WORKERS = max(1, min(16, os.cpu_count() or 1))

if B64_spectra_save_path.exists() and not force_recompute_B64_spectra:
    ds_loaded = xr.open_dataset(B64_spectra_save_path)
    B64_spectra_qf = ds_loaded["B64_spectra_qf"]
    print(f"loaded cached B64_spectra_qf: {B64_spectra_save_path}")

else:
    if len(mgf_target_times) == 0:
        raise ValueError("mgf_target_times が空です。merged_ranges_df または efd_spectra_qf を確認してください。")

    print(f"MGF FFT workers: {MGF_FFT_N_WORKERS}")
    B64_spectra_qf = make_mgf64_spectra_like_efd(
        B64_data_dsi_qf_total,
        target_times=mgf_target_times,
        spec_bins=np.arange(3, 33),
        window_sec=1.0,
        min_valid_fraction=1.0,
        use_hann=True,
        remove_mean=True,
        show_progress=True,
        n_workers=MGF_FFT_N_WORKERS,
    )

    B64_spectra_qf.attrs.update({
        "long_name": "MGF 64 Hz total magnetic field spectrum",
        "units": "nT^2/Hz",
        "input_data": "B64_data_dsi_qf_total",
        "quality_flag": "Bad-quality samples were set to NaN before FFT.",
        "frequency_bins": "1 Hz bins from 3 to 32 Hz",
        "analysis_ranges": "Only merged_ranges_df intervals were loaded and transformed.",
        "ranges_signature": B64_ranges_signature,
        "event_half_width_sec": float(EVENT_HALF_WIDTH.total_seconds()),
        "minimum_event_duration_sec": float(MIN_EVENT_DURATION.total_seconds()),
        "mgf_load_pad_sec": float(MGF_LOAD_PAD.total_seconds()),
        "mgf_max_block_hours": int(MGF_MAX_BLOCK_HOURS),
        "fft_n_workers": int(MGF_FFT_N_WORKERS),
    })

    ds_B64_spectra_qf = B64_spectra_qf.to_dataset(name="B64_spectra_qf")

    # NetCDFで扱いやすい属性に整える。
    for key, val in list(ds_B64_spectra_qf.attrs.items()):
        if isinstance(val, (bool, np.bool_)):
            ds_B64_spectra_qf.attrs[key] = str(val)

    for var in ds_B64_spectra_qf.variables:
        for key, val in list(ds_B64_spectra_qf[var].attrs.items()):
            if isinstance(val, (bool, np.bool_)):
                ds_B64_spectra_qf[var].attrs[key] = str(val)

    ds_B64_spectra_qf.to_netcdf(B64_spectra_save_path)
    print(f"computed and saved B64_spectra_qf: {B64_spectra_save_path}")

print(B64_spectra_qf)

MGF FFT workers: 16
Estimated fs        : 64.102038 Hz
Estimated dt        : 0.015600 sec
nperseg             : 64
actual window length: 0.998408 sec
df                  : 1.001594 Hz
Nyquist             : 32.051019 Hz
target_times        : 478971
n_workers           : 16

MGF FFT: 100%|██████████| 478971/478971 [07:12<00:00, 1107.35it/s]
29-Sep-26 19:14:40: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/xarray/backends/netCDF4_.py:96: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  data[key] = value

computed and saved B64_spectra_qf: /mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/B64_spectra/B64_spectra_qf_valid_ranges_20200301_000737_to_20200331_173334_rd9661a427768_hw200s_min400s.nc
<xarray.DataArray 'B64_spectra_qf' (time: 478971, spec_bins: 30)> Size: 115MB
array([[1.02573698e-04, 1.82276406e-04, 1.20417648e-04, ...,
        5.12143166e-05, 2.71707885e-05, 3.54033250e-06],
       [2.28775735e-04, 2.70987763e-04, 6.37295172e-06, ...,
        5.75659900e-05, 2.88674560e-04, 2.83954790e-04],
       [1.36801117e-03, 8.15005589e-04, 5.02393818e-04, ...,
        6.83274170e-05, 5.30292179e-05, 3.41583080e-05],
       ...,
       [8.02010652e-04, 2.78239009e-04, 2.43119511e-04, ...,
        6.37377360e-06, 6.20803547e-05, 3.18275753e-05],
       [5.94600513e-05, 1.70283867e-04, 1.33510471e-04, ...,
        1.79721815e-04, 2.00841884e-04, 1.09915662e-04],
       [1.54869254e-04, 1.78376074e-04, 3.97355536e-05, ...,
        1.14355603e-05, 3.35184107e-04, 4.78784825e-04]],
      shape=(478971, 30))
Coordinates:
  * time             (time) datetime64[ns] 4MB 2020-03-01T00:07:38.057405 ......
    valid_fraction   (time) float64 4MB 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0
    n_valid          (time) int64 4MB 64 64 64 64 64 64 64 ... 64 64 64 64 64 64
    is_valid_window  (time) bool 479kB True True True True ... True True True
  * spec_bins        (spec_bins) int64 240B 3 4 5 6 7 8 9 ... 27 28 29 30 31 32
Attributes: (12/27)
    units:                       nT^2/Hz
    input_units:                 nT
    method:                      sliding-window one-sided FFT PSD
    window:                      hann
    remove_mean:                 True
    sampling_rate_Hz:            64.10203820735934
    ...                          ...
    ranges_signature:            d9661a427768
    event_half_width_sec:        200.0
    minimum_event_duration_sec:  400.0
    mgf_load_pad_sec:            2.0
    mgf_max_block_hours:         24
    fft_n_workers:               16

In [36]:
# 確認用: B64_spectra_qf の時間範囲と有効窓数
if B64_spectra_qf.sizes.get("time", 0) > 0:
    print(f"B64_spectra_qf time start: {pd.to_datetime(B64_spectra_qf.time.values[0])}")
    print(f"B64_spectra_qf time end  : {pd.to_datetime(B64_spectra_qf.time.values[-1])}")
    if "is_valid_window" in B64_spectra_qf.coords:
        print(f"valid FFT windows: {int(B64_spectra_qf.is_valid_window.sum().values)}")
else:
    print("B64_spectra_qf is empty")

B64_spectra_qf time start: 2020-03-01 00:07:38.057405
B64_spectra_qf time end  : 2020-03-31 17:33:33.617567
valid FFT windows: 478293

In [ ]:
#import numpy as np
#import pandas as pd
#import matplotlib.pyplot as plt
#import matplotlib.dates as mdates
#from matplotlib.colors import Normalize
#from pathlib import Path
#
#
#def edges_numeric(arr):
#    arr = np.asarray(arr, dtype=float)
#    if arr.size < 2:
#        return np.concatenate((arr, arr + 1.0))
#    d = np.diff(arr) / 2.0
#    return np.concatenate(([arr[0] - d[0]], arr[:-1] + d, [arr[-1] + d[-1]]))
#
#
## ============================================================
## save base path
## ============================================================
#
#path_base_save_plot = f'/mnt/j/statistical_analysis_arase/preanalysis'
#path_base_save_plot = Path(path_base_save_plot + f'/MGF_spec')
#os.makedirs(path_base_save_plot, exist_ok=True)
#
#
#
## ============================================================
## plot settings
## ============================================================
#
#vmin = -4
#vmax = -1
#
#for idx, row in merged_ranges_df.iterrows():
#
#    start = pd.to_datetime(row["start_time"])
#    end   = pd.to_datetime(row["end_time"])
#
#    if pd.isna(start) or pd.isna(end):
#        continue
#
#    f_cH_plot = f_cH.sel(time=slice(start, end))
#    f_cHe_plot = f_cHe.sel(time=slice(start, end))
#    f_cO_plot = f_cO.sel(time=slice(start, end))
#
#    # xarray sel 用
#    B64_spectra_qf_analysis = B64_spectra_qf.sel(
#        time=slice(start, end)
#    )
#
#    # time が少なすぎる場合は skip
#    if B64_spectra_qf_analysis.sizes.get("time", 0) < 2:
#        print(f"skip: too few time points: {start} - {end}")
#        continue
#
#    data = B64_spectra_qf_analysis.values
#    data = np.where(np.isfinite(data) & (data > 0), data, np.nan)
#
#    if np.isnan(data).all():
#        print(f"skip: all NaN: {start} - {end}")
#        continue
#
#    logdata = np.log10(data)
#
#    times = pd.DatetimeIndex(pd.to_datetime(B64_spectra_qf_analysis.time.values))
#    t_num = mdates.date2num(times.to_pydatetime())
#    t_edges = edges_numeric(t_num)
#
#    freqs = B64_spectra_qf_analysis.spec_bins.values
#    f_edges = edges_numeric(freqs)
#
#    fig, ax = plt.subplots(figsize=(12, 4.5))
#
#    pcm = ax.pcolormesh(
#        t_edges,
#        f_edges,
#        logdata.T,
#        shading="auto",
#        cmap="turbo",
#        norm=Normalize(vmin=vmin, vmax=vmax),
#    )
#
#    ax.plot(f_cH_plot.time, f_cH_plot.data, lw=1, c='white', linestyle='solid')
#    ax.plot(f_cHe_plot.time, f_cHe_plot.data, lw=1, c='magenta', linestyle='solid')
#    ax.plot(f_cO_plot.time, f_cO_plot.data, lw=1, c='yellow', linestyle='solid')
#
#    ax.xaxis_date()
#    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
#
#    ax.set_yscale("log")
#    ax.set_ylim(3, 32)
#
#    ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())
#
#    ax.set_xlabel("Time")
#    ax.set_ylabel("Frequency [Hz]")
#    ax.set_title(
#        f"MGF 64hz total spec "
#        f"({start:%Y-%m-%d %H:%M:%S} - {end:%Y-%m-%d %H:%M:%S})"
#    )
#
#    fig.colorbar(
#        pcm,
#        ax=ax,
#        label=r"log10 PSD [$\mathrm{nT}^2/\mathrm{Hz}$]"
#    )
#
#    plt.tight_layout()
#
#    # ========================================================
#    # save
#    # ========================================================
#
#    save_dir = path_base_save_plot / f"{start:%Y}" / f"{start:%m}"
#    save_dir.mkdir(parents=True, exist_ok=True)
#
#    filename = (
#        f"MGF_B64_spectra_"
#        f"{start:%Y%m%d_%H%M%S}_to_{end:%Y%m%d_%H%M%S}.png"
#    )
#
#    save_path = save_dir / filename
#
#    fig.savefig(save_path, dpi=200, bbox_inches="tight")
#    plt.close(fig)
#
#    print(f"saved: {save_path}")

29-Sep-26 19:14:43: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_000737_to_20200301_005027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_005626_to_20200301_014114.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_014443_to_20200301_015200.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_022432_to_20200301_023318.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_062856_to_20200301_064548.png

29-Sep-26 19:14:47: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_070508_to_20200301_072514.png

29-Sep-26 19:14:47: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_073559_to_20200301_075930.png

29-Sep-26 19:14:48: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_081634_to_20200301_083659.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_083923_to_20200301_084804.png

29-Sep-26 19:14:49: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_084928_to_20200301_085626.png

29-Sep-26 19:14:50: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_085744_to_20200301_092043.png

29-Sep-26 19:14:51: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_092355_to_20200301_101506.png

29-Sep-26 19:14:52: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_101730_to_20200301_114725.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_120829_to_20200301_121844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_145828_to_20200301_150515.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_150741_to_20200301_152007.png

29-Sep-26 19:14:54: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_161957_to_20200301_162938.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200301_164829_to_20200301_165837.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_012657_to_20200303_013339.png

29-Sep-26 19:14:56: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_053333_to_20200303_054508.png

29-Sep-26 19:14:57: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_064439_to_20200303_074949.png

29-Sep-26 19:14:57: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_080829_to_20200303_085303.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_085303_to_20200303_101033.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_110413_to_20200303_112004.png

29-Sep-26 19:14:59: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_144029_to_20200303_151034.png

29-Sep-26 19:15:00: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_171520_to_20200303_174946.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_175642_to_20200303_185359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_190534_to_20200303_191227.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_191658_to_20200303_192443.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_192551_to_20200303_193741.png

29-Sep-26 19:15:03: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200303_203034_to_20200303_204108.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_040830_to_20200304_043602.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_044504_to_20200304_045624.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_045941_to_20200304_051752.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_052113_to_20200304_053208.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_090604_to_20200304_091247.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_100817_to_20200304_101748.png

29-Sep-26 19:15:08: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_102420_to_20200304_104602.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_104856_to_20200304_115930.png

29-Sep-26 19:15:09: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_120829_to_20200304_152234.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_152252_to_20200304_154627.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200304_214639_to_20200304_215414.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_002125_to_20200305_003019.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_053058_to_20200305_055624.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_055920_to_20200305_060654.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_061147_to_20200305_061829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_062158_to_20200305_062841.png

29-Sep-26 19:15:15: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_063642_to_20200305_064746.png

29-Sep-26 19:15:15: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_065443_to_20200305_070509.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_070645_to_20200305_071559.png

29-Sep-26 19:15:17: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_071753_to_20200305_072833.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_080829_to_20200305_090740.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_090946_to_20200305_093003.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_093827_to_20200305_095536.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200305_095811_to_20200305_100535.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_001717_to_20200306_002359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_002910_to_20200306_003552.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_093353_to_20200306_094755.png

29-Sep-26 19:15:22: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_094946_to_20200306_100403.png

29-Sep-26 19:15:22: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_100450_to_20200306_101625.png

29-Sep-26 19:15:23: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_101737_to_20200306_104529.png

29-Sep-26 19:15:24: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_104714_to_20200306_105457.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_120829_to_20200306_134654.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_135252_to_20200306_141119.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_141222_to_20200306_145141.png

29-Sep-26 19:15:27: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200306_145704_to_20200306_151602.png

29-Sep-26 19:15:28: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_053301_to_20200307_060617.png

29-Sep-26 19:15:29: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_060729_to_20200307_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_080829_to_20200307_093632.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_094846_to_20200307_095649.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_131058_to_20200307_132256.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_132630_to_20200307_133406.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200307_133458_to_20200307_134140.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_041848_to_20200308_043302.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_081504_to_20200308_082306.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_090728_to_20200308_091410.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_092924_to_20200308_093954.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_094356_to_20200308_101035.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_101118_to_20200308_103516.png

29-Sep-26 19:15:36: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_103917_to_20200308_114142.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_114236_to_20200308_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_121331_to_20200308_122013.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_123251_to_20200308_135503.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_140433_to_20200308_141342.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_190437_to_20200308_191710.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_202219_to_20200308_203553.png

29-Sep-26 19:15:41: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_204419_to_20200308_212930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_213740_to_20200308_215016.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200308_224921_to_20200308_231522.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_042422_to_20200309_045621.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_050048_to_20200309_052249.png

29-Sep-26 19:15:44: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_052411_to_20200309_054404.png

29-Sep-26 19:15:45: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_061300_to_20200309_065052.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_065300_to_20200309_070753.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_071828_to_20200309_072511.png

29-Sep-26 19:15:47: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_072707_to_20200309_074358.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_074811_to_20200309_075930.png

29-Sep-26 19:15:48: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_083745_to_20200309_085431.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_181103_to_20200309_182838.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200309_182958_to_20200309_185226.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_001053_to_20200310_002328.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_002509_to_20200310_003355.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_004801_to_20200310_005447.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_020703_to_20200310_021345.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_022055_to_20200310_023045.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_024118_to_20200310_024814.png

29-Sep-26 19:15:53: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_064049_to_20200310_064811.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_065415_to_20200310_072115.png

29-Sep-26 19:15:54: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_080901_to_20200310_082822.png

29-Sep-26 19:15:54: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_085258_to_20200310_092526.png

29-Sep-26 19:15:55: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_092646_to_20200310_094335.png

29-Sep-26 19:15:56: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_105654_to_20200310_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_120829_to_20200310_125910.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_125927_to_20200310_131036.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_132746_to_20200310_133754.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_133754_to_20200310_135821.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200310_171309_to_20200310_172123.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200311_123216_to_20200311_124141.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200311_124731_to_20200311_125438.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200311_152640_to_20200311_153627.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200311_172346_to_20200311_173825.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200311_174013_to_20200311_175023.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_064035_to_20200312_071539.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_072752_to_20200312_073434.png

29-Sep-26 19:16:03: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_073751_to_20200312_074441.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_080829_to_20200312_083616.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_084200_to_20200312_084958.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_085649_to_20200312_090344.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_090522_to_20200312_091205.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_091752_to_20200312_093827.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_094630_to_20200312_103106.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_104257_to_20200312_105954.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_110557_to_20200312_111239.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_122001_to_20200312_123848.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_192117_to_20200312_192759.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_193158_to_20200312_194225.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_200221_to_20200312_200903.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_200948_to_20200312_201710.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_203635_to_20200312_204347.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_213329_to_20200312_214021.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200312_214407_to_20200312_215516.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_025712_to_20200313_032114.png

29-Sep-26 19:16:14: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_032408_to_20200313_033246.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_034255_to_20200313_035930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_041029_to_20200313_041844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_042204_to_20200313_043127.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_044846_to_20200313_045528.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_061428_to_20200313_062159.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_065419_to_20200313_071942.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_102344_to_20200313_104210.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_105646_to_20200313_112944.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_114320_to_20200313_115006.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_152117_to_20200313_152800.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_161919_to_20200313_163113.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200313_163202_to_20200313_165905.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200314_095346_to_20200314_100032.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200314_100343_to_20200314_110844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200314_111230_to_20200314_111912.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200314_113055_to_20200314_114454.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_061657_to_20200315_062340.png

29-Sep-26 19:16:25: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_063613_to_20200315_064255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_132514_to_20200315_134139.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_134245_to_20200315_140944.png

29-Sep-26 19:16:27: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_141952_to_20200315_143528.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_154645_to_20200315_155930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_162237_to_20200315_162920.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_223136_to_20200315_223902.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_224241_to_20200315_225214.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_225216_to_20200315_231820.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_232323_to_20200315_233241.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200315_233331_to_20200315_235349.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_003420_to_20200316_010156.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_060852_to_20200316_062735.png

29-Sep-26 19:16:33: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_072345_to_20200316_074407.png

29-Sep-26 19:16:34: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_074519_to_20200316_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_080829_to_20200316_093120.png

29-Sep-26 19:16:35: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_093654_to_20200316_095006.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_101049_to_20200316_101841.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_104231_to_20200316_110255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_143537_to_20200316_144306.png

29-Sep-26 19:16:37: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_144436_to_20200316_145806.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200316_202845_to_20200316_203806.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_035106_to_20200317_035753.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_090823_to_20200317_091733.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_093243_to_20200317_095343.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_095843_to_20200317_101653.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_102451_to_20200317_105442.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_105810_to_20200317_110920.png

29-Sep-26 19:16:41: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_111311_to_20200317_113026.png

29-Sep-26 19:16:42: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_113102_to_20200317_115930.png

29-Sep-26 19:16:43: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_120829_to_20200317_130233.png

29-Sep-26 19:16:44: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_133820_to_20200317_135116.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_140756_to_20200317_142229.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_142244_to_20200317_150140.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_150141_to_20200317_152450.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_154036_to_20200317_155353.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_213956_to_20200317_214638.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_215118_to_20200317_215824.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_215828_to_20200317_223643.png

29-Sep-26 19:16:48: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_231154_to_20200317_234131.png

29-Sep-26 19:16:49: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200317_234332_to_20200317_235930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_040830_to_20200318_041629.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_042810_to_20200318_043516.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_063546_to_20200318_064812.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_070459_to_20200318_071408.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_071734_to_20200318_072626.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_072751_to_20200318_073917.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_091026_to_20200318_091709.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_101722_to_20200318_102503.png

29-Sep-26 19:16:54: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_102703_to_20200318_103751.png

29-Sep-26 19:16:55: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_170320_to_20200318_175508.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_180237_to_20200318_184921.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_190855_to_20200318_191656.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200318_195243_to_20200318_200631.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_004508_to_20200319_014640.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_014718_to_20200319_015400.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_022632_to_20200319_023513.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_050453_to_20200319_052626.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_081810_to_20200319_082940.png

29-Sep-26 19:17:01: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_083040_to_20200319_090254.png

29-Sep-26 19:17:02: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_091524_to_20200319_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_120829_to_20200319_134812.png

29-Sep-26 19:17:03: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_135013_to_20200319_135658.png

29-Sep-26 19:17:04: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_141007_to_20200319_142303.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_142608_to_20200319_151542.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_175100_to_20200319_180321.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_190947_to_20200319_192112.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_193259_to_20200319_193941.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_201534_to_20200319_202411.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_204429_to_20200319_210051.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_210350_to_20200319_211032.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_212102_to_20200319_212835.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_213902_to_20200319_215821.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_220929_to_20200319_222028.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200319_235052_to_20200319_235735.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_144437_to_20200320_145249.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_145758_to_20200320_150619.png

29-Sep-26 19:17:11: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_151226_to_20200320_152229.png

29-Sep-26 19:17:12: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_152627_to_20200320_160008.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_160737_to_20200320_173713.png

29-Sep-26 19:17:13: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_173814_to_20200320_175657.png

29-Sep-26 19:17:14: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_175802_to_20200320_184309.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_184309_to_20200320_190644.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_190714_to_20200320_191356.png

29-Sep-26 19:17:16: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200320_192623_to_20200320_194103.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_080829_to_20200321_084332.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_090431_to_20200321_093117.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_093503_to_20200321_101215.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_101255_to_20200321_105440.png

29-Sep-26 19:17:20: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_105855_to_20200321_110537.png

29-Sep-26 19:17:20: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_111347_to_20200321_115930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_120829_to_20200321_123640.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_123643_to_20200321_133047.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_133047_to_20200321_140120.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_140928_to_20200321_142554.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_142648_to_20200321_143336.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_181844_to_20200321_185945.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_222439_to_20200321_223255.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200321_223835_to_20200321_224517.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_024516_to_20200322_030614.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_033456_to_20200322_034347.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_053937_to_20200322_054620.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_060230_to_20200322_064920.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_071726_to_20200322_072408.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_083148_to_20200322_083944.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_155137_to_20200322_155933.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_174044_to_20200322_174924.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_175720_to_20200322_180457.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_181223_to_20200322_182359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_220956_to_20200322_222023.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200322_223512_to_20200322_224155.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_004821_to_20200323_014348.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_014928_to_20200323_020722.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_023054_to_20200323_023736.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_032610_to_20200323_033609.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_033956_to_20200323_034811.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_063945_to_20200323_065823.png

29-Sep-26 19:17:35: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_071602_to_20200323_074707.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_075014_to_20200323_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_081157_to_20200323_081943.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_083004_to_20200323_083817.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_090012_to_20200323_091341.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_092917_to_20200323_093600.png

29-Sep-26 19:17:39: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_093933_to_20200323_094616.png

29-Sep-26 19:17:39: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_094840_to_20200323_103955.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_104531_to_20200323_113622.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_113713_to_20200323_115100.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_121743_to_20200323_130455.png

29-Sep-26 19:17:42: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_132513_to_20200323_134246.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_165051_to_20200323_170016.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_173507_to_20200323_175017.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_175146_to_20200323_180245.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_180402_to_20200323_181338.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_190911_to_20200323_191557.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_192935_to_20200323_193643.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_193734_to_20200323_194901.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_194919_to_20200323_201046.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_215312_to_20200323_215954.png

29-Sep-26 19:17:47: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200323_220901_to_20200323_221549.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_010847_to_20200325_020027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_022207_to_20200325_022849.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_023833_to_20200325_024515.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_025812_to_20200325_030455.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_061511_to_20200325_062153.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_062255_to_20200325_062937.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_070147_to_20200325_070829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_085404_to_20200325_090326.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_091710_to_20200325_092359.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_092703_to_20200325_093902.png

29-Sep-26 19:17:54: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_094138_to_20200325_095403.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_101357_to_20200325_102346.png

29-Sep-26 19:17:55: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_103303_to_20200325_115824.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_120829_to_20200325_121832.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_122114_to_20200325_122756.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_211409_to_20200325_212051.png

29-Sep-26 19:17:58: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200325_212140_to_20200325_213755.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_120829_to_20200326_122601.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_122627_to_20200326_130955.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_144120_to_20200326_144813.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_145732_to_20200326_153317.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_154739_to_20200326_155708.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200326_163658_to_20200326_165330.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_091550_to_20200327_092232.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_092422_to_20200327_093108.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_094752_to_20200327_101456.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_102231_to_20200327_102925.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_102955_to_20200327_104338.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_111844_to_20200327_113727.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_154555_to_20200327_155239.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_172813_to_20200327_173455.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_175129_to_20200327_182844.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_182925_to_20200327_183607.png

29-Sep-26 19:18:07: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_183753_to_20200327_184452.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_194932_to_20200327_200008.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200327_200756_to_20200327_202459.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_054055_to_20200328_055615.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_060352_to_20200328_061034.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_103623_to_20200328_111936.png

29-Sep-26 19:18:11: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_111942_to_20200328_112829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_120829_to_20200328_122423.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_122447_to_20200328_125614.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_125657_to_20200328_130443.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_131703_to_20200328_132919.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_151840_to_20200328_152522.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_162345_to_20200328_163157.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_223626_to_20200328_225923.png

29-Sep-26 19:18:16: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200328_230446_to_20200328_234450.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_000830_to_20200329_003214.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_043704_to_20200329_045053.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_064915_to_20200329_070208.png

29-Sep-26 19:18:18: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_070643_to_20200329_073201.png

29-Sep-26 19:18:19: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_073317_to_20200329_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_080829_to_20200329_085141.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_085635_to_20200329_090855.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_103250_to_20200329_104549.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200329_105555_to_20200329_111037.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_001308_to_20200330_002222.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_002428_to_20200330_003122.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_022609_to_20200330_023410.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_024340_to_20200330_025030.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_025623_to_20200330_030305.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_032244_to_20200330_033411.png

29-Sep-26 19:18:25: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_034154_to_20200330_034836.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_040830_to_20200330_042829.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_043403_to_20200330_045232.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_045352_to_20200330_050348.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_054909_to_20200330_055632.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_091537_to_20200330_092256.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_092608_to_20200330_114428.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_114723_to_20200330_115556.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_120947_to_20200330_121633.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_122951_to_20200330_123635.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_123917_to_20200330_124820.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_131552_to_20200330_143726.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_144330_to_20200330_145028.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_151628_to_20200330_153231.png

29-Sep-26 19:18:34: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_153515_to_20200330_154740.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_200737_to_20200330_203039.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_203052_to_20200330_204128.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_204449_to_20200330_205907.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_210333_to_20200330_220110.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_221138_to_20200330_222816.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200330_224730_to_20200330_225559.png

29-Sep-26 19:18:38: /tmp/ipykernel_91668/2285973339.py:93: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_004030_to_20200331_005004.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_074521_to_20200331_075930.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_080904_to_20200331_082305.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_083108_to_20200331_083828.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_102047_to_20200331_103344.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_135721_to_20200331_144027.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_145412_to_20200331_150103.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_151114_to_20200331_151805.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_154256_to_20200331_155441.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_163241_to_20200331_165326.png
saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec/2020/03/MGF_B64_spectra_20200331_172652_to_20200331_173334.png

# 各selected_timeでのMGF PSDの勾配を確認

In [38]:
import numpy as np
import pandas as pd
from tqdm.contrib.concurrent import thread_map


def quantify_decreasing_psd_array(f, P):
    """
    1時刻の MGF PSD spectrum が 3--32 Hz で概ね単調減少かを定量化する。
    xarray を使わない高速版。
    """

    f = np.asarray(f, dtype=float)
    P = np.asarray(P, dtype=float)

    use = np.isfinite(f) & np.isfinite(P) & (P > 0)

    f = f[use]
    P = P[use]

    if len(f) < 3:
        return {
            "n_points": len(f),
            "alpha": np.nan,
            "intercept": np.nan,
            "r2_loglog": np.nan,
            "rmse_log10": np.nan,
            "spearman_rho": np.nan,
            "adjacent_decrease_fraction": np.nan,
            "positive_local_slope_fraction": np.nan,
            "median_local_alpha": np.nan,
            "log10_drop_low_to_high": np.nan,
            "monotonic_decrease_score": np.nan,
        }

    order = np.argsort(f)
    f = f[order]
    P = P[order]

    logf = np.log10(f)
    logP = np.log10(P)

    # log10(PSD) = intercept + slope * log10(f)
    # PSD が f^(-alpha) 型で減少する場合 alpha > 0。
    slope, intercept = np.polyfit(logf, logP, 1)
    alpha = -slope

    fit = intercept + slope * logf
    resid = logP - fit

    ss_res = np.sum(resid**2)
    ss_tot = np.sum((logP - np.mean(logP))**2)

    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
    rmse_log10 = np.sqrt(np.mean(resid**2))

    spearman_rho = pd.Series(logf).corr(
        pd.Series(logP),
        method="spearman",
    )

    dlogP = np.diff(logP)
    dlogf = np.diff(logf)

    adjacent_decrease_fraction = np.mean(dlogP < 0)

    local_alpha = -dlogP / dlogf

    positive_local_slope_fraction = np.mean(local_alpha > 0)
    median_local_alpha = np.nanmedian(local_alpha)

    log10_drop_low_to_high = logP[0] - logP[-1]

    decreasing_variation = np.sum(np.maximum(-dlogP, 0))
    total_variation = np.sum(np.abs(dlogP))

    if total_variation > 0:
        monotonic_decrease_score = decreasing_variation / total_variation
    else:
        monotonic_decrease_score = np.nan

    return {
        "n_points": len(f),
        "alpha": alpha,
        "intercept": intercept,
        "r2_loglog": r2,
        "rmse_log10": rmse_log10,
        "spearman_rho": spearman_rho,
        "adjacent_decrease_fraction": adjacent_decrease_fraction,
        "positive_local_slope_fraction": positive_local_slope_fraction,
        "median_local_alpha": median_local_alpha,
        "log10_drop_low_to_high": log10_drop_low_to_high,
        "monotonic_decrease_score": monotonic_decrease_score,
    }


def _check_threshold(value, threshold, mode):
    """
    threshold が None なら条件を課さない。
    mode は 'gt' or 'lt'。
    """

    if threshold is None:
        return True

    if not np.isfinite(value):
        return False

    if mode == "gt":
        return value > threshold
    if mode == "lt":
        return value < threshold

    raise ValueError("mode must be 'gt' or 'lt'")


def make_mask_in_ranges(time_values, ranges_df):
    """
    time_values が ranges_df の start_time--end_time 内にあるかを返す。
    """

    times = pd.DatetimeIndex(pd.to_datetime(time_values))

    if ranges_df is None or len(ranges_df) == 0:
        return np.zeros(len(times), dtype=bool)

    return make_mask_in_padded_ranges(
        times,
        ranges_df,
        pad=pd.Timedelta(0),
    )

In [39]:
def make_monotonic_selected_times_parallel(
    B64_spectra_qf,
    selected_times,
    selected_fracs=None,
    source_indices=None,
    freq_dim="spec_bins",
    fmin=3,
    fmax=32,
    alpha_min=0.0,
    alpha_max=None,
    r2_min=0.5,
    spearman_max=-0.7,
    adjacent_decrease_fraction_min=0.65,
    monotonic_decrease_score_min=0.7,
    n_workers=8,
    desc="Checking monotonic B PSD",
    nearest_tolerance=None,
):
    """
    selected_times のうち、B PSD が概ね単調減少する時刻だけを抽出する。

    B64_spectra_qf は前段で merged_ranges_df 内の target_times だけに限定して作るため、
    ここでは selected_times を B64_spectra_qf.time に照合して評価する。
    threshold に None を指定した場合、その条件は使わない。
    """

    da = B64_spectra_qf.transpose("time", freq_dim)
    da = da.sel({freq_dim: slice(fmin, fmax)})

    all_times = pd.DatetimeIndex(pd.to_datetime(da.time.values))
    selected_times_pd = pd.DatetimeIndex(pd.to_datetime(selected_times))

    if source_indices is None:
        source_indices = np.arange(len(selected_times_pd))
    else:
        source_indices = np.asarray(source_indices)

    freqs = da[freq_dim].values.astype(float)
    spectra_values = da.values.astype(float)

    if nearest_tolerance is None:
        time_indexer = all_times.get_indexer(selected_times_pd)
    else:
        time_indexer = all_times.get_indexer(
            selected_times_pd,
            method="nearest",
            tolerance=pd.Timedelta(nearest_tolerance),
        )

    def process_one(i):
        t = selected_times_pd[i]
        idx = time_indexer[i]

        if idx < 0:
            return {
                "source_index": int(source_indices[i]),
                "time": t,
                "matched_time": pd.NaT,
                "n_points": np.nan,
                "alpha": np.nan,
                "intercept": np.nan,
                "r2_loglog": np.nan,
                "rmse_log10": np.nan,
                "spearman_rho": np.nan,
                "adjacent_decrease_fraction": np.nan,
                "positive_local_slope_fraction": np.nan,
                "median_local_alpha": np.nan,
                "log10_drop_low_to_high": np.nan,
                "monotonic_decrease_score": np.nan,
                "is_monotonic_decreasing": False,
                "reject_reason": "no_matching_B64_spectrum",
            }

        P = spectra_values[idx, :]

        metrics = quantify_decreasing_psd_array(
            f=freqs,
            P=P,
        )

        alpha = metrics["alpha"]
        r2 = metrics["r2_loglog"]
        rho = metrics["spearman_rho"]
        dec_frac = metrics["adjacent_decrease_fraction"]
        mono_score = metrics["monotonic_decrease_score"]

        ok = (
            np.isfinite(alpha)
            and np.isfinite(r2)
            and np.isfinite(rho)
            and np.isfinite(dec_frac)
            and np.isfinite(mono_score)
            and _check_threshold(alpha, alpha_min, "gt")
            and _check_threshold(alpha, alpha_max, "lt")
            and _check_threshold(r2, r2_min, "gt")
            and _check_threshold(rho, spearman_max, "lt")
            and _check_threshold(dec_frac, adjacent_decrease_fraction_min, "gt")
            and _check_threshold(mono_score, monotonic_decrease_score_min, "gt")
        )

        row = dict(metrics)
        row["source_index"] = int(source_indices[i])
        row["time"] = t
        row["matched_time"] = all_times[idx]
        row["is_monotonic_decreasing"] = bool(ok)
        row["reject_reason"] = "" if ok else "threshold_not_met"

        return row

    rows = thread_map(
        process_one,
        range(len(selected_times_pd)),
        max_workers=n_workers,
        desc=desc,
    )

    metrics_df = pd.DataFrame(rows).set_index("time")

    mask_mono = metrics_df["is_monotonic_decreasing"].values.astype(bool)

    selected_times_mono = np.asarray(selected_times)[mask_mono]

    if selected_fracs is not None:
        selected_fracs_mono = np.asarray(selected_fracs)[mask_mono]
    else:
        selected_fracs_mono = None

    return selected_times_mono, selected_fracs_mono, metrics_df, mask_mono

In [40]:
# ============================================================
# 前段の有効時間範囲に対応する selected_times だけ MGF PSD 勾配判定へ渡す
# ============================================================

selected_times = np.asarray(selected_times)
selected_fracs = np.asarray(selected_fracs)

mask_selected_in_merged_ranges = make_mask_in_ranges(
    selected_times,
    merged_ranges_df,
)

selected_times_for_B_check = selected_times[mask_selected_in_merged_ranges]
selected_fracs_for_B_check = selected_fracs[mask_selected_in_merged_ranges]
source_indices_for_B_check = np.where(mask_selected_in_merged_ranges)[0]

print(f"元の selected_times 数: {len(selected_times)}")
print(f"merged_ranges_df 内の selected_times 数: {len(selected_times_for_B_check)}")
print(f"B64_spectra_qf time 数: {B64_spectra_qf.sizes.get('time', 0)}")

selected_times_mono_in_ranges, selected_fracs_mono_in_ranges, B64_mono_metrics_df, mask_mono_in_ranges = make_monotonic_selected_times_parallel(
    B64_spectra_qf=B64_spectra_qf,
    selected_times=selected_times_for_B_check,
    selected_fracs=selected_fracs_for_B_check,
    source_indices=source_indices_for_B_check,
    freq_dim="spec_bins",
    fmin=3,
    fmax=32,

    alpha_min=0,
    alpha_max=None,
    r2_min=0.5,
    spearman_max=-0.7,
    adjacent_decrease_fraction_min=None,
    monotonic_decrease_score_min=0.5,

    n_workers=16,
    nearest_tolerance=None,
)

# mask_mono は元の selected_times と同じ長さに戻しておく。
mask_mono = np.zeros(len(selected_times), dtype=bool)
mask_mono[source_indices_for_B_check] = mask_mono_in_ranges

selected_times_mono = selected_times[mask_mono]
selected_fracs_mono = selected_fracs[mask_mono]

print(f"B PSD が概ね単調減少する selected_times 数: {len(selected_times_mono)}")
print(f"元の selected_times に対する残存率: {len(selected_times_mono) / len(selected_times):.3f}")
print(f"merged_ranges_df 内 selected_times に対する残存率: {len(selected_times_mono) / len(selected_times_for_B_check):.3f}")

B64_mono_metrics_df

元の selected_times 数: 100831
merged_ranges_df 内の selected_times 数: 100045
B64_spectra_qf time 数: 478971

Checking monotonic B PSD: 100%|██████████| 100045/100045 [02:01<00:00, 821.91it/s]

B PSD が概ね単調減少する selected_times 数: 716
元の selected_times に対する残存率: 0.007
merged_ranges_df 内 selected_times に対する残存率: 0.007

,n_points,alpha,intercept,r2_loglog,rmse_log10,spearman_rho,adjacent_decrease_fraction,positive_local_slope_fraction,median_local_alpha,log10_drop_low_to_high,monotonic_decrease_score,source_index,matched_time,is_monotonic_decreasing,reject_reason
time,,,,,,,,,,,,,,,
2020-03-01 00:08:41.058170,30,0.815973,-3.554904,0.077330,0.778089,-0.247608,0.551724,0.551724,0.887138,3.160078,0.584130,0,2020-03-01 00:08:41.058170,False,threshold_not_met
2020-03-01 00:08:42.058170,30,0.261155,-4.074271,0.011096,0.680595,-0.202670,0.482759,0.482759,-1.357557,0.530215,0.513027,1,2020-03-01 00:08:42.058170,False,threshold_not_met
2020-03-01 00:08:43.058170,30,1.242065,-2.786684,0.215602,0.654018,-0.563960,0.620690,0.620690,5.848812,2.949622,0.597463,2,2020-03-01 00:08:43.058170,False,threshold_not_met
2020-03-01 00:08:45.058264,30,0.500610,-3.803805,0.041755,0.662046,-0.244494,0.413793,0.413793,-1.740868,1.065265,0.528120,3,2020-03-01 00:08:45.058264,False,threshold_not_met
2020-03-01 00:08:46.058264,30,1.064943,-2.889957,0.311928,0.436637,-0.477197,0.448276,0.448276,-1.136542,0.880305,0.539316,4,2020-03-01 00:08:46.058264,False,threshold_not_met
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-31 16:50:05.629087,30,1.293896,-2.994516,0.277850,0.575853,-0.522136,0.551724,0.551724,0.786112,2.982785,0.588136,100826,2020-03-31 16:50:05.629087,False,threshold_not_met
2020-03-31 16:50:06.629087,30,0.676382,-3.394127,0.081842,0.625411,-0.261402,0.482759,0.482759,-2.647675,2.448384,0.570058,100827,2020-03-31 16:50:06.629087,False,threshold_not_met
2020-03-31 17:30:12.617188,30,1.353316,-2.731279,0.430745,0.429484,-0.655617,0.551724,0.551724,4.458690,1.961259,0.578522,100828,2020-03-31 17:30:12.617188,False,threshold_not_met
2020-03-31 17:30:13.617188,30,1.220231,-2.795478,0.259706,0.568731,-0.559511,0.620690,0.620690,2.568064,2.501471,0.583604,100829,2020-03-31 17:30:13.617188,False,threshold_not_met
2020-03-31 17:30:14.617188,30,0.691402,-3.533542,0.047479,0.854911,-0.035373,0.482759,0.482759,-1.061323,5.273960,0.652720,100830,2020-03-31 17:30:14.617188,False,threshold_not_met

# Bzの角度の設定

Breneman+ 2022のRBSPの設定に従い、磁場とspin planeの角度が15°以上の時に有効とする。

In [41]:
import numpy as np
import pandas as pd
import xarray as xr


def make_EdotB0_geometry_mask(
    B_da,
    angle_min_deg=15.0,
    time_dim="time",
    comp_dim=None,
):
    """
    B_da: xarray.DataArray
        shape = (time, 3) を想定。
        成分順は [Bx, By, Bz]。

    angle_min_deg:
        磁場が spin plane / DSI xy plane から何度以上離れていれば有効とみなすか。
        RBSP 的には 15 deg が一つの目安。

    returns:
        xr.Dataset containing:
            B_spinplane_angle_deg
            Ez_amp_factor
            bad_EdotB0_geometry
    """

    if comp_dim is None:
        comp_dims = [d for d in B_da.dims if d != time_dim]
        if len(comp_dims) != 1:
            raise ValueError("component dimension を特定できないので comp_dim を指定してほしい。")
        comp_dim = comp_dims[0]

    Bx = B_da.isel({comp_dim: 0})
    By = B_da.isel({comp_dim: 1})
    Bz = B_da.isel({comp_dim: 2})

    Bxy = np.sqrt(Bx**2 + By**2)
    Bmag = np.sqrt(Bx**2 + By**2 + Bz**2)

    theta_B_spin = np.degrees(np.arctan2(np.abs(Bz), Bxy))

    Ez_amp_factor = xr.where(
        np.abs(Bz) > 0,
        Bxy / np.abs(Bz),
        np.inf,
    )

    bad_geom = (
        ~np.isfinite(theta_B_spin)
        | ~np.isfinite(Ez_amp_factor)
        | ~np.isfinite(Bmag)
        | (Bmag <= 0)
        | (theta_B_spin < angle_min_deg)
    )

    out = xr.Dataset({
        "B_spinplane_angle_deg": theta_B_spin,
        "Ez_amp_factor": Ez_amp_factor,
        "bad_EdotB0_geometry": bad_geom,
    })

    return out

In [42]:
geom = make_EdotB0_geometry_mask(
    B64_data_dsi_qf,
    angle_min_deg=15.0,
)

bad_mask_spin_angle_raw = geom["bad_EdotB0_geometry"]

# B64_data_dsi_qf は FFT 端のため pad を含んでいるので、判定に使う範囲は merged_ranges_df 内に戻す。
mask_B64_in_merged_ranges = xr.DataArray(
    make_mask_in_ranges(B64_data_dsi_qf["time"].values, merged_ranges_df),
    coords={"time": B64_data_dsi_qf["time"]},
    dims=("time",),
)

bad_mask_spin_angle = bad_mask_spin_angle_raw & mask_B64_in_merged_ranges
bad_times_spin_angle = B64_data_dsi_qf["time"].where(bad_mask_spin_angle, drop=True)

n_in_ranges = int(mask_B64_in_merged_ranges.sum().values)
n_bad_spin = int(bad_mask_spin_angle.sum().values)
bad_fraction_spin = n_bad_spin / n_in_ranges if n_in_ranges > 0 else np.nan

print(f"B64 samples in merged_ranges_df: {n_in_ranges}")
print(f"bad spin-angle samples: {n_bad_spin}")
print(f"bad fraction in merged_ranges_df = {bad_fraction_spin:.4f}")
print(bad_times_spin_angle)

B64 samples in merged_ranges_df: 30672159
bad spin-angle samples: 4620345
bad fraction in merged_ranges_df = 0.1506
<xarray.DataArray 'time' (time: 4620345)> Size: 37MB
array(['2020-03-01T06:28:56.018297088', '2020-03-01T06:28:56.033896960',
       '2020-03-01T06:28:56.049497088', ...,
       '2020-03-31T15:54:41.611398144', '2020-03-31T15:54:41.626998016',
       '2020-03-31T15:54:41.642597888'],
      shape=(4620345,), dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 37MB 2020-03-01T06:28:56.018297088 ... 202...

# EFD波形データの有効時間の確認

In [43]:
import cdflib
from tqdm.auto import tqdm


def make_efd64_quality_save_path(
    ranges_df,
    time_range,
    ranges_signature,
    base_dir=Path("/mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/E64_quality"),
):
    """有効区間限定 E64 quality flag の保存パスを一意に作る。"""

    base_dir = Path(base_dir)
    base_dir.mkdir(parents=True, exist_ok=True)

    if ranges_df is not None and len(ranges_df) > 0:
        t0 = pd.to_datetime(ranges_df["start_time"].min())
        t1 = pd.to_datetime(ranges_df["end_time"].max())
    else:
        t0 = pd.to_datetime(time_range[0])
        t1 = pd.to_datetime(time_range[-1])

    filename = (
        f"E64_quality_valid_ranges_"
        f"{t0:%Y%m%d_%H%M%S}_to_{t1:%Y%m%d_%H%M%S}_"
        f"r{ranges_signature}.nc"
    )
    return base_dir / filename


def _empty_efd64_quality():
    return xr.DataArray(
        np.array([], dtype=np.uint32),
        coords={"time": np.array([], dtype="datetime64[ns]")},
        dims=("time",),
        name="E64_data_dsi_quality_flag",
    )


def load_efd64_quality_for_ranges(
    ranges_df,
    pad=pd.Timedelta(seconds=2),
    no_update=True,
    use_cache=True,
    force_reload=False,
    save_path=None,
):
    """
    EFD 64 Hz日次CDFからquality_flagだけを読み、有効区間+padへ絞る。

    waveform本体をergpy.pwe_efdでtplot展開すると、空区間や通信失敗後に
    waveform用time_offsetsがなくIndexErrorになるため、downloadonlyで得た
    local CDFのEpoch/quality_flagを直接読む。通信は先行prefetchだけで行う。
    """

    if ranges_df is None or len(ranges_df) == 0:
        raise ValueError("ranges_df が空なので EFD 64 Hz quality flag を読み込めない。")

    if save_path is not None:
        save_path = Path(save_path)

    if use_cache and save_path is not None and save_path.exists() and not force_reload:
        try:
            with xr.open_dataset(save_path) as ds_loaded:
                quality = ds_loaded["E64_data_dsi_quality_flag"].load()
            print(f"loaded cached EFD 64 Hz quality flag: {save_path}")
            return quality
        except Exception as err:
            print(f"failed to load cached EFD 64 Hz quality flag; recompute: {save_path} ({err})")
            try:
                save_path.unlink()
            except OSError:
                pass

    ranges = _normalize_time_ranges(ranges_df)
    pad = pd.Timedelta(pad)
    load_start = ranges["start_time"].min() - pad
    load_end = ranges["end_time"].max() + pad
    trange_all = _format_erg_trange(load_start, load_end)

    files = load_erg_with_retry(
        ergpy.pwe_efd,
        description="PWE-EFD L2 64 Hz quality CDF load",
        validate_result=lambda result: result is not None and len(result) > 0,
        trange=trange_all,
        level="l2",
        datatype="64",
        coord="dsi",
        downloadonly=True,
        no_update=no_update,
        ror=False,
    )
    if files is None:
        files = []
    elif isinstance(files, (str, Path)):
        files = [str(files)]
    else:
        files = [str(path) for path in files]
    files = list(dict.fromkeys(files))

    print(f"EFD quality source CDFs: {len(files)}")
    print(f"EFD quality local-only : {bool(no_update)}")

    qf_list = []
    failed_files = []
    for file in tqdm(files, desc="Reading EFD quality CDFs"):
        cdf = None
        try:
            cdf = cdflib.CDF(file)
            epoch = np.asarray(cdf.varget("Epoch")).reshape(-1)
            quality = np.asarray(cdf.varget("quality_flag")).reshape(-1)
            times = np.asarray(cdflib.cdfepoch.to_datetime(epoch)).reshape(-1)

            if len(times) != len(quality):
                raise ValueError(
                    f"Epoch/quality_flag length mismatch: {len(times)} != {len(quality)}"
                )

            use = make_mask_in_padded_ranges(times, ranges, pad=pad)
            if not np.any(use):
                continue

            qf_list.append(xr.DataArray(
                quality[use],
                coords={"time": times[use]},
                dims=("time",),
                name="E64_data_dsi_quality_flag",
            ))
        except Exception as err:
            failed_files.append((file, repr(err)))
            print(f"skip unreadable EFD quality CDF: {file} ({err})")

    if qf_list:
        quality = xr.concat(qf_list, dim="time").sortby("time")
        quality = _drop_duplicate_times(quality)
        quality.name = "E64_data_dsi_quality_flag"
    else:
        # 後段のcoverage-aware gap判定が全候補区間を欠損として除外する。
        quality = _empty_efd64_quality()

    if save_path is not None:
        qf_cache = xr.DataArray(
            quality.values,
            coords={"time": quality["time"].values},
            dims=("time",),
            name="E64_data_dsi_quality_flag",
            attrs={
                "long_name": "PWE-EFD 64 Hz DSI waveform quality flag",
                "analysis_ranges": "Only merged_ranges_df intervals were retained.",
                "pad_seconds": float(pad.total_seconds()),
                "source_cdf_count": int(len(files)),
                "failed_cdf_count": int(len(failed_files)),
                "read_method": "Direct Epoch and quality_flag read via cdflib",
            },
        )
        qf_cache.to_dataset(name="E64_data_dsi_quality_flag").to_netcdf(save_path)
        print(f"saved EFD 64 Hz quality flag: {save_path}")

    if failed_files:
        print(f"warning: unreadable EFD quality CDFs: {len(failed_files)}")

    return quality


E64_ranges_signature = make_ranges_signature(merged_ranges_df)
E64_quality_save_path = make_efd64_quality_save_path(
    merged_ranges_df,
    time_range,
    ranges_signature=E64_ranges_signature,
)

force_reload_E64_quality = False

E64_data_dsi_quality_flag = load_efd64_quality_for_ranges(
    merged_ranges_df,
    pad=pd.Timedelta(seconds=2),
    no_update=True,
    use_cache=True,
    force_reload=force_reload_E64_quality,
    save_path=E64_quality_save_path,
)

# pad部分を後段のbad判定へ混ぜないため、merged_ranges_df内だけに戻す。
mask_E64_in_merged_ranges = xr.DataArray(
    make_mask_in_ranges(E64_data_dsi_quality_flag["time"].values, merged_ranges_df),
    coords={"time": E64_data_dsi_quality_flag["time"]},
    dims=("time",),
)
E64_data_dsi_quality_flag = E64_data_dsi_quality_flag.where(
    mask_E64_in_merged_ranges,
    drop=True,
)

print(E64_data_dsi_quality_flag)
print(f"E64 quality samples in merged_ranges_df: {E64_data_dsi_quality_flag.sizes.get('time', 0)}")
print(f"E64 ranges signature: {E64_ranges_signature}")
print(f"E64 quality cache path: {E64_quality_save_path}")

29-Sep-26 19:20:55: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200301_v01_03.cdf
29-Sep-26 19:20:56: No local files found for https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200302_v??_??.cdf
29-Sep-26 19:20:57: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200303_v01_03.cdf
29-Sep-26 19:20:58: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200304_v01_03.cdf
29-Sep-26 19:20:59: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200305_v01_03.cdf
29-Sep-26 19:21:00: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200306_v01_03.cdf
29-Sep-26 19:21:00: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200307_v01_03.cdf
29-Sep-26 19:21:01: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200308_v01_03.cdf
29-Sep-26 19:21:02: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200309_v01_03.cdf
29-Sep-26 19:21:03: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200310_v01_03.cdf
29-Sep-26 19:21:04: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200311_v01_03.cdf
29-Sep-26 19:21:05: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200312_v01_03.cdf
29-Sep-26 19:21:06: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200313_v01_03.cdf
29-Sep-26 19:21:07: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200314_v01_03.cdf
29-Sep-26 19:21:08: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200315_v01_03.cdf
29-Sep-26 19:21:08: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200316_v01_03.cdf
29-Sep-26 19:21:09: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200317_v01_03.cdf
29-Sep-26 19:21:10: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200318_v01_03.cdf
29-Sep-26 19:21:11: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200319_v01_03.cdf
29-Sep-26 19:21:12: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200320_v01_03.cdf
29-Sep-26 19:21:13: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200321_v01_03.cdf
29-Sep-26 19:21:14: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200322_v01_03.cdf
29-Sep-26 19:21:15: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200323_v01_03.cdf
29-Sep-26 19:21:16: No local files found for https://ergsc.isee.nagoya-u.ac.jp/data/ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200324_v??_??.cdf
29-Sep-26 19:21:16: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200325_v01_03.cdf
29-Sep-26 19:21:17: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200326_v01_03.cdf
29-Sep-26 19:21:18: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200327_v01_03.cdf
29-Sep-26 19:21:19: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200328_v01_03.cdf
29-Sep-26 19:21:20: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200329_v01_03.cdf
29-Sep-26 19:21:21: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200330_v01_03.cdf
29-Sep-26 19:21:22: Local file found: /mnt/j/observation_data//ergsc/satellite/erg/pwe/efd/l2/E64Hz/2020/03/erg_pwe_efd_l2_E64Hz_dsi_20200331_v01_03.cdf

EFD quality source CDFs: 29
EFD quality local-only : True

Reading EFD quality CDFs:   0%|          | 0/29 [00:00<?, ?it/s]29-Sep-26 19:21:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:23: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:   3%|▎         | 1/29 [00:00<00:24,  1.13it/s]29-Sep-26 19:21:24: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:24: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:   7%|▋         | 2/29 [00:02<00:35,  1.30s/it]29-Sep-26 19:21:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:26: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  10%|█         | 3/29 [00:04<00:42,  1.62s/it]29-Sep-26 19:21:28: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:28: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  14%|█▍        | 4/29 [00:06<00:41,  1.65s/it]29-Sep-26 19:21:29: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:29: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  17%|█▋        | 5/29 [00:07<00:35,  1.47s/it]29-Sep-26 19:21:31: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:31: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  21%|██        | 6/29 [00:09<00:35,  1.56s/it]29-Sep-26 19:21:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:33: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  24%|██▍       | 7/29 [00:10<00:36,  1.67s/it]29-Sep-26 19:21:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:34: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  28%|██▊       | 8/29 [00:12<00:34,  1.66s/it]29-Sep-26 19:21:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:36: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  31%|███       | 9/29 [00:14<00:33,  1.67s/it]29-Sep-26 19:21:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:38: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  34%|███▍      | 10/29 [00:15<00:31,  1.67s/it]29-Sep-26 19:21:39: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:39: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  38%|███▊      | 11/29 [00:17<00:28,  1.60s/it]29-Sep-26 19:21:41: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:41: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  41%|████▏     | 12/29 [00:19<00:27,  1.62s/it]29-Sep-26 19:21:42: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:42: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  45%|████▍     | 13/29 [00:20<00:26,  1.63s/it]29-Sep-26 19:21:44: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:44: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  48%|████▊     | 14/29 [00:22<00:24,  1.64s/it]29-Sep-26 19:21:46: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:46: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  52%|█████▏    | 15/29 [00:24<00:22,  1.64s/it]29-Sep-26 19:21:48: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:48: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  55%|█████▌    | 16/29 [00:25<00:21,  1.67s/it]29-Sep-26 19:21:49: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:49: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  59%|█████▊    | 17/29 [00:27<00:20,  1.68s/it]29-Sep-26 19:21:51: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:51: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  62%|██████▏   | 18/29 [00:29<00:18,  1.66s/it]29-Sep-26 19:21:52: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:52: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  66%|██████▌   | 19/29 [00:30<00:16,  1.65s/it]29-Sep-26 19:21:54: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:54: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  69%|██████▉   | 20/29 [00:32<00:14,  1.58s/it]29-Sep-26 19:21:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:56: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  72%|███████▏  | 21/29 [00:33<00:13,  1.65s/it]29-Sep-26 19:21:57: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

29-Sep-26 19:21:57: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:181: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.where(nat_positions, np.datetime64("NaT"), total_datetime)

Reading EFD quality CDFs:  76%|███████▌  | 22/29 [00:35<00:11,  1.60s/it]29-Sep-26 19:21:59: /home/satanka/Documents/observation_workspace/.venv_pyspedas/lib/python3.12/site-packages/cdflib/epochs.py:180: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`). Please use a specific unit instead.
  total_datetime = np.array(sum(arrays))

saved EFD 64 Hz quality flag: /mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/E64_quality/E64_quality_valid_ranges_20200301_000737_to_20200331_173334_rd9661a427768.nc
<xarray.DataArray 'E64_data_dsi_quality_flag' (time: 473616)> Size: 4MB
array([12.,  0.,  0., ...,  0.,  0.,  0.], shape=(473616,))
Coordinates:
  * time     (time) datetime64[ns] 4MB 2020-03-01T00:07:37.071563937 ... 2020...
E64 quality samples in merged_ranges_df: 473616
E64 ranges signature: d9661a427768
E64 quality cache path: /mnt/j/observation_data/statistical_analysis_arase/Arase_analysis_save_data/E64_quality/E64_quality_valid_ranges_20200301_000737_to_20200331_173334_rd9661a427768.nc

# 第二段階検証

In [44]:
import numpy as np
import pandas as pd
import xarray as xr


def keep_true_runs_1d(
    cond,
    dim="time",
    min_run_length=2,
    check_time_gap=True,
    gap_factor=1.5,
):
    """
    1D boolean DataArray について、True が min_run_length 点以上
    連続する区間だけ True として残す。

    Parameters
    ----------
    cond : xr.DataArray
        1D boolean DataArray
    dim : str
        time dimension name
    min_run_length : int
        何点以上連続した True を残すか
    check_time_gap : bool
        True の場合、時刻 gap が通常 dt から大きく外れると別 run とみなす
    gap_factor : float
        median dt の gap_factor 倍より大きい gap で run を切る

    Returns
    -------
    keep_da : xr.DataArray
        cond と同じ time 軸を持つ boolean DataArray
    """

    cond = cond.fillna(False).astype(bool)
    values = cond.values.astype(bool)

    n = len(values)
    keep = np.zeros(n, dtype=bool)

    if n == 0:
        return xr.DataArray(
            keep,
            coords={dim: cond[dim]},
            dims=(dim,),
            name="consecutive_true_mask",
        )

    times = pd.DatetimeIndex(pd.to_datetime(cond[dim].values))

    if check_time_gap and n >= 2:
        t_ns = times.asi8
        dt_sec = np.diff(t_ns) * 1e-9
        dt_sec_valid = dt_sec[np.isfinite(dt_sec) & (dt_sec > 0)]

        if len(dt_sec_valid) > 0:
            dt_ref = np.median(dt_sec_valid)
            max_gap_sec = gap_factor * dt_ref
        else:
            max_gap_sec = np.inf
    else:
        max_gap_sec = np.inf

    i = 0

    while i < n:
        if not values[i]:
            i += 1
            continue

        j = i + 1

        while j < n and values[j]:
            if check_time_gap:
                gap_sec = (times[j] - times[j - 1]).total_seconds()
                if gap_sec > max_gap_sec:
                    break

            j += 1

        run_length = j - i

        if run_length >= min_run_length:
            keep[i:j] = True

        i = j

    keep_da = xr.DataArray(
        keep,
        coords={dim: cond[dim]},
        dims=(dim,),
        name="consecutive_true_mask",
    )

    return keep_da

In [45]:
# MGF quality flag の bad は、前段で有効とした merged_ranges_df 内だけ評価する。
mask_qf_B_in_merged_ranges = xr.DataArray(
    make_mask_in_ranges(qf_B["time"].values, merged_ranges_df),
    coords={"time": qf_B["time"]},
    dims=("time",),
)

qf_B_for_bad_check = qf_B.where(mask_qf_B_in_merged_ranges, drop=True)

bad_mask_mgf_raw = qf_B_for_bad_check > 21

bad_mask_mgf = keep_true_runs_1d(
    bad_mask_mgf_raw,
    dim="time",
    min_run_length=4,     # 4点以上連続した bad のみ残す
    check_time_gap=True,
    gap_factor=1.5,
)

bad_times_mgf = qf_B_for_bad_check.time.where(bad_mask_mgf, drop=True)

print(f"MGF qf samples in merged_ranges_df: {qf_B_for_bad_check.sizes.get('time', 0)}")
print(f"raw MGF bad times: {int(bad_mask_mgf_raw.sum().values)}")
print(f"consecutive MGF bad times: {int(bad_mask_mgf.sum().values)}")
print(bad_times_mgf)

MGF qf samples in merged_ranges_df: 30672159
raw MGF bad times: 1585
consecutive MGF bad times: 1585
<xarray.DataArray 'time' (time: 1585)> Size: 13kB
array(['2020-03-09T06:19:24.124892160', '2020-03-09T06:19:24.140492032',
       '2020-03-09T06:19:24.156091904', ...,
       '2020-03-25T01:09:35.887274752', '2020-03-25T01:09:35.902873088',
       '2020-03-25T01:09:35.918473216'],
      shape=(1585,), dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 13kB 2020-03-09T06:19:24.124892160 ... 202...

In [46]:
bad_mask_efd_wave_raw = E64_data_dsi_quality_flag != 0

bad_mask_efd_wave = keep_true_runs_1d(
    bad_mask_efd_wave_raw,
    dim="time",
    min_run_length=10,
    check_time_gap=True,
    gap_factor=1.5,
)

bad_times_efd_wave = E64_data_dsi_quality_flag.time.where(bad_mask_efd_wave, drop=True)

print(f"EFD 64 Hz qf samples in merged_ranges_df: {E64_data_dsi_quality_flag.sizes.get('time', 0)}")
print(f"raw EFD wave bad times: {int(bad_mask_efd_wave_raw.sum().values)}")
print(f"consecutive EFD wave bad times: {int(bad_mask_efd_wave.sum().values)}")
print(bad_times_efd_wave)

EFD 64 Hz qf samples in merged_ranges_df: 473616
raw EFD wave bad times: 8
consecutive EFD wave bad times: 0
<xarray.DataArray 'time' (time: 0)> Size: 0B
array([], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 0B

In [47]:
import numpy as np
import pandas as pd
import xarray as xr


def find_time_gap_ranges(
    time_da,
    threshold=pd.Timedelta(seconds=30),
    time_dim="time",
    reason="time_gap",
    coverage_ranges_df=None,
):
    """
    time 軸で threshold 以上の欠損区間を bad gap として抽出する。

    coverage_ranges_df を指定しない場合は、従来どおり隣接観測時刻の差だけを調べる。
    指定した場合は各 start_time--end_time 内を独立に調べ、区間端の欠損と
    観測点が1点もない区間も gap に含める。

    Parameters
    ----------
    time_da : xr.DataArray or array-like
        time 座標。例: qf_B.time
    threshold : pd.Timedelta
        欠損継続時間がこの値以上なら gap とみなす。
    time_dim : str
        互換性のため保持する time dimension name。
    reason : str
        gap の reason 名。
    coverage_ranges_df : pd.DataFrame or None
        start_time, end_time を持つ評価対象区間。None なら内部 gap のみを調べる。

    Returns
    -------
    gap_ranges_df : pd.DataFrame
        gap_start_time, gap_end_time, gap_duration_sec などを持つ表。
    """

    del time_dim  # time_da 自体を受け取るため、現実装では参照しない。

    values = time_da.values if hasattr(time_da, "values") else time_da
    times = pd.DatetimeIndex(pd.to_datetime(values)).dropna().sort_values().unique()
    times = pd.DatetimeIndex(times)
    threshold = pd.Timedelta(threshold)

    columns = [
        "gap_start_time",
        "gap_end_time",
        "gap_duration_sec",
        "gap_duration_min",
        "reason",
    ]
    gaps = []

    def append_if_gap(start, end):
        start = pd.Timestamp(start)
        end = pd.Timestamp(end)
        if end - start >= threshold:
            gaps.append((start, end))

    if coverage_ranges_df is None:
        for start, end in zip(times[:-1], times[1:]):
            append_if_gap(start, end)
    else:
        ranges = coverage_ranges_df.dropna(subset=["start_time", "end_time"]).copy()
        ranges["start_time"] = pd.to_datetime(ranges["start_time"])
        ranges["end_time"] = pd.to_datetime(ranges["end_time"])
        ranges = ranges[ranges["end_time"] >= ranges["start_time"]]
        ranges = ranges.sort_values(["start_time", "end_time"])

        for row in ranges.itertuples(index=False):
            range_start = pd.Timestamp(row.start_time)
            range_end = pd.Timestamp(row.end_time)
            in_range = times[(times >= range_start) & (times <= range_end)]

            if len(in_range) == 0:
                append_if_gap(range_start, range_end)
                continue

            append_if_gap(range_start, in_range[0])
            for start, end in zip(in_range[:-1], in_range[1:]):
                append_if_gap(start, end)
            append_if_gap(in_range[-1], range_end)

    if len(gaps) == 0:
        return pd.DataFrame(columns=columns)

    gaps = sorted(gaps)
    merged = []
    current_start, current_end = gaps[0]
    for start, end in gaps[1:]:
        if start <= current_end:
            current_end = max(current_end, end)
        else:
            merged.append((current_start, current_end))
            current_start, current_end = start, end
    merged.append((current_start, current_end))

    rows = []
    for start, end in merged:
        duration_sec = (end - start).total_seconds()
        rows.append({
            "gap_start_time": start,
            "gap_end_time": end,
            "gap_duration_sec": duration_sec,
            "gap_duration_min": duration_sec / 60,
            "reason": reason,
        })

    return pd.DataFrame(rows, columns=columns)

In [48]:
mgf_gap_ranges_df = find_time_gap_ranges(
    B64_data_dsi_qf.time,
    threshold=pd.Timedelta(milliseconds=63),
    reason="mgf_time_gap",
)
display(mgf_gap_ranges_df)

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,reason
0,2020-03-01 00:50:29.054782976,2020-03-01 00:56:24.065616896,355.010833,5.916847,mgf_time_gap
1,2020-03-01 01:41:16.030366720,2020-03-01 01:44:41.051211008,205.020844,3.417014,mgf_time_gap
2,2020-03-01 01:52:02.027329024,2020-03-01 02:24:30.062413056,1948.035084,32.467251,mgf_time_gap
3,2020-03-01 02:33:20.032890112,2020-03-01 06:28:54.019496960,14133.986606,235.566443,mgf_time_gap
4,2020-03-01 06:45:50.985563136,2020-03-01 07:05:06.011655680,1155.026092,19.250435,mgf_time_gap
...,...,...,...,...,...
380,2020-03-31 14:40:29.669275136,2020-03-31 14:54:10.661568000,820.992292,13.683205,mgf_time_gap
381,2020-03-31 15:01:05.654855936,2020-03-31 15:11:12.662465792,607.007609,10.116793,mgf_time_gap
382,2020-03-31 15:18:07.640378880,2020-03-31 15:42:54.645668864,1487.005289,24.783421,mgf_time_gap
383,2020-03-31 15:54:43.641498112,2020-03-31 16:32:39.652109312,2276.010611,37.933510,mgf_time_gap
384,2020-03-31 16:53:28.618103296,2020-03-31 17:26:50.618416128,2002.000312,33.366672,mgf_time_gap

In [49]:
efd_wave_gap_ranges_df = find_time_gap_ranges(
    E64_data_dsi_quality_flag.time,
    threshold=pd.Timedelta(seconds=30),
    reason="efd_wave_time_gap",
    coverage_ranges_df=merged_ranges_df,
)

display(efd_wave_gap_ranges_df)

,gap_start_time,gap_end_time,gap_duration_sec,gap_duration_min,reason
0,2020-03-01 01:05:05.071563937,2020-03-01 01:41:14.041179,2168.969615,36.149494,efd_wave_time_gap
1,2020-03-01 01:44:43.039767000,2020-03-01 01:52:00.041287,437.001520,7.283359,efd_wave_time_gap
2,2020-03-01 02:24:32.047267000,2020-03-01 02:33:18.038827,525.991560,8.766526,efd_wave_time_gap
3,2020-03-01 15:00:05.939348937,2020-03-01 15:05:15.940432,310.001083,5.166685,efd_wave_time_gap
4,2020-03-01 15:07:41.936130000,2020-03-01 15:20:07.927358,745.991228,12.433187,efd_wave_time_gap
5,2020-03-01 16:19:57.929351000,2020-03-01 16:29:38.926049,580.996698,9.683278,efd_wave_time_gap
6,2020-03-31 00:40:30.867753000,2020-03-31 00:50:04.869935,574.002182,9.566703,efd_wave_time_gap

In [50]:
import pandas as pd
import numpy as np


# ============================================================
# helper functions
# ============================================================

def _as_datetime_index_from_time_da(time_da):
    """
    xarray DataArray / numpy array / list-like を DatetimeIndex に変換する。
    """
    if time_da is None:
        return pd.DatetimeIndex([])

    if hasattr(time_da, "values"):
        vals = time_da.values
    else:
        vals = time_da

    out = pd.DatetimeIndex(pd.to_datetime(vals))
    out = out.dropna().sort_values().unique()
    out = pd.DatetimeIndex(out)

    return out


def point_times_to_intervals(
    times,
    gap_factor=1.5,
):
    """
    bad_times のような点列を、連続点ごとに interval 化する。

    例:
      t0, t0+1/64s, t0+2/64s, ... を
      [t0, tN] の1区間にまとめる。

    単発 bad time は [t, t] として残る。
    """

    times = _as_datetime_index_from_time_da(times)

    if len(times) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    if len(times) == 1:
        return pd.DataFrame({
            "start_time": times,
            "end_time": times,
        })

    t_ns = times.asi8
    dt_sec = np.diff(t_ns) * 1e-9

    dt_valid = dt_sec[np.isfinite(dt_sec) & (dt_sec > 0)]

    if len(dt_valid) == 0:
        return pd.DataFrame({
            "start_time": times,
            "end_time": times,
        })

    dt_ref = np.median(dt_valid)
    max_gap = gap_factor * dt_ref

    is_continuous = dt_sec <= max_gap

    break_points = np.where(~is_continuous)[0] + 1
    idx_groups = np.split(np.arange(len(times)), break_points)

    intervals = []

    for idx in idx_groups:
        intervals.append((times[idx[0]], times[idx[-1]]))

    return pd.DataFrame(intervals, columns=["start_time", "end_time"])


def gap_df_to_intervals(gap_df):
    """
    gap DataFrame を start_time, end_time の DataFrame に変換する。

    対応列:
      - missing_start_time, missing_end_time
      - gap_start_time, gap_end_time
    """

    if gap_df is None or len(gap_df) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    if {"missing_start_time", "missing_end_time"}.issubset(gap_df.columns):
        start_col = "missing_start_time"
        end_col = "missing_end_time"
    elif {"gap_start_time", "gap_end_time"}.issubset(gap_df.columns):
        start_col = "gap_start_time"
        end_col = "gap_end_time"
    else:
        raise ValueError(
            "gap_df must have either "
            "['missing_start_time', 'missing_end_time'] or "
            "['gap_start_time', 'gap_end_time'] columns."
        )

    out = pd.DataFrame({
        "start_time": pd.to_datetime(gap_df[start_col]),
        "end_time": pd.to_datetime(gap_df[end_col]),
    })

    out = out.dropna()
    out = out[out["end_time"] >= out["start_time"]]

    return out.reset_index(drop=True)


def merge_intervals(intervals_df):
    """
    start_time, end_time を持つ interval DataFrame を merge する。
    """

    if intervals_df is None or len(intervals_df) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    df = intervals_df.dropna().copy()
    df = df[df["end_time"] >= df["start_time"]]
    df = df.sort_values("start_time").reset_index(drop=True)

    if len(df) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    starts = pd.DatetimeIndex(pd.to_datetime(df["start_time"])).to_numpy()
    ends = pd.DatetimeIndex(pd.to_datetime(df["end_time"])).to_numpy()

    merged = []

    cur_start = starts[0]
    cur_end = ends[0]

    for s, e in zip(starts[1:], ends[1:]):
        if s <= cur_end:
            cur_end = max(cur_end, e)
        else:
            merged.append((cur_start, cur_end))
            cur_start = s
            cur_end = e

    merged.append((cur_start, cur_end))

    return pd.DataFrame({
        "start_time": pd.to_datetime([m[0] for m in merged]),
        "end_time": pd.to_datetime([m[1] for m in merged]),
    })


def make_forbidden_intervals_for_mono(
    bad_times,
    bad_times_mgf,
    bad_times_spin_angle,
    bad_times_efd_wave=None,
    LEPe_gap_ranges_df=None,
    LEPi_gap_ranges_df=None,
    HFA_gap_ranges_df=None,
    mgf_gap_ranges_df=None,
    efd_wave_gap_ranges_df=None,
    att_gap_ranges_df=None,
    merge=True,
):
    """
    第二段階用の bad times / gap ranges をまとめて禁止 interval にする。
    """

    dfs = []

    bad_efd_intervals = point_times_to_intervals(bad_times)
    bad_mgf_intervals = point_times_to_intervals(bad_times_mgf)
    bad_spin_angle_intervals = point_times_to_intervals(bad_times_spin_angle)
    bad_efd_wave_intervals = point_times_to_intervals(bad_times_efd_wave)

    if len(bad_efd_intervals) > 0:
        dfs.append(bad_efd_intervals)

    if len(bad_mgf_intervals) > 0:
        dfs.append(bad_mgf_intervals)

    if len(bad_spin_angle_intervals) > 0:
        dfs.append(bad_spin_angle_intervals)

    if len(bad_efd_wave_intervals) > 0:
        dfs.append(bad_efd_wave_intervals)

    lepe_intervals = gap_df_to_intervals(LEPe_gap_ranges_df)
    lepi_intervals = gap_df_to_intervals(LEPi_gap_ranges_df)
    hfa_intervals = gap_df_to_intervals(HFA_gap_ranges_df)
    mgf_intervals = gap_df_to_intervals(mgf_gap_ranges_df)
    efd_intervals = gap_df_to_intervals(efd_wave_gap_ranges_df)
    att_intervals = gap_df_to_intervals(att_gap_ranges_df)

    if len(lepe_intervals) > 0:
        dfs.append(lepe_intervals)

    if len(lepi_intervals) > 0:
        dfs.append(lepi_intervals)

    if len(hfa_intervals) > 0:
        dfs.append(hfa_intervals)

    if len(mgf_intervals) > 0:
        dfs.append(mgf_intervals)

    if len(efd_intervals) > 0:
        dfs.append(efd_intervals)

    if len(att_intervals) > 0:
        dfs.append(att_intervals)

    if len(dfs) == 0:
        return pd.DataFrame(columns=["start_time", "end_time"])

    forbidden_intervals_df = pd.concat(dfs, ignore_index=True)

    if merge:
        forbidden_intervals_df = merge_intervals(forbidden_intervals_df)

    return forbidden_intervals_df.reset_index(drop=True)

In [51]:
def make_trimmed_time_ranges_by_forbidden(
    selected_times,
    forbidden_intervals_df,
    half_width=EVENT_HALF_WIDTH,
    eps=pd.Timedelta(nanoseconds=1),
):
    """
    selected_times ± half_width の時間範囲を作る。
    ただし forbidden intervals を含まないように、
    各 selected time の前後で最も近い forbidden interval まで切り詰める。
    """

    selected_times_pd = pd.DatetimeIndex(
        pd.to_datetime(selected_times)
    ).sort_values()

    if len(selected_times_pd) == 0:
        return []

    start0 = selected_times_pd - half_width
    end0   = selected_times_pd + half_width

    if forbidden_intervals_df is None or len(forbidden_intervals_df) == 0:
        return list(zip(start0, end0))

    forbidden_intervals_df = forbidden_intervals_df.sort_values("start_time").reset_index(drop=True)

    f_starts = pd.DatetimeIndex(pd.to_datetime(forbidden_intervals_df["start_time"]))
    f_ends   = pd.DatetimeIndex(pd.to_datetime(forbidden_intervals_df["end_time"]))

    t_np      = selected_times_pd.to_numpy()
    start_np  = start0.to_numpy()
    end_np    = end0.to_numpy()
    fs_np     = f_starts.to_numpy()
    fe_np     = f_ends.to_numpy()

    # 各 selected time に対して、start <= t となる最後の forbidden interval
    i_prev = np.searchsorted(fs_np, t_np, side="right") - 1
    valid_prev = i_prev >= 0

    inside_forbidden = np.zeros(len(t_np), dtype=bool)

    # selected time 自体が forbidden interval 内なら除外
    inside_forbidden[valid_prev] = (
        t_np[valid_prev] <= fe_np[i_prev[valid_prev]]
    )

    # 前側の forbidden interval で start を切る
    start_trim = start_np.copy()

    use_prev_trim = np.zeros(len(t_np), dtype=bool)
    use_prev_trim[valid_prev] = (
        fe_np[i_prev[valid_prev]] > start_np[valid_prev]
    )

    start_trim[use_prev_trim] = (
        fe_np[i_prev[use_prev_trim]] + np.timedelta64(eps.value, "ns")
    )

    # 後側の forbidden interval で end を切る
    i_next = i_prev + 1
    valid_next = i_next < len(fs_np)

    end_trim = end_np.copy()

    use_next_trim = np.zeros(len(t_np), dtype=bool)
    use_next_trim[valid_next] = (
        fs_np[i_next[valid_next]] < end_np[valid_next]
    )

    end_trim[use_next_trim] = (
        fs_np[i_next[use_next_trim]] - np.timedelta64(eps.value, "ns")
    )

    valid = (~inside_forbidden) & (end_trim > start_trim)

    start_out = pd.to_datetime(start_trim[valid])
    end_out   = pd.to_datetime(end_trim[valid])

    return list(zip(start_out, end_out))


def merge_time_ranges(
    time_ranges,
    max_duration=None,
):
    """
    overlapping time ranges を merge する。
    max_duration を指定した場合は、それを超える merge はしない。
    """

    if len(time_ranges) == 0:
        return []

    time_ranges = sorted(time_ranges)

    merged = []

    for start, end in time_ranges:
        if not merged:
            merged.append((start, end))
            continue

        prev_start, prev_end = merged[-1]

        is_overlapping = start <= prev_end

        candidate_start = prev_start
        candidate_end = max(prev_end, end)

        if max_duration is None:
            ok_duration = True
        else:
            ok_duration = (candidate_end - candidate_start) <= max_duration

        if is_overlapping and ok_duration:
            merged[-1] = (candidate_start, candidate_end)
        else:
            merged.append((start, end))

    return merged

In [52]:
bad_spin_angle_intervals_df = point_times_to_intervals(bad_times_spin_angle)

print(f"spin-angle bad intervals: {len(bad_spin_angle_intervals_df)}")
display(bad_spin_angle_intervals_df)

spin-angle bad intervals: 2445

                        start_time                      end_time
0    2020-03-01 06:28:56.018297088 2020-03-01 06:40:37.981401088
1    2020-03-01 06:40:38.012601344 2020-03-01 06:40:38.075001088
2    2020-03-01 06:40:38.106301184 2020-03-01 06:40:38.121901056
3    2020-03-01 06:40:38.153101056 2020-03-01 06:40:38.231201024
4    2020-03-01 06:40:38.309301248 2020-03-01 06:40:38.309301248
...                            ...                           ...
2440 2020-03-31 14:59:45.576531968 2020-03-31 15:00:17.542362112
2441 2020-03-31 15:00:17.573661952 2020-03-31 15:00:41.544009216
2442 2020-03-31 15:00:41.575208960 2020-03-31 15:01:03.656074240
2443 2020-03-31 15:11:14.661348096 2020-03-31 15:18:05.641579264
2444 2020-03-31 15:42:56.644468992 2020-03-31 15:54:41.642597888

[2445 rows x 2 columns]

In [53]:
import time

t0_clock = time.perf_counter()

# ============================================================
# forbidden intervals:
# EFD spec bad + MGF bad + spin angle bad + EFD wave bad
# + LEPe gap + LEPi gap + HFA L3 gap + MGF gap + EFD wave gap + ATT gap
# ============================================================

forbidden_intervals_mono_df = make_forbidden_intervals_for_mono(
    bad_times=bad_times,
    bad_times_mgf=bad_times_mgf,
    bad_times_spin_angle=bad_times_spin_angle,
    bad_times_efd_wave=bad_times_efd_wave,
    LEPe_gap_ranges_df=LEPe_omniflux_gap_ranges_df,
    LEPi_gap_ranges_df=LEPi_omniflux_gap_ranges_df,
    HFA_gap_ranges_df=HFA_L3_gap_ranges_df,
    mgf_gap_ranges_df=mgf_gap_ranges_df,
    efd_wave_gap_ranges_df=efd_wave_gap_ranges_df,
    att_gap_ranges_df=att_nan_intervals_df,
    merge=True,
)

elapsed = time.perf_counter() - t0_clock

print(f"forbidden intervals after merge: {len(forbidden_intervals_mono_df)}")
print(f"elapsed: {elapsed:.2f} sec")
forbidden_intervals_mono_df

forbidden intervals after merge: 2823
elapsed: 0.16 sec

                        start_time                      end_time
0    2020-03-01 00:00:13.064606000 2020-03-01 00:07:37.057405000
1    2020-03-01 00:50:29.054782976 2020-03-01 00:56:24.065616896
2    2020-03-01 01:05:05.071563937 2020-03-01 01:41:14.041179000
3    2020-03-01 01:41:16.030366720 2020-03-01 01:44:41.051211008
4    2020-03-01 01:44:43.039767000 2020-03-01 01:52:00.041287000
...                            ...                           ...
2818 2020-03-31 16:53:28.618103296 2020-03-31 17:26:50.618416128
2819 2020-03-31 20:00:08.579899000 2020-03-31 20:07:37.585025000
2820 2020-03-31 20:43:17.579666000 2020-03-31 23:40:00.678999808
2821 2020-03-31 23:42:16.673274000 2020-03-31 23:46:00.659858000
2822 2020-03-31 23:46:48.660346000 2020-03-31 23:59:44.621380000

[2823 rows x 2 columns]

In [54]:
# 確認用
bad_times_efd_pd = _as_datetime_index_from_time_da(bad_times)
bad_times_mgf_pd = _as_datetime_index_from_time_da(bad_times_mgf)
bad_times_spin_angle_pd = _as_datetime_index_from_time_da(bad_times_spin_angle)
bad_times_efd_wave_pd = _as_datetime_index_from_time_da(bad_times_efd_wave)

print(f"EFD spec bad_times: {len(bad_times_efd_pd)}")
print(f"MGF qf bad_times: {len(bad_times_mgf_pd)}")
print(f"Spin angle bad_times: {len(bad_times_spin_angle_pd)}")
print(f"EFD wave qf bad_times: {len(bad_times_efd_wave_pd)}")
print(f"LEPe gaps: {len(LEPe_omniflux_gap_ranges_df) if LEPe_omniflux_gap_ranges_df is not None else 0}")
print(f"LEPi gaps: {len(LEPi_omniflux_gap_ranges_df) if LEPi_omniflux_gap_ranges_df is not None else 0}")
print(f"HFA L3 gaps: {len(HFA_L3_gap_ranges_df) if HFA_L3_gap_ranges_df is not None else 0}")
print(f"MGF time gaps: {len(mgf_gap_ranges_df) if mgf_gap_ranges_df is not None else 0}")
print(f"EFD wave time gaps: {len(efd_wave_gap_ranges_df) if efd_wave_gap_ranges_df is not None else 0}")
print(f"ATT gaps: {len(att_nan_intervals_df) if att_nan_intervals_df is not None else 0}")


# ============================================================
# selected_times_mono ±200 sec を forbidden intervals で切る
# ============================================================

t0_clock = time.perf_counter()

time_ranges_mono = make_trimmed_time_ranges_by_forbidden(
    selected_times=selected_times_mono,
    forbidden_intervals_df=forbidden_intervals_mono_df,
    half_width=EVENT_HALF_WIDTH,
    eps=pd.Timedelta(nanoseconds=1),
)

print(f"time ranges before merge: {len(time_ranges_mono)}")


# ============================================================
# Merge overlapping time ranges
# ============================================================

merged_ranges_mono = merge_time_ranges(
    time_ranges_mono,
    max_duration=None,
)


# ============================================================
# DataFrame 化
# ============================================================

merged_ranges_mono_df = pd.DataFrame(
    merged_ranges_mono,
    columns=["start_time", "end_time"]
)

if len(merged_ranges_mono_df) > 0:
    merged_ranges_mono_df["duration_sec"] = (
        merged_ranges_mono_df["end_time"] - merged_ranges_mono_df["start_time"]
    ).dt.total_seconds()
    merged_ranges_mono_df["duration_minutes"] = merged_ranges_mono_df["duration_sec"] / 60

    # 400秒以上の時間範囲のみ有効にする
    merged_ranges_mono_df = merged_ranges_mono_df[
        merged_ranges_mono_df["duration_sec"] >= MIN_EVENT_DURATION.total_seconds()
    ].reset_index(drop=True)
else:
    merged_ranges_mono_df["duration_sec"] = []
    merged_ranges_mono_df["duration_minutes"] = []

elapsed = time.perf_counter() - t0_clock

print(f"元の selected_times_mono 数: {len(selected_times_mono)}")
print(f"400秒以上のマージ後時間範囲数: {len(merged_ranges_mono_df)}")
print(f"elapsed: {elapsed:.2f} sec")
print("\n有効なマージ時間範囲:")
print(merged_ranges_mono_df)

EFD spec bad_times: 378905
MGF qf bad_times: 1585
Spin angle bad_times: 4620345
EFD wave qf bad_times: 0
LEPe gaps: 241
LEPi gaps: 155
HFA L3 gaps: 223
MGF time gaps: 385
EFD wave time gaps: 7
ATT gaps: 96
time ranges before merge: 533
元の selected_times_mono 数: 716
400秒以上のマージ後時間範囲数: 210
elapsed: 0.01 sec

有効なマージ時間範囲:
                    start_time                   end_time  duration_sec  \
0   2020-03-01 00:13:26.058598 2020-03-01 00:20:06.058598    400.000000
1   2020-03-01 00:56:26.056025 2020-03-01 01:03:06.056025    400.000000
2   2020-03-01 07:17:45.015339 2020-03-01 07:24:25.015339    400.000000
3   2020-03-01 08:18:44.985669 2020-03-01 08:26:52.986725    488.001056
4   2020-03-01 08:49:28.989212 2020-03-01 08:56:08.989212    400.000000
..                         ...                        ...           ...
205 2020-03-30 14:19:42.835812 2020-03-30 14:26:22.835812    400.000000
206 2020-03-30 14:30:44.828387 2020-03-30 14:37:24.828387    400.000000
207 2020-03-30 14:43:32.825893 2020-03-30 14:50:12.825893    400.000000
208 2020-03-30 15:22:52.820368 2020-03-30 15:29:32.820368    400.000000
209 2020-03-30 22:18:57.899974 2020-03-30 22:25:37.899974    400.000000

     duration_minutes
0            6.666667
1            6.666667
2            6.666667
3            8.133351
4            6.666667
..                ...
205          6.666667
206          6.666667
207          6.666667
208          6.666667
209          6.666667

[210 rows x 4 columns]

In [55]:
from pathlib import Path
from tqdm.auto import tqdm
import numpy as np
import pandas as pd
from matplotlib.colors import Normalize
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

path_base_save_plot = f'/mnt/j/statistical_analysis_arase/preanalysis'
path_base_save_plot = Path(path_base_save_plot + f'/PWE-EFD_spec_after_B')
os.makedirs(path_base_save_plot, exist_ok=True)

def edges_numeric(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.size < 2:
        return np.concatenate((arr, arr + 1.0))
    d = np.diff(arr) / 2.0
    return np.concatenate(([arr[0] - d[0]], arr[:-1] + d, [arr[-1] + d[-1]]))

vmax = np.log10(1E1)
vmin = np.log10(1e-4)

for idx, row in tqdm(merged_ranges_mono_df.iterrows(), total=len(merged_ranges_mono_df), desc="Saving PWE-EFD spec plots"):
    start = row["start_time"]
    end = row["end_time"]

    if pd.isna(start) or pd.isna(end):
        continue

    subset_range = efd_spectra_qf.sel(time=slice(start, end))

    if subset_range.sizes.get("time", 0) < 2:
        continue

    times = pd.to_datetime(subset_range.time.values)

    if "spec_bins" in subset_range.coords:
        freqs = subset_range["spec_bins"].values
    elif "v" in subset_range.coords:
        freqs = subset_range["v"].values
    else:
        freqs = np.arange(subset_range.sizes["v_dim"])

    data_range = subset_range.values
    data_range = np.where(
        np.isfinite(data_range) & (data_range > 0),
        data_range,
        np.nan
    )

    logdata_range = np.log10(data_range)

    if np.isnan(logdata_range).all():
        continue

    t_num = mdates.date2num(times.to_pydatetime())
    t_edges = edges_numeric(t_num)
    f_edges = edges_numeric(freqs)

    fig_i, ax_i = plt.subplots(figsize=(12, 4.5))

    pcm_i = ax_i.pcolormesh(
        t_edges,
        f_edges,
        logdata_range.T,
        shading="auto",
        cmap="turbo",
        norm=Normalize(vmin=vmin, vmax=vmax),
    )

    f_cH_plot = f_cH.sel(time=slice(start, end))
    f_cHe_plot = f_cHe.sel(time=slice(start, end))
    f_cO_plot = f_cO.sel(time=slice(start, end))

    ax_i.plot(f_cH_plot.time, f_cH_plot.data, lw=1, c='white', linestyle='solid')
    ax_i.plot(f_cHe_plot.time, f_cHe_plot.data, lw=1, c='magenta', linestyle='solid')
    ax_i.plot(f_cO_plot.time, f_cO_plot.data, lw=1, c='yellow', linestyle='solid')

    ax_i.set_xlabel("Time")
    ax_i.xaxis_date()
    ax_i.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))
    ax_i.set_ylabel("Frequency [Hz]")
    ax_i.set_title(
        f"PWE-EFD spec ({start:%Y-%m-%d %H:%M:%S} - {end:%Y-%m-%d %H:%M:%S})"
    )
    ax_i.set_yscale("log")
    ax_i.set_ylim(3, 32)
    ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

    fig_i.colorbar(pcm_i, ax=ax_i, label=r"log10 PSD [$\mathrm{(mV/m)}^2/\mathrm{Hz}$]")
    plt.tight_layout()

    # =========================
    # save figure
    # =========================

    # start の月・日で階層フォルダを作る
    save_dir = path_base_save_plot / f"{start:%Y}" / f"{start:%m}"
    save_dir.mkdir(parents=True, exist_ok=True)

    filename = (
        f"efd_spectra_qf_"
        f"{start:%Y%m%d_%H%M%S}_to_{end:%Y%m%d_%H%M%S}.png"
    )

    save_path = save_dir / filename

    fig_i.savefig(save_path, dpi=200, bbox_inches="tight")
    plt.close(fig_i)

    print(f"saved: {save_path}")

Saving PWE-EFD spec plots:   0%|          | 1/210 [00:00<02:42,  1.28it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_001326_to_20200301_002006.png

Saving PWE-EFD spec plots:   1%|          | 2/210 [00:01<02:27,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_005626_to_20200301_010306.png

Saving PWE-EFD spec plots:   1%|▏         | 3/210 [00:02<02:22,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_071745_to_20200301_072425.png

Saving PWE-EFD spec plots:   2%|▏         | 4/210 [00:02<02:14,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_081844_to_20200301_082652.png

Saving PWE-EFD spec plots:   2%|▏         | 5/210 [00:03<02:29,  1.37it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_084928_to_20200301_085608.png

Saving PWE-EFD spec plots:   3%|▎         | 6/210 [00:04<02:24,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_085838_to_20200301_091707.png

Saving PWE-EFD spec plots:   3%|▎         | 7/210 [00:04<02:19,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_092641_to_20200301_093550.png

Saving PWE-EFD spec plots:   4%|▍         | 8/210 [00:05<02:17,  1.47it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_093601_to_20200301_094241.png

Saving PWE-EFD spec plots:   4%|▍         | 9/210 [00:06<02:14,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_094506_to_20200301_095146.png

Saving PWE-EFD spec plots:   5%|▍         | 10/210 [00:06<02:10,  1.53it/s]29-Sep-26 19:24:03: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_095727_to_20200301_100407.png

Saving PWE-EFD spec plots:   5%|▌         | 11/210 [00:07<02:09,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_100631_to_20200301_101506.png

Saving PWE-EFD spec plots:   6%|▌         | 12/210 [00:08<02:08,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_101804_to_20200301_103158.png

Saving PWE-EFD spec plots:   6%|▌         | 13/210 [00:08<02:15,  1.46it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_103553_to_20200301_105359.png

Saving PWE-EFD spec plots:   7%|▋         | 14/210 [00:09<02:12,  1.48it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_111114_to_20200301_111754.png

Saving PWE-EFD spec plots:   7%|▋         | 15/210 [00:10<02:13,  1.46it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200301_111937_to_20200301_113513.png

Saving PWE-EFD spec plots:   8%|▊         | 16/210 [00:10<02:13,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_070541_to_20200303_072509.png

Saving PWE-EFD spec plots:   8%|▊         | 17/210 [00:11<02:09,  1.49it/s]29-Sep-26 19:24:08: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_072545_to_20200303_073225.png

Saving PWE-EFD spec plots:   9%|▊         | 18/210 [00:12<02:06,  1.51it/s]29-Sep-26 19:24:09: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_074144_to_20200303_074949.png

Saving PWE-EFD spec plots:   9%|▉         | 19/210 [00:12<02:10,  1.46it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_080829_to_20200303_081827.png

Saving PWE-EFD spec plots:  10%|▉         | 20/210 [00:13<02:06,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_082106_to_20200303_082746.png

Saving PWE-EFD spec plots:  10%|█         | 21/210 [00:14<02:01,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_083515_to_20200303_084155.png

Saving PWE-EFD spec plots:  10%|█         | 22/210 [00:14<02:02,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_085826_to_20200303_090747.png

Saving PWE-EFD spec plots:  11%|█         | 23/210 [00:15<02:01,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_091609_to_20200303_092249.png

Saving PWE-EFD spec plots:  11%|█▏        | 24/210 [00:16<02:03,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_092841_to_20200303_095130.png

Saving PWE-EFD spec plots:  12%|█▏        | 25/210 [00:16<02:00,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_095543_to_20200303_100223.png

Saving PWE-EFD spec plots:  12%|█▏        | 26/210 [00:17<01:59,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_171653_to_20200303_172333.png

Saving PWE-EFD spec plots:  13%|█▎        | 27/210 [00:18<01:59,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_172704_to_20200303_173804.png

Saving PWE-EFD spec plots:  13%|█▎        | 28/210 [00:18<01:58,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_180522_to_20200303_181836.png

Saving PWE-EFD spec plots:  14%|█▍        | 29/210 [00:19<01:57,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_182345_to_20200303_183206.png

Saving PWE-EFD spec plots:  14%|█▍        | 30/210 [00:20<01:56,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200303_193048_to_20200303_193728.png

Saving PWE-EFD spec plots:  15%|█▍        | 31/210 [00:20<02:11,  1.36it/s]29-Sep-26 19:24:17: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_042802_to_20200304_043442.png

Saving PWE-EFD spec plots:  15%|█▌        | 32/210 [00:21<02:04,  1.43it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_111108_to_20200304_111914.png

Saving PWE-EFD spec plots:  16%|█▌        | 33/210 [00:22<02:01,  1.46it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_112710_to_20200304_113350.png

Saving PWE-EFD spec plots:  16%|█▌        | 34/210 [00:22<01:59,  1.48it/s]29-Sep-26 19:24:19: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_113833_to_20200304_115535.png

Saving PWE-EFD spec plots:  17%|█▋        | 35/210 [00:23<02:02,  1.42it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_120829_to_20200304_124818.png

Saving PWE-EFD spec plots:  17%|█▋        | 36/210 [00:24<02:01,  1.43it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_125014_to_20200304_131456.png

Saving PWE-EFD spec plots:  18%|█▊        | 37/210 [00:25<02:02,  1.42it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_132820_to_20200304_135313.png

Saving PWE-EFD spec plots:  18%|█▊        | 38/210 [00:25<01:57,  1.46it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_135314_to_20200304_141405.png

Saving PWE-EFD spec plots:  19%|█▊        | 39/210 [00:26<01:57,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_141731_to_20200304_143350.png

Saving PWE-EFD spec plots:  19%|█▉        | 40/210 [00:27<01:53,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_143454_to_20200304_144640.png

Saving PWE-EFD spec plots:  20%|█▉        | 41/210 [00:27<01:50,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_152414_to_20200304_153054.png

Saving PWE-EFD spec plots:  20%|██        | 42/210 [00:28<01:47,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200304_153230_to_20200304_153914.png

Saving PWE-EFD spec plots:  20%|██        | 43/210 [00:28<01:47,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_063646_to_20200305_064730.png

Saving PWE-EFD spec plots:  21%|██        | 44/210 [00:29<01:46,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_082116_to_20200305_082756.png

Saving PWE-EFD spec plots:  21%|██▏       | 45/210 [00:30<01:49,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_083020_to_20200305_083700.png

Saving PWE-EFD spec plots:  22%|██▏       | 46/210 [00:30<01:51,  1.47it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_084149_to_20200305_084829.png

Saving PWE-EFD spec plots:  22%|██▏       | 47/210 [00:31<01:47,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_084908_to_20200305_085548.png

Saving PWE-EFD spec plots:  23%|██▎       | 48/210 [00:32<01:45,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_085917_to_20200305_090557.png

Saving PWE-EFD spec plots:  23%|██▎       | 49/210 [00:32<01:43,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200305_091126_to_20200305_091806.png

Saving PWE-EFD spec plots:  24%|██▍       | 50/210 [00:33<01:43,  1.54it/s]29-Sep-26 19:24:30: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_102350_to_20200306_103415.png

Saving PWE-EFD spec plots:  24%|██▍       | 51/210 [00:34<01:39,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_120829_to_20200306_122443.png

Saving PWE-EFD spec plots:  25%|██▍       | 52/210 [00:34<01:42,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_122455_to_20200306_124135.png

Saving PWE-EFD spec plots:  25%|██▌       | 53/210 [00:35<01:37,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_124550_to_20200306_125230.png

Saving PWE-EFD spec plots:  26%|██▌       | 54/210 [00:35<01:35,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_125700_to_20200306_131039.png

Saving PWE-EFD spec plots:  26%|██▌       | 55/210 [00:36<01:36,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_133902_to_20200306_134542.png

Saving PWE-EFD spec plots:  27%|██▋       | 56/210 [00:37<01:36,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200306_142647_to_20200306_143414.png

Saving PWE-EFD spec plots:  27%|██▋       | 57/210 [00:37<01:35,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_053303_to_20200307_053943.png

Saving PWE-EFD spec plots:  28%|██▊       | 58/210 [00:38<01:31,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_054414_to_20200307_055630.png

Saving PWE-EFD spec plots:  28%|██▊       | 59/210 [00:38<01:30,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_060753_to_20200307_062427.png

Saving PWE-EFD spec plots:  29%|██▊       | 60/210 [00:39<01:28,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_062655_to_20200307_063903.png

Saving PWE-EFD spec plots:  29%|██▉       | 61/210 [00:40<01:27,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_063941_to_20200307_064621.png

Saving PWE-EFD spec plots:  30%|██▉       | 62/210 [00:41<01:44,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_072351_to_20200307_073134.png

Saving PWE-EFD spec plots:  30%|███       | 63/210 [00:41<01:36,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_073443_to_20200307_074123.png

Saving PWE-EFD spec plots:  30%|███       | 64/210 [00:42<01:34,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_074438_to_20200307_075736.png

Saving PWE-EFD spec plots:  31%|███       | 65/210 [00:42<01:31,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_081701_to_20200307_083033.png

Saving PWE-EFD spec plots:  31%|███▏      | 66/210 [00:43<01:35,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_083847_to_20200307_084527.png

Saving PWE-EFD spec plots:  32%|███▏      | 67/210 [00:44<01:31,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_084546_to_20200307_085431.png

Saving PWE-EFD spec plots:  32%|███▏      | 68/210 [00:44<01:32,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_085909_to_20200307_091601.png

Saving PWE-EFD spec plots:  33%|███▎      | 69/210 [00:45<01:31,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200307_092201_to_20200307_092841.png

Saving PWE-EFD spec plots:  33%|███▎      | 70/210 [00:46<01:30,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_093314_to_20200308_093954.png

Saving PWE-EFD spec plots:  34%|███▍      | 71/210 [00:46<01:29,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_094723_to_20200308_095614.png

Saving PWE-EFD spec plots:  34%|███▍      | 72/210 [00:47<01:31,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_095958_to_20200308_100805.png

Saving PWE-EFD spec plots:  35%|███▍      | 73/210 [00:48<01:30,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_101545_to_20200308_102649.png

Saving PWE-EFD spec plots:  35%|███▌      | 74/210 [00:48<01:29,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_102732_to_20200308_103412.png

Saving PWE-EFD spec plots:  36%|███▌      | 75/210 [00:49<01:27,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_104941_to_20200308_105621.png

Saving PWE-EFD spec plots:  36%|███▌      | 76/210 [00:49<01:23,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_110605_to_20200308_111248.png

Saving PWE-EFD spec plots:  37%|███▋      | 77/210 [00:50<01:22,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_111724_to_20200308_112404.png

Saving PWE-EFD spec plots:  37%|███▋      | 78/210 [00:51<01:22,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_114710_to_20200308_115350.png

Saving PWE-EFD spec plots:  38%|███▊      | 79/210 [00:51<01:21,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_125810_to_20200308_130450.png

Saving PWE-EFD spec plots:  38%|███▊      | 80/210 [00:52<01:20,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_131033_to_20200308_131713.png

Saving PWE-EFD spec plots:  39%|███▊      | 81/210 [00:53<01:19,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_131725_to_20200308_132405.png

Saving PWE-EFD spec plots:  39%|███▉      | 82/210 [00:53<01:18,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_132529_to_20200308_133306.png

Saving PWE-EFD spec plots:  40%|███▉      | 83/210 [00:54<01:18,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_134000_to_20200308_135429.png

Saving PWE-EFD spec plots:  40%|████      | 84/210 [00:54<01:15,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_140553_to_20200308_141241.png

Saving PWE-EFD spec plots:  40%|████      | 85/210 [00:55<01:17,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_205340_to_20200308_210245.png

Saving PWE-EFD spec plots:  41%|████      | 86/210 [00:56<01:17,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_210740_to_20200308_211420.png

Saving PWE-EFD spec plots:  41%|████▏     | 87/210 [00:56<01:14,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200308_211531_to_20200308_212211.png

Saving PWE-EFD spec plots:  42%|████▏     | 88/210 [00:57<01:16,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200309_050107_to_20200309_050747.png

Saving PWE-EFD spec plots:  42%|████▏     | 89/210 [00:58<01:15,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200309_062616_to_20200309_063356.png

Saving PWE-EFD spec plots:  43%|████▎     | 90/210 [00:58<01:16,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200309_063510_to_20200309_064153.png

Saving PWE-EFD spec plots:  43%|████▎     | 91/210 [00:59<01:15,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200309_181755_to_20200309_182435.png

Saving PWE-EFD spec plots:  44%|████▍     | 92/210 [00:59<01:14,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_001118_to_20200310_001758.png

Saving PWE-EFD spec plots:  44%|████▍     | 93/210 [01:00<01:15,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_082106_to_20200310_082746.png

Saving PWE-EFD spec plots:  45%|████▍     | 94/210 [01:01<01:15,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_090620_to_20200310_091300.png

Saving PWE-EFD spec plots:  45%|████▌     | 95/210 [01:01<01:13,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_091706_to_20200310_092346.png

Saving PWE-EFD spec plots:  46%|████▌     | 96/210 [01:02<01:12,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_110935_to_20200310_112311.png

Saving PWE-EFD spec plots:  46%|████▌     | 97/210 [01:03<01:26,  1.30it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_113642_to_20200310_114541.png

Saving PWE-EFD spec plots:  47%|████▋     | 98/210 [01:04<01:21,  1.37it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_115002_to_20200310_115642.png

Saving PWE-EFD spec plots:  47%|████▋     | 99/210 [01:04<01:16,  1.44it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_123631_to_20200310_124311.png

Saving PWE-EFD spec plots:  48%|████▊     | 100/210 [01:05<01:12,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_124601_to_20200310_125442.png

Saving PWE-EFD spec plots:  48%|████▊     | 101/210 [01:06<01:10,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200310_130110_to_20200310_130750.png

Saving PWE-EFD spec plots:  49%|████▊     | 102/210 [01:06<01:09,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200312_081636_to_20200312_082354.png

Saving PWE-EFD spec plots:  49%|████▉     | 103/210 [01:07<01:08,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200312_092151_to_20200312_093351.png

Saving PWE-EFD spec plots:  50%|████▉     | 104/210 [01:07<01:07,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200312_095506_to_20200312_100146.png

Saving PWE-EFD spec plots:  50%|█████     | 105/210 [01:08<01:07,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200313_070129_to_20200313_071020.png

Saving PWE-EFD spec plots:  50%|█████     | 106/210 [01:09<01:05,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200314_100414_to_20200314_101054.png

Saving PWE-EFD spec plots:  51%|█████     | 107/210 [01:09<01:06,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200314_104417_to_20200314_105506.png

Saving PWE-EFD spec plots:  51%|█████▏    | 108/210 [01:10<01:01,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200314_113326_to_20200314_114006.png

Saving PWE-EFD spec plots:  52%|█████▏    | 109/210 [01:10<00:59,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200316_073459_to_20200316_074139.png

Saving PWE-EFD spec plots:  52%|█████▏    | 110/210 [01:11<01:00,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200316_083550_to_20200316_084230.png

Saving PWE-EFD spec plots:  53%|█████▎    | 111/210 [01:12<01:00,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200316_085220_to_20200316_090129.png

Saving PWE-EFD spec plots:  53%|█████▎    | 112/210 [01:12<01:00,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_121056_to_20200317_121736.png

Saving PWE-EFD spec plots:  54%|█████▍    | 113/210 [01:13<00:59,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_123118_to_20200317_123758.png

Saving PWE-EFD spec plots:  54%|█████▍    | 114/210 [01:14<00:58,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_124342_to_20200317_125022.png

Saving PWE-EFD spec plots:  55%|█████▍    | 115/210 [01:14<00:56,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_142416_to_20200317_143614.png

Saving PWE-EFD spec plots:  55%|█████▌    | 116/210 [01:15<00:56,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_145459_to_20200317_150139.png

Saving PWE-EFD spec plots:  56%|█████▌    | 117/210 [01:15<00:53,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_150702_to_20200317_151343.png

Saving PWE-EFD spec plots:  56%|█████▌    | 118/210 [01:16<00:54,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_154107_to_20200317_155318.png

Saving PWE-EFD spec plots:  57%|█████▋    | 119/210 [01:17<01:12,  1.25it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_220606_to_20200317_221246.png

Saving PWE-EFD spec plots:  57%|█████▋    | 120/210 [01:18<01:07,  1.34it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200317_231154_to_20200317_231834.png

Saving PWE-EFD spec plots:  58%|█████▊    | 121/210 [01:18<01:03,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200318_070527_to_20200318_071207.png

Saving PWE-EFD spec plots:  58%|█████▊    | 122/210 [01:19<00:59,  1.47it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200318_073114_to_20200318_073754.png

Saving PWE-EFD spec plots:  59%|█████▊    | 123/210 [01:20<00:56,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200318_170947_to_20200318_171627.png

Saving PWE-EFD spec plots:  59%|█████▉    | 124/210 [01:20<00:56,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200318_172142_to_20200318_174204.png

Saving PWE-EFD spec plots:  60%|█████▉    | 125/210 [01:21<00:53,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200318_182311_to_20200318_183506.png

Saving PWE-EFD spec plots:  60%|██████    | 126/210 [01:21<00:50,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_005007_to_20200319_005647.png

Saving PWE-EFD spec plots:  60%|██████    | 127/210 [01:22<00:49,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_012259_to_20200319_013721.png

Saving PWE-EFD spec plots:  61%|██████    | 128/210 [01:23<00:47,  1.72it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_081931_to_20200319_082611.png

Saving PWE-EFD spec plots:  61%|██████▏   | 129/210 [01:23<00:46,  1.75it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_105554_to_20200319_110234.png

Saving PWE-EFD spec plots:  62%|██████▏   | 130/210 [01:24<00:44,  1.79it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_111108_to_20200319_111748.png

Saving PWE-EFD spec plots:  62%|██████▏   | 131/210 [01:24<00:44,  1.79it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_111926_to_20200319_112606.png

Saving PWE-EFD spec plots:  63%|██████▎   | 132/210 [01:25<00:43,  1.78it/s]29-Sep-26 19:25:22: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_113452_to_20200319_114140.png

Saving PWE-EFD spec plots:  63%|██████▎   | 133/210 [01:26<00:50,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_114842_to_20200319_115930.png

Saving PWE-EFD spec plots:  64%|██████▍   | 134/210 [01:26<00:49,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_121109_to_20200319_122009.png

Saving PWE-EFD spec plots:  64%|██████▍   | 135/210 [01:27<00:48,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_123203_to_20200319_124100.png

Saving PWE-EFD spec plots:  65%|██████▍   | 136/210 [01:28<00:47,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_124114_to_20200319_124754.png

Saving PWE-EFD spec plots:  65%|██████▌   | 137/210 [01:28<00:46,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_130140_to_20200319_131454.png

Saving PWE-EFD spec plots:  66%|██████▌   | 138/210 [01:29<00:58,  1.24it/s]29-Sep-26 19:25:26: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_131612_to_20200319_134020.png

Saving PWE-EFD spec plots:  66%|██████▌   | 139/210 [01:30<00:58,  1.22it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_142608_to_20200319_144823.png

Saving PWE-EFD spec plots:  67%|██████▋   | 140/210 [01:31<00:53,  1.30it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_145904_to_20200319_150717.png

Saving PWE-EFD spec plots:  67%|██████▋   | 141/210 [01:31<00:49,  1.39it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_212120_to_20200319_212800.png

Saving PWE-EFD spec plots:  68%|██████▊   | 142/210 [01:32<00:45,  1.48it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200319_221347_to_20200319_222027.png

Saving PWE-EFD spec plots:  68%|██████▊   | 143/210 [01:33<00:44,  1.49it/s]29-Sep-26 19:25:30: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_152726_to_20200320_154007.png

Saving PWE-EFD spec plots:  69%|██████▊   | 144/210 [01:33<00:42,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_155223_to_20200320_160008.png

Saving PWE-EFD spec plots:  69%|██████▉   | 145/210 [01:34<00:41,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_160908_to_20200320_163010.png

Saving PWE-EFD spec plots:  70%|██████▉   | 146/210 [01:34<00:40,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_163608_to_20200320_164816.png

Saving PWE-EFD spec plots:  70%|███████   | 147/210 [01:35<00:38,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_170131_to_20200320_171102.png

Saving PWE-EFD spec plots:  70%|███████   | 148/210 [01:36<00:36,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_171327_to_20200320_172007.png

Saving PWE-EFD spec plots:  71%|███████   | 149/210 [01:36<00:34,  1.75it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_172728_to_20200320_173408.png

Saving PWE-EFD spec plots:  71%|███████▏  | 150/210 [01:37<00:33,  1.80it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_173922_to_20200320_174602.png

Saving PWE-EFD spec plots:  72%|███████▏  | 151/210 [01:37<00:34,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_180624_to_20200320_181656.png

Saving PWE-EFD spec plots:  72%|███████▏  | 152/210 [01:38<00:32,  1.77it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200320_193422_to_20200320_194102.png

Saving PWE-EFD spec plots:  73%|███████▎  | 153/210 [01:38<00:33,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_094446_to_20200321_095126.png

Saving PWE-EFD spec plots:  73%|███████▎  | 154/210 [01:39<00:33,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_100504_to_20200321_101144.png

Saving PWE-EFD spec plots:  74%|███████▍  | 155/210 [01:40<00:33,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_103005_to_20200321_104431.png

Saving PWE-EFD spec plots:  74%|███████▍  | 156/210 [01:40<00:32,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_112604_to_20200321_113244.png

Saving PWE-EFD spec plots:  75%|███████▍  | 157/210 [01:41<00:32,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_114003_to_20200321_115600.png

Saving PWE-EFD spec plots:  75%|███████▌  | 158/210 [01:42<00:32,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_122317_to_20200321_122957.png

Saving PWE-EFD spec plots:  76%|███████▌  | 159/210 [01:42<00:31,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_125431_to_20200321_131428.png

Saving PWE-EFD spec plots:  76%|███████▌  | 160/210 [01:43<00:31,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_133454_to_20200321_134134.png

Saving PWE-EFD spec plots:  77%|███████▋  | 161/210 [01:43<00:30,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200321_141545_to_20200321_142225.png

Saving PWE-EFD spec plots:  77%|███████▋  | 162/210 [01:44<00:30,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200322_061515_to_20200322_062155.png

Saving PWE-EFD spec plots:  78%|███████▊  | 163/210 [01:45<00:30,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200322_064239_to_20200322_064919.png

Saving PWE-EFD spec plots:  78%|███████▊  | 164/210 [01:45<00:30,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200322_181544_to_20200322_182224.png

Saving PWE-EFD spec plots:  79%|███████▊  | 165/210 [01:46<00:28,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_011308_to_20200323_012455.png

Saving PWE-EFD spec plots:  79%|███████▉  | 166/210 [01:47<00:26,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_015843_to_20200323_020523.png

Saving PWE-EFD spec plots:  80%|███████▉  | 167/210 [01:47<00:25,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_023056_to_20200323_023736.png

Saving PWE-EFD spec plots:  80%|████████  | 168/210 [01:48<00:23,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_032822_to_20200323_033502.png

Saving PWE-EFD spec plots:  80%|████████  | 169/210 [01:48<00:23,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_065142_to_20200323_065822.png

Saving PWE-EFD spec plots:  81%|████████  | 170/210 [01:49<00:23,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_101431_to_20200323_102111.png

Saving PWE-EFD spec plots:  81%|████████▏ | 171/210 [01:49<00:22,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_102143_to_20200323_102823.png

Saving PWE-EFD spec plots:  82%|████████▏ | 172/210 [01:50<00:22,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_104842_to_20200323_105902.png

Saving PWE-EFD spec plots:  82%|████████▏ | 173/210 [01:51<00:22,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_111214_to_20200323_111854.png

Saving PWE-EFD spec plots:  83%|████████▎ | 174/210 [01:51<00:21,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_113913_to_20200323_114553.png

Saving PWE-EFD spec plots:  83%|████████▎ | 175/210 [01:52<00:20,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_122111_to_20200323_122751.png

Saving PWE-EFD spec plots:  84%|████████▍ | 176/210 [01:52<00:20,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_124457_to_20200323_125459.png

Saving PWE-EFD spec plots:  84%|████████▍ | 177/210 [01:53<00:19,  1.67it/s]29-Sep-26 19:25:50: /tmp/ipykernel_91668/3675806032.py:88: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax_i.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_133516_to_20200323_134222.png

Saving PWE-EFD spec plots:  85%|████████▍ | 178/210 [01:54<00:19,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_165053_to_20200323_165920.png

Saving PWE-EFD spec plots:  85%|████████▌ | 179/210 [01:54<00:18,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_192935_to_20200323_193615.png

Saving PWE-EFD spec plots:  86%|████████▌ | 180/210 [01:55<00:17,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200323_195523_to_20200323_200223.png

Saving PWE-EFD spec plots:  86%|████████▌ | 181/210 [01:55<00:17,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200325_012617_to_20200325_013257.png

Saving PWE-EFD spec plots:  87%|████████▋ | 182/210 [01:56<00:16,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200325_110023_to_20200325_110703.png

Saving PWE-EFD spec plots:  87%|████████▋ | 183/210 [01:57<00:16,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200325_110859_to_20200325_112920.png

Saving PWE-EFD spec plots:  88%|████████▊ | 184/210 [01:58<00:20,  1.29it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200325_113145_to_20200325_114406.png

Saving PWE-EFD spec plots:  88%|████████▊ | 185/210 [01:58<00:17,  1.40it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200325_114905_to_20200325_115545.png

Saving PWE-EFD spec plots:  89%|████████▊ | 186/210 [01:59<00:16,  1.43it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200326_150136_to_20200326_150816.png

Saving PWE-EFD spec plots:  89%|████████▉ | 187/210 [02:00<00:16,  1.39it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200326_152318_to_20200326_153304.png

Saving PWE-EFD spec plots:  90%|████████▉ | 188/210 [02:01<00:16,  1.37it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200327_100211_to_20200327_101033.png

Saving PWE-EFD spec plots:  90%|█████████ | 189/210 [02:01<00:14,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200327_111948_to_20200327_112631.png

Saving PWE-EFD spec plots:  90%|█████████ | 190/210 [02:02<00:14,  1.43it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200327_180201_to_20200327_181057.png

Saving PWE-EFD spec plots:  91%|█████████ | 191/210 [02:03<00:13,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200328_123718_to_20200328_124731.png

Saving PWE-EFD spec plots:  91%|█████████▏| 192/210 [02:03<00:12,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200328_131835_to_20200328_132520.png

Saving PWE-EFD spec plots:  92%|█████████▏| 193/210 [02:04<00:11,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200328_224900_to_20200328_225540.png

Saving PWE-EFD spec plots:  92%|█████████▏| 194/210 [02:05<00:10,  1.48it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200328_231808_to_20200328_232530.png

Saving PWE-EFD spec plots:  93%|█████████▎| 195/210 [02:05<00:10,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200328_232612_to_20200328_233520.png

Saving PWE-EFD spec plots:  93%|█████████▎| 196/210 [02:06<00:10,  1.40it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200329_065150_to_20200329_065830.png

Saving PWE-EFD spec plots:  94%|█████████▍| 197/210 [02:07<00:08,  1.44it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200329_070755_to_20200329_072216.png

Saving PWE-EFD spec plots:  94%|█████████▍| 198/210 [02:07<00:08,  1.48it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200329_072312_to_20200329_072952.png

Saving PWE-EFD spec plots:  95%|█████████▍| 199/210 [02:08<00:07,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200329_074418_to_20200329_075536.png

Saving PWE-EFD spec plots:  95%|█████████▌| 200/210 [02:09<00:06,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200329_082350_to_20200329_083133.png

Saving PWE-EFD spec plots:  96%|█████████▌| 201/210 [02:09<00:05,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_092639_to_20200330_093319.png

Saving PWE-EFD spec plots:  96%|█████████▌| 202/210 [02:10<00:05,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_132142_to_20200330_134322.png

Saving PWE-EFD spec plots:  97%|█████████▋| 203/210 [02:10<00:04,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_134756_to_20200330_135436.png

Saving PWE-EFD spec plots:  97%|█████████▋| 204/210 [02:11<00:03,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_135500_to_20200330_140140.png

Saving PWE-EFD spec plots:  98%|█████████▊| 205/210 [02:12<00:03,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_141042_to_20200330_141722.png

Saving PWE-EFD spec plots:  98%|█████████▊| 206/210 [02:12<00:02,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_141942_to_20200330_142622.png

Saving PWE-EFD spec plots:  99%|█████████▊| 207/210 [02:13<00:01,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_143044_to_20200330_143724.png

Saving PWE-EFD spec plots:  99%|█████████▉| 208/210 [02:14<00:01,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_144332_to_20200330_145012.png

Saving PWE-EFD spec plots: 100%|█████████▉| 209/210 [02:14<00:00,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_152252_to_20200330_152932.png

Saving PWE-EFD spec plots: 100%|██████████| 210/210 [02:15<00:00,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/PWE-EFD_spec_after_B/2020/03/efd_spectra_qf_20200330_221857_to_20200330_222537.png

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import Normalize
from pathlib import Path
from tqdm.auto import tqdm


def edges_numeric(arr):
    arr = np.asarray(arr, dtype=float)
    if arr.size < 2:
        return np.concatenate((arr, arr + 1.0))
    d = np.diff(arr) / 2.0
    return np.concatenate(([arr[0] - d[0]], arr[:-1] + d, [arr[-1] + d[-1]]))


# ============================================================
# save base path
# ============================================================

path_base_save_plot = f'/mnt/j/statistical_analysis_arase/preanalysis'
path_base_save_plot = Path(path_base_save_plot + f'/MGF_spec_after_B')
os.makedirs(path_base_save_plot, exist_ok=True)



# ============================================================
# plot settings
# ============================================================

vmin = -4
vmax = -1

for idx, row in tqdm(merged_ranges_mono_df.iterrows(), total=len(merged_ranges_mono_df), desc="Saving MGF spec plots"):

    start = pd.to_datetime(row["start_time"])
    end   = pd.to_datetime(row["end_time"])

    if pd.isna(start) or pd.isna(end):
        continue

    f_cH_plot = f_cH.sel(time=slice(start, end))
    f_cHe_plot = f_cHe.sel(time=slice(start, end))
    f_cO_plot = f_cO.sel(time=slice(start, end))

    # xarray sel 用
    B64_spectra_qf_analysis = B64_spectra_qf.sel(
        time=slice(start, end)
    )

    # time が少なすぎる場合は skip
    if B64_spectra_qf_analysis.sizes.get("time", 0) < 2:
        print(f"skip: too few time points: {start} - {end}")
        continue

    data = B64_spectra_qf_analysis.values
    data = np.where(np.isfinite(data) & (data > 0), data, np.nan)

    if np.isnan(data).all():
        print(f"skip: all NaN: {start} - {end}")
        continue

    logdata = np.log10(data)

    times = pd.DatetimeIndex(pd.to_datetime(B64_spectra_qf_analysis.time.values))
    t_num = mdates.date2num(times.to_pydatetime())
    t_edges = edges_numeric(t_num)

    freqs = B64_spectra_qf_analysis.spec_bins.values
    f_edges = edges_numeric(freqs)

    fig, ax = plt.subplots(figsize=(12, 4.5))

    pcm = ax.pcolormesh(
        t_edges,
        f_edges,
        logdata.T,
        shading="auto",
        cmap="turbo",
        norm=Normalize(vmin=vmin, vmax=vmax),
    )

    ax.plot(f_cH_plot.time, f_cH_plot.data, lw=1, c='white', linestyle='solid')
    ax.plot(f_cHe_plot.time, f_cHe_plot.data, lw=1, c='magenta', linestyle='solid')
    ax.plot(f_cO_plot.time, f_cO_plot.data, lw=1, c='yellow', linestyle='solid')

    ax.xaxis_date()
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))

    ax.set_yscale("log")
    ax.set_ylim(3, 32)

    ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

    ax.set_xlabel("Time")
    ax.set_ylabel("Frequency [Hz]")
    ax.set_title(
        f"MGF 64hz total spec "
        f"({start:%Y-%m-%d %H:%M:%S} - {end:%Y-%m-%d %H:%M:%S})"
    )

    fig.colorbar(
        pcm,
        ax=ax,
        label=r"log10 PSD [$\mathrm{nT}^2/\mathrm{Hz}$]"
    )

    plt.tight_layout()

    # ========================================================
    # save
    # ========================================================

    save_dir = path_base_save_plot / f"{start:%Y}" / f"{start:%m}"
    save_dir.mkdir(parents=True, exist_ok=True)

    filename = (
        f"MGF_B64_spectra_"
        f"{start:%Y%m%d_%H%M%S}_to_{end:%Y%m%d_%H%M%S}.png"
    )

    save_path = save_dir / filename

    fig.savefig(save_path, dpi=200, bbox_inches="tight")
    plt.close(fig)

    print(f"saved: {save_path}")

Saving MGF spec plots:   0%|          | 1/210 [00:00<02:38,  1.32it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_001326_to_20200301_002006.png

Saving MGF spec plots:   1%|          | 2/210 [00:01<02:18,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_005626_to_20200301_010306.png

Saving MGF spec plots:   1%|▏         | 3/210 [00:01<02:11,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_071745_to_20200301_072425.png

Saving MGF spec plots:   2%|▏         | 4/210 [00:02<02:07,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_081844_to_20200301_082652.png

Saving MGF spec plots:   2%|▏         | 5/210 [00:03<02:04,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_084928_to_20200301_085608.png

Saving MGF spec plots:   3%|▎         | 6/210 [00:03<02:05,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_085838_to_20200301_091707.png

Saving MGF spec plots:   3%|▎         | 7/210 [00:04<02:06,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_092641_to_20200301_093550.png

Saving MGF spec plots:   4%|▍         | 8/210 [00:05<02:04,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_093601_to_20200301_094241.png

Saving MGF spec plots:   4%|▍         | 9/210 [00:05<02:01,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_094506_to_20200301_095146.png

Saving MGF spec plots:   5%|▍         | 10/210 [00:06<02:01,  1.65it/s]29-Sep-26 19:26:18: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_095727_to_20200301_100407.png

Saving MGF spec plots:   5%|▌         | 11/210 [00:06<02:03,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_100631_to_20200301_101506.png

Saving MGF spec plots:   6%|▌         | 12/210 [00:07<02:02,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_101804_to_20200301_103158.png

Saving MGF spec plots:   6%|▌         | 13/210 [00:08<02:03,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_103553_to_20200301_105359.png

Saving MGF spec plots:   7%|▋         | 14/210 [00:08<02:01,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_111114_to_20200301_111754.png

Saving MGF spec plots:   7%|▋         | 15/210 [00:09<02:02,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200301_111937_to_20200301_113513.png

Saving MGF spec plots:   8%|▊         | 16/210 [00:09<02:02,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_070541_to_20200303_072509.png

Saving MGF spec plots:   8%|▊         | 17/210 [00:10<01:59,  1.62it/s]29-Sep-26 19:26:22: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_072545_to_20200303_073225.png

Saving MGF spec plots:   9%|▊         | 18/210 [00:11<01:57,  1.63it/s]29-Sep-26 19:26:23: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_074144_to_20200303_074949.png

Saving MGF spec plots:   9%|▉         | 19/210 [00:11<01:57,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_080829_to_20200303_081827.png

Saving MGF spec plots:  10%|▉         | 20/210 [00:12<01:55,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_082106_to_20200303_082746.png

Saving MGF spec plots:  10%|█         | 21/210 [00:12<01:50,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_083515_to_20200303_084155.png

Saving MGF spec plots:  10%|█         | 22/210 [00:13<01:51,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_085826_to_20200303_090747.png

Saving MGF spec plots:  11%|█         | 23/210 [00:14<01:50,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_091609_to_20200303_092249.png

Saving MGF spec plots:  11%|█▏        | 24/210 [00:14<01:52,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_092841_to_20200303_095130.png

Saving MGF spec plots:  12%|█▏        | 25/210 [00:15<01:53,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_095543_to_20200303_100223.png

Saving MGF spec plots:  12%|█▏        | 26/210 [00:16<01:52,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_171653_to_20200303_172333.png

Saving MGF spec plots:  13%|█▎        | 27/210 [00:16<01:49,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_172704_to_20200303_173804.png

Saving MGF spec plots:  13%|█▎        | 28/210 [00:18<02:55,  1.04it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_180522_to_20200303_181836.png

Saving MGF spec plots:  14%|█▍        | 29/210 [00:18<02:31,  1.19it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_182345_to_20200303_183206.png

Saving MGF spec plots:  14%|█▍        | 30/210 [00:19<02:16,  1.32it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200303_193048_to_20200303_193728.png

Saving MGF spec plots:  15%|█▍        | 31/210 [00:20<02:03,  1.45it/s]29-Sep-26 19:26:32: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_042802_to_20200304_043442.png

Saving MGF spec plots:  15%|█▌        | 32/210 [00:20<01:57,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_111108_to_20200304_111914.png

Saving MGF spec plots:  16%|█▌        | 33/210 [00:21<01:53,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_112710_to_20200304_113350.png

Saving MGF spec plots:  16%|█▌        | 34/210 [00:21<01:53,  1.55it/s]29-Sep-26 19:26:34: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_113833_to_20200304_115535.png

Saving MGF spec plots:  17%|█▋        | 35/210 [00:22<02:01,  1.43it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_120829_to_20200304_124818.png

Saving MGF spec plots:  17%|█▋        | 36/210 [00:23<01:59,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_125014_to_20200304_131456.png

Saving MGF spec plots:  18%|█▊        | 37/210 [00:23<01:55,  1.50it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_132820_to_20200304_135313.png

Saving MGF spec plots:  18%|█▊        | 38/210 [00:24<01:51,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_135314_to_20200304_141405.png

Saving MGF spec plots:  19%|█▊        | 39/210 [00:25<01:46,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_141731_to_20200304_143350.png

Saving MGF spec plots:  19%|█▉        | 40/210 [00:25<01:42,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_143454_to_20200304_144640.png

Saving MGF spec plots:  20%|█▉        | 41/210 [00:26<01:37,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_152414_to_20200304_153054.png

Saving MGF spec plots:  20%|██        | 42/210 [00:26<01:37,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200304_153230_to_20200304_153914.png

Saving MGF spec plots:  20%|██        | 43/210 [00:27<01:39,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_063646_to_20200305_064730.png

Saving MGF spec plots:  21%|██        | 44/210 [00:27<01:37,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_082116_to_20200305_082756.png

Saving MGF spec plots:  21%|██▏       | 45/210 [00:28<01:35,  1.72it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_083020_to_20200305_083700.png

Saving MGF spec plots:  22%|██▏       | 46/210 [00:29<01:33,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_084149_to_20200305_084829.png

Saving MGF spec plots:  22%|██▏       | 47/210 [00:29<01:31,  1.78it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_084908_to_20200305_085548.png

Saving MGF spec plots:  23%|██▎       | 48/210 [00:30<01:30,  1.78it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_085917_to_20200305_090557.png

Saving MGF spec plots:  23%|██▎       | 49/210 [00:30<01:29,  1.81it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200305_091126_to_20200305_091806.png

Saving MGF spec plots:  24%|██▍       | 50/210 [00:31<01:30,  1.77it/s]29-Sep-26 19:26:43: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_102350_to_20200306_103415.png

Saving MGF spec plots:  24%|██▍       | 51/210 [00:32<01:35,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_120829_to_20200306_122443.png

Saving MGF spec plots:  25%|██▍       | 52/210 [00:32<01:35,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_122455_to_20200306_124135.png

Saving MGF spec plots:  25%|██▌       | 53/210 [00:33<01:35,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_124550_to_20200306_125230.png

Saving MGF spec plots:  26%|██▌       | 54/210 [00:33<01:35,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_125700_to_20200306_131039.png

Saving MGF spec plots:  26%|██▌       | 55/210 [00:34<01:33,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_133902_to_20200306_134542.png

Saving MGF spec plots:  27%|██▋       | 56/210 [00:35<01:34,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200306_142647_to_20200306_143414.png

Saving MGF spec plots:  27%|██▋       | 57/210 [00:35<01:33,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_053303_to_20200307_053943.png

Saving MGF spec plots:  28%|██▊       | 58/210 [00:36<01:32,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_054414_to_20200307_055630.png

Saving MGF spec plots:  28%|██▊       | 59/210 [00:37<01:50,  1.36it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_060753_to_20200307_062427.png

Saving MGF spec plots:  29%|██▊       | 60/210 [00:37<01:46,  1.41it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_062655_to_20200307_063903.png

Saving MGF spec plots:  29%|██▉       | 61/210 [00:38<01:42,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_063941_to_20200307_064621.png

Saving MGF spec plots:  30%|██▉       | 62/210 [00:39<01:39,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_072351_to_20200307_073134.png

Saving MGF spec plots:  30%|███       | 63/210 [00:39<01:36,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_073443_to_20200307_074123.png

Saving MGF spec plots:  30%|███       | 64/210 [00:40<01:36,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_074438_to_20200307_075736.png

Saving MGF spec plots:  31%|███       | 65/210 [00:41<01:33,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_081701_to_20200307_083033.png

Saving MGF spec plots:  31%|███▏      | 66/210 [00:41<01:31,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_083847_to_20200307_084527.png

Saving MGF spec plots:  32%|███▏      | 67/210 [00:42<01:31,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_084546_to_20200307_085431.png

Saving MGF spec plots:  32%|███▏      | 68/210 [00:43<01:30,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_085909_to_20200307_091601.png

Saving MGF spec plots:  33%|███▎      | 69/210 [00:43<01:32,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200307_092201_to_20200307_092841.png

Saving MGF spec plots:  33%|███▎      | 70/210 [00:44<01:30,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_093314_to_20200308_093954.png

Saving MGF spec plots:  34%|███▍      | 71/210 [00:45<01:30,  1.53it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_094723_to_20200308_095614.png

Saving MGF spec plots:  34%|███▍      | 72/210 [00:45<01:31,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_095958_to_20200308_100805.png

Saving MGF spec plots:  35%|███▍      | 73/210 [00:46<01:28,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_101545_to_20200308_102649.png

Saving MGF spec plots:  35%|███▌      | 74/210 [00:46<01:27,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_102732_to_20200308_103412.png

Saving MGF spec plots:  36%|███▌      | 75/210 [00:47<01:26,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_104941_to_20200308_105621.png

Saving MGF spec plots:  36%|███▌      | 76/210 [00:48<01:23,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_110605_to_20200308_111248.png

Saving MGF spec plots:  37%|███▋      | 77/210 [00:48<01:22,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_111724_to_20200308_112404.png

Saving MGF spec plots:  37%|███▋      | 78/210 [00:49<01:27,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_114710_to_20200308_115350.png

Saving MGF spec plots:  38%|███▊      | 79/210 [00:50<01:24,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_125810_to_20200308_130450.png

Saving MGF spec plots:  38%|███▊      | 80/210 [00:50<01:22,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_131033_to_20200308_131713.png

Saving MGF spec plots:  39%|███▊      | 81/210 [00:51<01:21,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_131725_to_20200308_132405.png

Saving MGF spec plots:  39%|███▉      | 82/210 [00:52<01:20,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_132529_to_20200308_133306.png

Saving MGF spec plots:  40%|███▉      | 83/210 [00:52<01:19,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_134000_to_20200308_135429.png

Saving MGF spec plots:  40%|████      | 84/210 [00:53<01:18,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_140553_to_20200308_141241.png

Saving MGF spec plots:  40%|████      | 85/210 [00:53<01:19,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_205340_to_20200308_210245.png

Saving MGF spec plots:  41%|████      | 86/210 [00:54<01:17,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_210740_to_20200308_211420.png

Saving MGF spec plots:  41%|████▏     | 87/210 [00:55<01:14,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200308_211531_to_20200308_212211.png

Saving MGF spec plots:  42%|████▏     | 88/210 [00:55<01:14,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200309_050107_to_20200309_050747.png

Saving MGF spec plots:  42%|████▏     | 89/210 [00:56<01:15,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200309_062616_to_20200309_063356.png

Saving MGF spec plots:  43%|████▎     | 90/210 [00:57<01:15,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200309_063510_to_20200309_064153.png

Saving MGF spec plots:  43%|████▎     | 91/210 [00:57<01:13,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200309_181755_to_20200309_182435.png

Saving MGF spec plots:  44%|████▍     | 92/210 [00:58<01:15,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_001118_to_20200310_001758.png

Saving MGF spec plots:  44%|████▍     | 93/210 [00:58<01:14,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_082106_to_20200310_082746.png

Saving MGF spec plots:  45%|████▍     | 94/210 [00:59<01:28,  1.31it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_090620_to_20200310_091300.png

Saving MGF spec plots:  45%|████▌     | 95/210 [01:00<01:22,  1.39it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_091706_to_20200310_092346.png

Saving MGF spec plots:  46%|████▌     | 96/210 [01:01<01:18,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_110935_to_20200310_112311.png

Saving MGF spec plots:  46%|████▌     | 97/210 [01:01<01:16,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_113642_to_20200310_114541.png

Saving MGF spec plots:  47%|████▋     | 98/210 [01:02<01:12,  1.54it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_115002_to_20200310_115642.png

Saving MGF spec plots:  47%|████▋     | 99/210 [01:03<01:10,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_123631_to_20200310_124311.png

Saving MGF spec plots:  48%|████▊     | 100/210 [01:03<01:08,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_124601_to_20200310_125442.png

Saving MGF spec plots:  48%|████▊     | 101/210 [01:04<01:08,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200310_130110_to_20200310_130750.png

Saving MGF spec plots:  49%|████▊     | 102/210 [01:04<01:07,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200312_081636_to_20200312_082354.png

Saving MGF spec plots:  49%|████▉     | 103/210 [01:05<01:06,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200312_092151_to_20200312_093351.png

Saving MGF spec plots:  50%|████▉     | 104/210 [01:06<01:03,  1.68it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200312_095506_to_20200312_100146.png

Saving MGF spec plots:  50%|█████     | 105/210 [01:06<01:03,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200313_070129_to_20200313_071020.png

Saving MGF spec plots:  50%|█████     | 106/210 [01:07<01:03,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200314_100414_to_20200314_101054.png

Saving MGF spec plots:  51%|█████     | 107/210 [01:07<01:04,  1.59it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200314_104417_to_20200314_105506.png

Saving MGF spec plots:  51%|█████▏    | 108/210 [01:08<01:03,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200314_113326_to_20200314_114006.png

Saving MGF spec plots:  52%|█████▏    | 109/210 [01:09<01:01,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200316_073459_to_20200316_074139.png

Saving MGF spec plots:  52%|█████▏    | 110/210 [01:09<01:01,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200316_083550_to_20200316_084230.png

Saving MGF spec plots:  53%|█████▎    | 111/210 [01:10<01:00,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200316_085220_to_20200316_090129.png

Saving MGF spec plots:  53%|█████▎    | 112/210 [01:11<01:00,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_121056_to_20200317_121736.png

Saving MGF spec plots:  54%|█████▍    | 113/210 [01:11<00:56,  1.71it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_123118_to_20200317_123758.png

Saving MGF spec plots:  54%|█████▍    | 114/210 [01:12<00:56,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_124342_to_20200317_125022.png

Saving MGF spec plots:  55%|█████▍    | 115/210 [01:12<00:56,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_142416_to_20200317_143614.png

Saving MGF spec plots:  55%|█████▌    | 116/210 [01:13<00:56,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_145459_to_20200317_150139.png

Saving MGF spec plots:  56%|█████▌    | 117/210 [01:14<00:56,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_150702_to_20200317_151343.png

Saving MGF spec plots:  56%|█████▌    | 118/210 [01:14<00:55,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_154107_to_20200317_155318.png

Saving MGF spec plots:  57%|█████▋    | 119/210 [01:15<00:55,  1.65it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_220606_to_20200317_221246.png

Saving MGF spec plots:  57%|█████▋    | 120/210 [01:15<00:54,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200317_231154_to_20200317_231834.png

Saving MGF spec plots:  58%|█████▊    | 121/210 [01:16<00:53,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200318_070527_to_20200318_071207.png

Saving MGF spec plots:  58%|█████▊    | 122/210 [01:17<00:53,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200318_073114_to_20200318_073754.png

Saving MGF spec plots:  59%|█████▊    | 123/210 [01:17<00:53,  1.62it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200318_170947_to_20200318_171627.png

Saving MGF spec plots:  59%|█████▉    | 124/210 [01:18<00:53,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200318_172142_to_20200318_174204.png

Saving MGF spec plots:  60%|█████▉    | 125/210 [01:18<00:53,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200318_182311_to_20200318_183506.png

Saving MGF spec plots:  60%|██████    | 126/210 [01:19<00:51,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_005007_to_20200319_005647.png

Saving MGF spec plots:  60%|██████    | 127/210 [01:20<00:51,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_012259_to_20200319_013721.png

Saving MGF spec plots:  61%|██████    | 128/210 [01:20<00:51,  1.58it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_081931_to_20200319_082611.png

Saving MGF spec plots:  61%|██████▏   | 129/210 [01:21<00:52,  1.55it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_105554_to_20200319_110234.png

Saving MGF spec plots:  62%|██████▏   | 130/210 [01:22<00:52,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_111108_to_20200319_111748.png

Saving MGF spec plots:  62%|██████▏   | 131/210 [01:22<00:50,  1.56it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_111926_to_20200319_112606.png

Saving MGF spec plots:  63%|██████▎   | 132/210 [01:23<00:46,  1.66it/s]29-Sep-26 19:27:35: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_113452_to_20200319_114140.png

Saving MGF spec plots:  63%|██████▎   | 133/210 [01:24<00:57,  1.33it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_114842_to_20200319_115930.png

Saving MGF spec plots:  64%|██████▍   | 134/210 [01:24<00:52,  1.45it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_121109_to_20200319_122009.png

Saving MGF spec plots:  64%|██████▍   | 135/210 [01:25<00:49,  1.52it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_123203_to_20200319_124100.png

Saving MGF spec plots:  65%|██████▍   | 136/210 [01:26<00:45,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_124114_to_20200319_124754.png

Saving MGF spec plots:  65%|██████▌   | 137/210 [01:26<00:44,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_130140_to_20200319_131454.png

Saving MGF spec plots:  66%|██████▌   | 138/210 [01:27<00:43,  1.66it/s]29-Sep-26 19:27:39: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_131612_to_20200319_134020.png

Saving MGF spec plots:  66%|██████▌   | 139/210 [01:27<00:42,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_142608_to_20200319_144823.png

Saving MGF spec plots:  67%|██████▋   | 140/210 [01:28<00:41,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_145904_to_20200319_150717.png

Saving MGF spec plots:  67%|██████▋   | 141/210 [01:28<00:39,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_212120_to_20200319_212800.png

Saving MGF spec plots:  68%|██████▊   | 142/210 [01:29<00:38,  1.77it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200319_221347_to_20200319_222027.png

Saving MGF spec plots:  68%|██████▊   | 143/210 [01:30<00:37,  1.80it/s]29-Sep-26 19:27:42: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_152726_to_20200320_154007.png

Saving MGF spec plots:  69%|██████▊   | 144/210 [01:30<00:36,  1.80it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_155223_to_20200320_160008.png

Saving MGF spec plots:  69%|██████▉   | 145/210 [01:31<00:38,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_160908_to_20200320_163010.png

Saving MGF spec plots:  70%|██████▉   | 146/210 [01:31<00:36,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_163608_to_20200320_164816.png

Saving MGF spec plots:  70%|███████   | 147/210 [01:32<00:36,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_170131_to_20200320_171102.png

Saving MGF spec plots:  70%|███████   | 148/210 [01:32<00:35,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_171327_to_20200320_172007.png

Saving MGF spec plots:  71%|███████   | 149/210 [01:33<00:34,  1.75it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_172728_to_20200320_173408.png

Saving MGF spec plots:  71%|███████▏  | 150/210 [01:34<00:34,  1.75it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_173922_to_20200320_174602.png

Saving MGF spec plots:  72%|███████▏  | 151/210 [01:34<00:33,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_180624_to_20200320_181656.png

Saving MGF spec plots:  72%|███████▏  | 152/210 [01:35<00:32,  1.77it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200320_193422_to_20200320_194102.png

Saving MGF spec plots:  73%|███████▎  | 153/210 [01:35<00:32,  1.78it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_094446_to_20200321_095126.png

Saving MGF spec plots:  73%|███████▎  | 154/210 [01:36<00:31,  1.77it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_100504_to_20200321_101144.png

Saving MGF spec plots:  74%|███████▍  | 155/210 [01:36<00:30,  1.80it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_103005_to_20200321_104431.png

Saving MGF spec plots:  74%|███████▍  | 156/210 [01:37<00:33,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_112604_to_20200321_113244.png

Saving MGF spec plots:  75%|███████▍  | 157/210 [01:38<00:31,  1.66it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_114003_to_20200321_115600.png

Saving MGF spec plots:  75%|███████▌  | 158/210 [01:38<00:30,  1.69it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_122317_to_20200321_122957.png

Saving MGF spec plots:  76%|███████▌  | 159/210 [01:39<00:30,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_125431_to_20200321_131428.png

Saving MGF spec plots:  76%|███████▌  | 160/210 [01:39<00:28,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_133454_to_20200321_134134.png

Saving MGF spec plots:  77%|███████▋  | 161/210 [01:40<00:27,  1.77it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200321_141545_to_20200321_142225.png

Saving MGF spec plots:  77%|███████▋  | 162/210 [01:40<00:26,  1.80it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200322_061515_to_20200322_062155.png

Saving MGF spec plots:  78%|███████▊  | 163/210 [01:41<00:25,  1.83it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200322_064239_to_20200322_064919.png

Saving MGF spec plots:  78%|███████▊  | 164/210 [01:41<00:24,  1.85it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200322_181544_to_20200322_182224.png

Saving MGF spec plots:  79%|███████▊  | 165/210 [01:42<00:23,  1.88it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_011308_to_20200323_012455.png

Saving MGF spec plots:  79%|███████▉  | 166/210 [01:43<00:23,  1.86it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_015843_to_20200323_020523.png

Saving MGF spec plots:  80%|███████▉  | 167/210 [01:43<00:23,  1.83it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_023056_to_20200323_023736.png

Saving MGF spec plots:  80%|████████  | 168/210 [01:44<00:23,  1.81it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_032822_to_20200323_033502.png

Saving MGF spec plots:  80%|████████  | 169/210 [01:44<00:22,  1.82it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_065142_to_20200323_065822.png

Saving MGF spec plots:  81%|████████  | 170/210 [01:45<00:22,  1.82it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_101431_to_20200323_102111.png

Saving MGF spec plots:  81%|████████▏ | 171/210 [01:45<00:21,  1.83it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_102143_to_20200323_102823.png

Saving MGF spec plots:  82%|████████▏ | 172/210 [01:46<00:20,  1.82it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_104842_to_20200323_105902.png

Saving MGF spec plots:  82%|████████▏ | 173/210 [01:46<00:19,  1.86it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_111214_to_20200323_111854.png

Saving MGF spec plots:  83%|████████▎ | 174/210 [01:47<00:19,  1.88it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_113913_to_20200323_114553.png

Saving MGF spec plots:  83%|████████▎ | 175/210 [01:47<00:18,  1.90it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_122111_to_20200323_122751.png

Saving MGF spec plots:  84%|████████▍ | 176/210 [01:48<00:18,  1.86it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_124457_to_20200323_125459.png

Saving MGF spec plots:  84%|████████▍ | 177/210 [01:49<00:17,  1.84it/s]29-Sep-26 19:28:01: /tmp/ipykernel_91668/83041203.py:94: UserWarning: Discarding nonzero nanoseconds in conversion.
  ax.set_xlim(start.to_pydatetime(), end.to_pydatetime())

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_133516_to_20200323_134222.png

Saving MGF spec plots:  85%|████████▍ | 178/210 [01:49<00:19,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_165053_to_20200323_165920.png

Saving MGF spec plots:  85%|████████▌ | 179/210 [01:50<00:19,  1.61it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_192935_to_20200323_193615.png

Saving MGF spec plots:  86%|████████▌ | 180/210 [01:51<00:23,  1.28it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200323_195523_to_20200323_200223.png

Saving MGF spec plots:  86%|████████▌ | 181/210 [01:52<00:20,  1.40it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200325_012617_to_20200325_013257.png

Saving MGF spec plots:  87%|████████▋ | 182/210 [01:52<00:18,  1.49it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200325_110023_to_20200325_110703.png

Saving MGF spec plots:  87%|████████▋ | 183/210 [01:53<00:17,  1.51it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200325_110859_to_20200325_112920.png

Saving MGF spec plots:  88%|████████▊ | 184/210 [01:53<00:16,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200325_113145_to_20200325_114406.png

Saving MGF spec plots:  88%|████████▊ | 185/210 [01:54<00:15,  1.57it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200325_114905_to_20200325_115545.png

Saving MGF spec plots:  89%|████████▊ | 186/210 [01:55<00:14,  1.60it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200326_150136_to_20200326_150816.png

Saving MGF spec plots:  89%|████████▉ | 187/210 [01:55<00:14,  1.64it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200326_152318_to_20200326_153304.png

Saving MGF spec plots:  90%|████████▉ | 188/210 [01:56<00:13,  1.67it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200327_100211_to_20200327_101033.png

Saving MGF spec plots:  90%|█████████ | 189/210 [01:56<00:12,  1.72it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200327_111948_to_20200327_112631.png

Saving MGF spec plots:  90%|█████████ | 190/210 [01:57<00:11,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200327_180201_to_20200327_181057.png

Saving MGF spec plots:  91%|█████████ | 191/210 [01:58<00:11,  1.70it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200328_123718_to_20200328_124731.png

Saving MGF spec plots:  91%|█████████▏| 192/210 [01:58<00:10,  1.75it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200328_131835_to_20200328_132520.png

Saving MGF spec plots:  92%|█████████▏| 193/210 [01:59<00:09,  1.79it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200328_224900_to_20200328_225540.png

Saving MGF spec plots:  92%|█████████▏| 194/210 [01:59<00:08,  1.83it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200328_231808_to_20200328_232530.png

Saving MGF spec plots:  93%|█████████▎| 195/210 [02:00<00:08,  1.78it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200328_232612_to_20200328_233520.png

Saving MGF spec plots:  93%|█████████▎| 196/210 [02:00<00:08,  1.73it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200329_065150_to_20200329_065830.png

Saving MGF spec plots:  94%|█████████▍| 197/210 [02:01<00:07,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200329_070755_to_20200329_072216.png

Saving MGF spec plots:  94%|█████████▍| 198/210 [02:01<00:06,  1.80it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200329_072312_to_20200329_072952.png

Saving MGF spec plots:  95%|█████████▍| 199/210 [02:02<00:06,  1.82it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200329_074418_to_20200329_075536.png

Saving MGF spec plots:  95%|█████████▌| 200/210 [02:02<00:05,  1.83it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200329_082350_to_20200329_083133.png

Saving MGF spec plots:  96%|█████████▌| 201/210 [02:03<00:04,  1.87it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_092639_to_20200330_093319.png

Saving MGF spec plots:  96%|█████████▌| 202/210 [02:04<00:04,  1.79it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_132142_to_20200330_134322.png

Saving MGF spec plots:  97%|█████████▋| 203/210 [02:04<00:04,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_134756_to_20200330_135436.png

Saving MGF spec plots:  97%|█████████▋| 204/210 [02:05<00:03,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_135500_to_20200330_140140.png

Saving MGF spec plots:  98%|█████████▊| 205/210 [02:05<00:02,  1.74it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_141042_to_20200330_141722.png

Saving MGF spec plots:  98%|█████████▊| 206/210 [02:06<00:02,  1.76it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_141942_to_20200330_142622.png

Saving MGF spec plots:  99%|█████████▊| 207/210 [02:06<00:01,  1.79it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_143044_to_20200330_143724.png

Saving MGF spec plots:  99%|█████████▉| 208/210 [02:07<00:01,  1.81it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_144332_to_20200330_145012.png

Saving MGF spec plots: 100%|█████████▉| 209/210 [02:08<00:00,  1.84it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_152252_to_20200330_152932.png

Saving MGF spec plots: 100%|██████████| 210/210 [02:08<00:00,  1.63it/s]

saved: /mnt/j/statistical_analysis_arase/preanalysis/MGF_spec_after_B/2020/03/MGF_B64_spectra_20200330_221857_to_20200330_222537.png

# 最終有効時間の保存

第二段階検証後の `merged_ranges_mono_df` を親レンジとして保持し、400--1200 s の非重複解析コアへ等分割する。CSV/JSON には親ID、分割番号、背景磁場計算用の前後60 sの読み込み範囲を保存する。

In [57]:
from pathlib import Path
import json
import pandas as pd
import numpy as np

# ============================================================
# save final valid time ranges
# ============================================================

save_dir_valid_times = Path("/mnt/j/statistical_analysis_arase/preanalysis/valid_time_ranges")
save_dir_valid_times.mkdir(parents=True, exist_ok=True)

if "merged_ranges_mono_df" not in globals():
    raise NameError("merged_ranges_mono_df が未定義です。第二段階検証を先に実行してください。")

ANALYSIS_RANGE_COLUMNS = [
    "range_id",
    "parent_range_id",
    "segment_id",
    "n_segments",
    "start_time",
    "end_time",
    "duration_sec",
    "duration_min",
    "load_start_time",
    "load_end_time",
    "parent_start_time",
    "parent_end_time",
    "parent_duration_sec",
]

def split_ranges_for_analysis(
    ranges_df,
    min_duration=MIN_EVENT_DURATION,
    max_duration=MAX_ANALYSIS_DURATION,
    context_pad=BACKGROUND_CONTEXT_PAD,
    boundary_epsilon=RANGE_BOUNDARY_EPSILON,
):
    """Split each parent range into equal, non-overlapping analysis cores."""
    min_duration = pd.Timedelta(min_duration)
    max_duration = pd.Timedelta(max_duration)
    context_pad = pd.Timedelta(context_pad)
    boundary_epsilon = pd.Timedelta(boundary_epsilon)

    if min_duration <= pd.Timedelta(0):
        raise ValueError("min_duration must be positive")
    if max_duration < 2 * min_duration:
        raise ValueError("max_duration must be at least twice min_duration for equal splitting")
    if context_pad < pd.Timedelta(0) or boundary_epsilon <= pd.Timedelta(0):
        raise ValueError("context_pad must be nonnegative and boundary_epsilon must be positive")

    if ranges_df is None or len(ranges_df) == 0:
        return pd.DataFrame(columns=ANALYSIS_RANGE_COLUMNS)

    parents = ranges_df[["start_time", "end_time"]].copy()
    parents["start_time"] = pd.to_datetime(parents["start_time"])
    parents["end_time"] = pd.to_datetime(parents["end_time"])
    parents = parents.sort_values("start_time").reset_index(drop=True)

    rows = []
    for parent_idx, parent in parents.iterrows():
        parent_id = int(parent_idx + 1)
        parent_start = pd.Timestamp(parent["start_time"])
        parent_end = pd.Timestamp(parent["end_time"])
        parent_duration = parent_end - parent_start

        if parent_duration < min_duration:
            raise ValueError(
                f"parent range {parent_id} is shorter than {min_duration.total_seconds():g} s"
            )

        n_segments = max(1, int(np.ceil(parent_duration / max_duration)))
        duration_ns = int(parent_duration.value)
        edges = [
            parent_start + pd.to_timedelta((duration_ns * i) // n_segments, unit="ns")
            for i in range(n_segments + 1)
        ]
        edges[-1] = parent_end

        for segment_idx in range(n_segments):
            segment_start = edges[segment_idx]
            segment_end = edges[segment_idx + 1]
            if segment_idx < n_segments - 1:
                segment_end -= boundary_epsilon
            segment_duration = segment_end - segment_start

            if segment_duration < min_duration or segment_duration > max_duration:
                raise ValueError(
                    f"invalid split duration for parent {parent_id}, segment {segment_idx + 1}: "
                    f"{segment_duration.total_seconds():.6f} s"
                )

            rows.append({
                "parent_range_id": parent_id,
                "segment_id": int(segment_idx + 1),
                "n_segments": int(n_segments),
                "start_time": segment_start,
                "end_time": segment_end,
                "duration_sec": float(segment_duration.total_seconds()),
                "duration_min": float(segment_duration.total_seconds() / 60.0),
                "load_start_time": segment_start - context_pad,
                "load_end_time": segment_end + context_pad,
                "parent_start_time": parent_start,
                "parent_end_time": parent_end,
                "parent_duration_sec": float(parent_duration.total_seconds()),
            })

    result = pd.DataFrame(rows)
    result.insert(0, "range_id", np.arange(1, len(result) + 1, dtype=int))
    return result[ANALYSIS_RANGE_COLUMNS]

parent_time_ranges_df = merged_ranges_mono_df[["start_time", "end_time"]].copy()
parent_time_ranges_df["start_time"] = pd.to_datetime(parent_time_ranges_df["start_time"])
parent_time_ranges_df["end_time"] = pd.to_datetime(parent_time_ranges_df["end_time"])
parent_time_ranges_df = parent_time_ranges_df.sort_values("start_time").reset_index(drop=True)
parent_time_ranges_df.insert(0, "parent_range_id", np.arange(1, len(parent_time_ranges_df) + 1, dtype=int))
parent_time_ranges_df["duration_sec"] = (
    parent_time_ranges_df["end_time"] - parent_time_ranges_df["start_time"]
).dt.total_seconds()
parent_time_ranges_df["duration_min"] = parent_time_ranges_df["duration_sec"] / 60.0

valid_time_ranges_df = split_ranges_for_analysis(parent_time_ranges_df)

t0_save = pd.to_datetime(time_range[0]) if "time_range" in globals() else pd.Timestamp("1970-01-01")
t1_save = pd.to_datetime(time_range[-1]) if "time_range" in globals() else pd.Timestamp("1970-01-01")

base_name = (
    f"Arase_valid_time_ranges_"
    f"{t0_save:%Y%m%d_%H%M%S}_to_{t1_save:%Y%m%d_%H%M%S}"
)

csv_path = save_dir_valid_times / f"{base_name}.csv"
json_path = save_dir_valid_times / f"{base_name}.json"
summary_path = save_dir_valid_times / f"{base_name}_summary.txt"

# CSV: 一番見やすい確認用
valid_time_ranges_df.to_csv(csv_path, index=False)

# JSON: 後で Python から読み直しやすい形式
json_records = []
for _, row in valid_time_ranges_df.iterrows():
    json_records.append({
        "range_id": int(row["range_id"]),
        "parent_range_id": int(row["parent_range_id"]),
        "segment_id": int(row["segment_id"]),
        "n_segments": int(row["n_segments"]),
        "start_time": pd.Timestamp(row["start_time"]).isoformat(),
        "end_time": pd.Timestamp(row["end_time"]).isoformat(),
        "duration_sec": float(row["duration_sec"]),
        "duration_min": float(row["duration_min"]),
        "load_start_time": pd.Timestamp(row["load_start_time"]).isoformat(),
        "load_end_time": pd.Timestamp(row["load_end_time"]).isoformat(),
        "parent_start_time": pd.Timestamp(row["parent_start_time"]).isoformat(),
        "parent_end_time": pd.Timestamp(row["parent_end_time"]).isoformat(),
        "parent_duration_sec": float(row["parent_duration_sec"]),
    })

parent_json_records = []
for _, row in parent_time_ranges_df.iterrows():
    parent_json_records.append({
        "parent_range_id": int(row["parent_range_id"]),
        "start_time": pd.Timestamp(row["start_time"]).isoformat(),
        "end_time": pd.Timestamp(row["end_time"]).isoformat(),
        "duration_sec": float(row["duration_sec"]),
        "duration_min": float(row["duration_min"]),
    })

metadata = {
    "description": "Final analysis ranges after Arase event preanalysis and duration-based splitting.",
    "source_notebook": "Arase_event_preanalysis.ipynb",
    "time_range_input": time_range if "time_range" in globals() else None,
    "event_half_width_sec": float(EVENT_HALF_WIDTH.total_seconds()),
    "minimum_event_duration_sec": float(MIN_EVENT_DURATION.total_seconds()),
    "maximum_analysis_duration_sec": float(MAX_ANALYSIS_DURATION.total_seconds()),
    "background_context_pad_sec": float(BACKGROUND_CONTEXT_PAD.total_seconds()),
    "range_boundary_epsilon_sec": float(RANGE_BOUNDARY_EPSILON.total_seconds()),
    "range_interval_convention": "closed intervals; non-final segment ends 1 microsecond before the next segment starts",
    "n_parent_ranges": int(len(parent_time_ranges_df)),
    "n_analysis_ranges": int(len(valid_time_ranges_df)),
    "n_valid_ranges": int(len(valid_time_ranges_df)),
    "n_split_parent_ranges": int(valid_time_ranges_df.loc[valid_time_ranges_df["n_segments"] > 1, "parent_range_id"].nunique()) if len(valid_time_ranges_df) > 0 else 0,
    "total_parent_duration_min": float(parent_time_ranges_df["duration_min"].sum()) if len(parent_time_ranges_df) > 0 else 0.0,
    "total_analysis_duration_min": float(valid_time_ranges_df["duration_min"].sum()) if len(valid_time_ranges_df) > 0 else 0.0,
    "total_duration_min": float(valid_time_ranges_df["duration_min"].sum()) if len(valid_time_ranges_df) > 0 else 0.0,
    "selection_summary": {
        "n_selected_times": int(len(selected_times)) if "selected_times" in globals() else None,
        "n_selected_times_mono": int(len(selected_times_mono)) if "selected_times_mono" in globals() else None,
        "n_forbidden_intervals_mono": int(len(forbidden_intervals_mono_df)) if "forbidden_intervals_mono_df" in globals() else None,
    },
    "conditions": [
        "PWE-EFD spec high-power condition in 3--32 Hz",
        "LEPe/LEPi omniflux bad intervals excluded",
        "PWE-HFA L3 time gaps >= 5 minutes, bad quality flags, and nonfinite ne_mgf excluded",
        "ATT NaN intervals excluded",
        "MGF PSD monotonic-decreasing condition applied",
        "MGF quality bad intervals excluded",
        "B spin-plane angle condition applied",
        "MGF waveform time gaps excluded",
        "PWE-EFD 64 Hz waveform nonzero quality flags for at least 10 consecutive samples excluded",
        "PWE-EFD 64 Hz waveform gaps >= 30 seconds, including range-edge and no-data gaps, excluded",
        "Final parent ranges at least 400 seconds retained",
        "Parent ranges split equally into non-overlapping analysis cores no longer than 1200 seconds",
    ],
    "parent_ranges": parent_json_records,
    "ranges": json_records,
}

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

summary_lines = [
    "Arase event preanalysis: final analysis time ranges",
    "=" * 58,
    f"source_notebook: Arase_event_preanalysis.ipynb",
    f"input time_range: {metadata['time_range_input']}",
    f"n_parent_ranges: {metadata['n_parent_ranges']}",
    f"n_analysis_ranges: {metadata['n_analysis_ranges']}",
    f"n_split_parent_ranges: {metadata['n_split_parent_ranges']}",
    f"maximum_analysis_duration_sec: {metadata['maximum_analysis_duration_sec']:.0f}",
    f"background_context_pad_sec: {metadata['background_context_pad_sec']:.0f}",
    f"total_analysis_duration_min: {metadata['total_analysis_duration_min']:.3f}",
    f"n_selected_times: {metadata['selection_summary']['n_selected_times']}",
    f"n_selected_times_mono: {metadata['selection_summary']['n_selected_times_mono']}",
    f"n_forbidden_intervals_mono: {metadata['selection_summary']['n_forbidden_intervals_mono']}",
    "",
    "conditions:",
]

summary_lines.extend([f"- {cond}" for cond in metadata["conditions"]])
summary_lines.append("")
summary_lines.append("analysis ranges:")

if len(valid_time_ranges_df) == 0:
    summary_lines.append("- none")
else:
    for _, row in valid_time_ranges_df.iterrows():
        summary_lines.append(
            f"- {int(row['range_id']):03d}: parent {int(row['parent_range_id']):03d}, "
            f"segment {int(row['segment_id'])}/{int(row['n_segments'])}; "
            f"{row['start_time']:%Y-%m-%d %H:%M:%S} -- {row['end_time']:%Y-%m-%d %H:%M:%S} "
            f"({row['duration_min']:.2f} min)"
        )

summary_path.write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

print(f"saved CSV    : {csv_path}")
print(f"saved JSON   : {json_path}")
print(f"saved summary: {summary_path}")
print(f"n_parent_ranges = {len(parent_time_ranges_df)}")
print(f"n_analysis_ranges = {len(valid_time_ranges_df)}")
print(f"total_analysis_duration_min = {metadata['total_analysis_duration_min']:.3f}")

valid_time_ranges_df

saved CSV    : /mnt/j/statistical_analysis_arase/preanalysis/valid_time_ranges/Arase_valid_time_ranges_20200301_000000_to_20200401_000000.csv
saved JSON   : /mnt/j/statistical_analysis_arase/preanalysis/valid_time_ranges/Arase_valid_time_ranges_20200301_000000_to_20200401_000000.json
saved summary: /mnt/j/statistical_analysis_arase/preanalysis/valid_time_ranges/Arase_valid_time_ranges_20200301_000000_to_20200401_000000_summary.txt
n_parent_ranges = 210
n_analysis_ranges = 221
total_analysis_duration_min = 1961.384

,range_id,parent_range_id,segment_id,n_segments,start_time,end_time,duration_sec,duration_min,load_start_time,load_end_time,parent_start_time,parent_end_time,parent_duration_sec
0,1,1,1,1,2020-03-01 00:13:26.058598,2020-03-01 00:20:06.058598,400.000000,6.666667,2020-03-01 00:12:26.058598,2020-03-01 00:21:06.058598,2020-03-01 00:13:26.058598,2020-03-01 00:20:06.058598,400.000000
1,2,2,1,1,2020-03-01 00:56:26.056025,2020-03-01 01:03:06.056025,400.000000,6.666667,2020-03-01 00:55:26.056025,2020-03-01 01:04:06.056025,2020-03-01 00:56:26.056025,2020-03-01 01:03:06.056025,400.000000
2,3,3,1,1,2020-03-01 07:17:45.015339,2020-03-01 07:24:25.015339,400.000000,6.666667,2020-03-01 07:16:45.015339,2020-03-01 07:25:25.015339,2020-03-01 07:17:45.015339,2020-03-01 07:24:25.015339,400.000000
3,4,4,1,1,2020-03-01 08:18:44.985669,2020-03-01 08:26:52.986725,488.001056,8.133351,2020-03-01 08:17:44.985669,2020-03-01 08:27:52.986725,2020-03-01 08:18:44.985669,2020-03-01 08:26:52.986725,488.001056
4,5,5,1,1,2020-03-01 08:49:28.989212,2020-03-01 08:56:08.989212,400.000000,6.666667,2020-03-01 08:48:28.989212,2020-03-01 08:57:08.989212,2020-03-01 08:49:28.989212,2020-03-01 08:56:08.989212,400.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,217,206,1,1,2020-03-30 14:19:42.835812,2020-03-30 14:26:22.835812,400.000000,6.666667,2020-03-30 14:18:42.835812,2020-03-30 14:27:22.835812,2020-03-30 14:19:42.835812,2020-03-30 14:26:22.835812,400.000000
217,218,207,1,1,2020-03-30 14:30:44.828387,2020-03-30 14:37:24.828387,400.000000,6.666667,2020-03-30 14:29:44.828387,2020-03-30 14:38:24.828387,2020-03-30 14:30:44.828387,2020-03-30 14:37:24.828387,400.000000
218,219,208,1,1,2020-03-30 14:43:32.825893,2020-03-30 14:50:12.825893,400.000000,6.666667,2020-03-30 14:42:32.825893,2020-03-30 14:51:12.825893,2020-03-30 14:43:32.825893,2020-03-30 14:50:12.825893,400.000000
219,220,209,1,1,2020-03-30 15:22:52.820368,2020-03-30 15:29:32.820368,400.000000,6.666667,2020-03-30 15:21:52.820368,2020-03-30 15:30:32.820368,2020-03-30 15:22:52.820368,2020-03-30 15:29:32.820368,400.000000
220,221,210,1,1,2020-03-30 22:18:57.899974,2020-03-30 22:25:37.899974,400.000000,6.666667,2020-03-30 22:17:57.899974,2020-03-30 22:26:37.899974,2020-03-30 22:18:57.899974,2020-03-30 22:25:37.899974,400.000000